/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */

import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

import type { Key } from 'swr';

import type { ConfigConfigResponse } from './types';

export type getConfigResponse200 = {
  data: ConfigConfigResponse;
  status: 200;
};

export type getConfigResponse401 = {
  data: string;
  status: 401;
};

export type getConfigResponse429 = {
  data: string;
  status: 429;
};

export type getConfigResponseSuccess = getConfigResponse200 & {
  headers: Headers;
};

export type getConfigResponseError = (
  | getConfigResponse401
  | getConfigResponse429
) & {
  headers: Headers;
};

export type getConfigResponse =
  | getConfigResponseSuccess
  | getConfigResponseError;

export const getGetConfigUrl = () => {
  return `/api/pact/gateway/v1/config`;
};

/**
 * @summary Get live enforcement config
 */
export const getConfig = async (
  options?: RequestInit
): Promise<getConfigResponse> => {
  const res = await fetch(getGetConfigUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getConfigResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getConfigResponse;
};

export const getGetConfigKey = () => [`/api/pact/gateway/v1/config`] as const;
