/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */

import type { Key } from 'swr';

import type {
  ConfigConfigResponse,
  ConfigEnforcementPatchRequest,
} from './types';

import { customFetch } from '../custom_fetch';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type getConfigResponse200 = {
  data: ConfigConfigResponse;
  status: 200;
};

export type getConfigResponse401 = {
  data: string;
  status: 401;
};

export type getConfigResponse429 = {
  data: string;
  status: 429;
};

export type getConfigResponseSuccess = getConfigResponse200 & {
  headers: Headers;
};

export type getConfigResponseError = (
  getConfigResponse401 | getConfigResponse429
) & {
  headers: Headers;
};

export type getConfigResponse =
  getConfigResponseSuccess | getConfigResponseError;

export const getGetConfigUrl = () => {
  return `/api/pact/gateway/v1/config`;
};

/**
 * @summary Get live enforcement config
 */
export const getConfig = async (
  options?: RequestInit
): Promise<getConfigResponse> => {
  return customFetch<getConfigResponse>(getGetConfigUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getGetConfigKey = () => [`/api/pact/gateway/v1/config`] as const;

export type patchEnforcementResponse200 = {
  data: ConfigConfigResponse;
  status: 200;
};

export type patchEnforcementResponse400 = {
  data: string;
  status: 400;
};

export type patchEnforcementResponse401 = {
  data: string;
  status: 401;
};

export type patchEnforcementResponse403 = {
  data: string;
  status: 403;
};

export type patchEnforcementResponse429 = {
  data: string;
  status: 429;
};

export type patchEnforcementResponseSuccess = patchEnforcementResponse200 & {
  headers: Headers;
};

export type patchEnforcementResponseError = (
  | patchEnforcementResponse400
  | patchEnforcementResponse401
  | patchEnforcementResponse403
  | patchEnforcementResponse429
) & {
  headers: Headers;
};

export type patchEnforcementResponse =
  patchEnforcementResponseSuccess | patchEnforcementResponseError;

export const getPatchEnforcementUrl = () => {
  return `/api/pact/gateway/v1/config/enforcement`;
};

/**
 * @summary Flip runtime enforcement mode
 */
export const patchEnforcement = async (
  configEnforcementPatchRequest: ConfigEnforcementPatchRequest,
  options?: RequestInit
): Promise<patchEnforcementResponse> => {
  return customFetch<patchEnforcementResponse>(getPatchEnforcementUrl(), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(configEnforcementPatchRequest),
  });
};

export const getPatchEnforcementMutationFetcher = (
  options?: SecondParameter<typeof customFetch>
) => {
  return (_: Key, { arg }: { arg: ConfigEnforcementPatchRequest }) => {
    return patchEnforcement(arg, options);
  };
};

export const getPatchEnforcementMutationKey = () =>
  [`/api/pact/gateway/v1/config/enforcement`] as const;
