'use client';

/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr';
import useSWRMutation from 'swr/mutation';
import type { Key, SWRConfiguration } from 'swr';
import type { SWRMutationConfiguration } from 'swr/mutation';

import type {
  ConfigConfigResponse,
  ConfigEnforcementPatchRequest,
} from './types';

import {
  getConfigResponse200,
  getConfigResponse401,
  getConfigResponse429,
  getConfigResponseSuccess,
  getConfigResponseError,
  getGetConfigUrl,
  getConfigResponse,
  getConfig,
  getGetConfigKey,
  patchEnforcementResponse200,
  patchEnforcementResponse400,
  patchEnforcementResponse401,
  patchEnforcementResponse403,
  patchEnforcementResponse429,
  patchEnforcementResponseSuccess,
  patchEnforcementResponseError,
  getPatchEnforcementUrl,
  patchEnforcementResponse,
  patchEnforcement,
  getPatchEnforcementMutationFetcher,
  getPatchEnforcementMutationKey,
} from './fetchers';

import { customFetch } from '../custom_fetch';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type GetConfigQueryResult = NonNullable<
  Awaited<ReturnType<typeof getConfig>>
>;

/**
 * @summary Get live enforcement config
 */
export const useGetConfig = <TError = string>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof getConfig>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetConfigKey() : null));
  const swrFn = () => getConfig(requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions
  );

  return {
    swrKey,
    ...query,
  };
};

export type PatchEnforcementMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchEnforcement>>
>;

/**
 * @summary Flip runtime enforcement mode
 */
export const usePatchEnforcement = <TError = string>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof patchEnforcement>>,
    TError,
    Key,
    ConfigEnforcementPatchRequest,
    Awaited<ReturnType<typeof patchEnforcement>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPatchEnforcementMutationKey();
  const swrFn = getPatchEnforcementMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
