/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */

import type { Key } from 'swr';

import type {
  AuditAnnotateDecisionRequest,
  AuditAnnotateDecisionResponse,
  AuditListDecisionAnnotationsRequest,
  AuditListDecisionAnnotationsResponse,
  AuditQueryAuditResponse,
  AuditQueryDecisionStatsResponse,
  AuditQueryPolicyEventsResponse,
  GetAuditEventsParams,
  GetAuditPolicyEventsParams,
  GetAuditStatsParams,
} from './types';

import { customFetch } from '../custom_fetch';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type annotateDecisionResponse200 = {
  data: AuditAnnotateDecisionResponse;
  status: 200;
};

export type annotateDecisionResponse400 = {
  data: string;
  status: 400;
};

export type annotateDecisionResponse401 = {
  data: string;
  status: 401;
};

export type annotateDecisionResponseSuccess = annotateDecisionResponse200 & {
  headers: Headers;
};

export type annotateDecisionResponseError = (
  | annotateDecisionResponse400
  | annotateDecisionResponse401
) & {
  headers: Headers;
};

export type annotateDecisionResponse =
  | annotateDecisionResponseSuccess
  | annotateDecisionResponseError;

export const getAnnotateDecisionUrl = () => {
  return `/api/pact/gateway/v1/audit/annotations`;
};

/**
 * @summary Record an operator annotation on a decision
 */
export const annotateDecision = async (
  auditAnnotateDecisionRequest: AuditAnnotateDecisionRequest,
  options?: RequestInit
): Promise<annotateDecisionResponse> => {
  return customFetch<annotateDecisionResponse>(getAnnotateDecisionUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(auditAnnotateDecisionRequest),
  });
};

export const getAnnotateDecisionMutationFetcher = (
  options?: SecondParameter<typeof customFetch>
) => {
  return (_: Key, { arg }: { arg: AuditAnnotateDecisionRequest }) => {
    return annotateDecision(arg, options);
  };
};

export const getAnnotateDecisionMutationKey = () =>
  [`/api/pact/gateway/v1/audit/annotations`] as const;

export type listDecisionAnnotationsResponse200 = {
  data: AuditListDecisionAnnotationsResponse;
  status: 200;
};

export type listDecisionAnnotationsResponse400 = {
  data: string;
  status: 400;
};

export type listDecisionAnnotationsResponse401 = {
  data: string;
  status: 401;
};

export type listDecisionAnnotationsResponseSuccess =
  listDecisionAnnotationsResponse200 & {
    headers: Headers;
  };

export type listDecisionAnnotationsResponseError = (
  | listDecisionAnnotationsResponse400
  | listDecisionAnnotationsResponse401
) & {
  headers: Headers;
};

export type listDecisionAnnotationsResponse =
  | listDecisionAnnotationsResponseSuccess
  | listDecisionAnnotationsResponseError;

export const getListDecisionAnnotationsUrl = () => {
  return `/api/pact/gateway/v1/audit/annotations/query`;
};

/**
 * @summary Batch-read operator annotations for a set of decisions
 */
export const listDecisionAnnotations = async (
  auditListDecisionAnnotationsRequest: AuditListDecisionAnnotationsRequest,
  options?: RequestInit
): Promise<listDecisionAnnotationsResponse> => {
  return customFetch<listDecisionAnnotationsResponse>(
    getListDecisionAnnotationsUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(auditListDecisionAnnotationsRequest),
    }
  );
};

export const getListDecisionAnnotationsMutationFetcher = (
  options?: SecondParameter<typeof customFetch>
) => {
  return (_: Key, { arg }: { arg: AuditListDecisionAnnotationsRequest }) => {
    return listDecisionAnnotations(arg, options);
  };
};

export const getListDecisionAnnotationsMutationKey = () =>
  [`/api/pact/gateway/v1/audit/annotations/query`] as const;

export type getAuditEventsResponse200 = {
  data: AuditQueryAuditResponse;
  status: 200;
};

export type getAuditEventsResponse400 = {
  data: string;
  status: 400;
};

export type getAuditEventsResponse401 = {
  data: string;
  status: 401;
};

export type getAuditEventsResponseSuccess = getAuditEventsResponse200 & {
  headers: Headers;
};

export type getAuditEventsResponseError = (
  | getAuditEventsResponse400
  | getAuditEventsResponse401
) & {
  headers: Headers;
};

export type getAuditEventsResponse =
  | getAuditEventsResponseSuccess
  | getAuditEventsResponseError;

export const getGetAuditEventsUrl = (params?: GetAuditEventsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/pact/gateway/v1/audit/events?${stringifiedParams}`
    : `/api/pact/gateway/v1/audit/events`;
};

/**
 * @summary Read the caller's audit log
 */
export const getAuditEvents = async (
  params?: GetAuditEventsParams,
  options?: RequestInit
): Promise<getAuditEventsResponse> => {
  return customFetch<getAuditEventsResponse>(getGetAuditEventsUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getGetAuditEventsKey = (params?: GetAuditEventsParams) =>
  [`/api/pact/gateway/v1/audit/events`, ...(params ? [params] : [])] as const;

export type getAuditPolicyEventsResponse200 = {
  data: AuditQueryPolicyEventsResponse;
  status: 200;
};

export type getAuditPolicyEventsResponse400 = {
  data: string;
  status: 400;
};

export type getAuditPolicyEventsResponse401 = {
  data: string;
  status: 401;
};

export type getAuditPolicyEventsResponseSuccess =
  getAuditPolicyEventsResponse200 & {
    headers: Headers;
  };

export type getAuditPolicyEventsResponseError = (
  | getAuditPolicyEventsResponse400
  | getAuditPolicyEventsResponse401
) & {
  headers: Headers;
};

export type getAuditPolicyEventsResponse =
  | getAuditPolicyEventsResponseSuccess
  | getAuditPolicyEventsResponseError;

export const getGetAuditPolicyEventsUrl = (
  params?: GetAuditPolicyEventsParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/pact/gateway/v1/audit/policy-events?${stringifiedParams}`
    : `/api/pact/gateway/v1/audit/policy-events`;
};

/**
 * @summary Read the caller's policy decisions
 */
export const getAuditPolicyEvents = async (
  params?: GetAuditPolicyEventsParams,
  options?: RequestInit
): Promise<getAuditPolicyEventsResponse> => {
  return customFetch<getAuditPolicyEventsResponse>(
    getGetAuditPolicyEventsUrl(params),
    {
      ...options,
      method: 'GET',
    }
  );
};

export const getGetAuditPolicyEventsKey = (
  params?: GetAuditPolicyEventsParams
) =>
  [
    `/api/pact/gateway/v1/audit/policy-events`,
    ...(params ? [params] : []),
  ] as const;

export type getAuditStatsResponse200 = {
  data: AuditQueryDecisionStatsResponse;
  status: 200;
};

export type getAuditStatsResponse400 = {
  data: string;
  status: 400;
};

export type getAuditStatsResponse401 = {
  data: string;
  status: 401;
};

export type getAuditStatsResponse403 = {
  data: string;
  status: 403;
};

export type getAuditStatsResponseSuccess = getAuditStatsResponse200 & {
  headers: Headers;
};

export type getAuditStatsResponseError = (
  | getAuditStatsResponse400
  | getAuditStatsResponse401
  | getAuditStatsResponse403
) & {
  headers: Headers;
};

export type getAuditStatsResponse =
  | getAuditStatsResponseSuccess
  | getAuditStatsResponseError;

export const getGetAuditStatsUrl = (params?: GetAuditStatsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/pact/gateway/v1/audit/stats?${stringifiedParams}`
    : `/api/pact/gateway/v1/audit/stats`;
};

/**
 * @summary Read aggregate decision stats for the pipeline dashboard
 */
export const getAuditStats = async (
  params?: GetAuditStatsParams,
  options?: RequestInit
): Promise<getAuditStatsResponse> => {
  return customFetch<getAuditStatsResponse>(getGetAuditStatsUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getGetAuditStatsKey = (params?: GetAuditStatsParams) =>
  [`/api/pact/gateway/v1/audit/stats`, ...(params ? [params] : [])] as const;
