/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * Audit Service
 * Read window into the append-only audit log for the signed-in
 * user. Mounted on pact-gateway at /v1/audit/*; the gateway resolves
 * user_id from the session cookie and forwards it to pact-audit as a
 * hard filter, so a regular caller can only see their own rows.
 *
 * pact-audit has no notion of identity: whoever holds a connection
 * to the gRPC :9590 listener reads anything they ask for. The gateway
 * is the only gate between the SPA and unfiltered access. There is
 * no admin override today; cross-user reads will land once sessions
 * carry an admin claim.
 *
 * The payloadJson field is the raw JSONB column from audit_events.
 * Schema is per-topic and evolves over time; decode lazily and
 * tolerate unknown fields.
 *
 * This spec is hand-maintained (schema/audit/services.config.json
 * sets "manual": true) because pact-audit is a gRPC-only service
 * with no swagger of its own; pact-gateway owns the REST surface
 * as a proxy and publishes its own per-tag slice at
 * api/swagger/audit.yaml. Keep this file in sync by hand when that
 * slice's audit paths change shape.
 *
 * OpenAPI spec version: 0.1.0
 */

import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

import type { Key } from 'swr';

import type {
  BadRequestResponse,
  ForbiddenResponse,
  QueryAuditEventsParams,
  QueryAuditEventsResponse,
  QueryDecisionStatsParams,
  QueryDecisionStatsResponse,
  QueryPolicyEventsParams,
  QueryPolicyEventsResponse,
  TooManyRequestsResponse,
  UnauthorizedResponse,
} from './types';

export type queryAuditEventsResponse200 = {
  data: QueryAuditEventsResponse;
  status: 200;
};

export type queryAuditEventsResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type queryAuditEventsResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type queryAuditEventsResponse429 = {
  data: TooManyRequestsResponse;
  status: 429;
};

export type queryAuditEventsResponseSuccess = queryAuditEventsResponse200 & {
  headers: Headers;
};

export type queryAuditEventsResponseError = (
  | queryAuditEventsResponse400
  | queryAuditEventsResponse401
  | queryAuditEventsResponse429
) & {
  headers: Headers;
};

export type queryAuditEventsResponse =
  | queryAuditEventsResponseSuccess
  | queryAuditEventsResponseError;

export const getQueryAuditEventsUrl = (params?: QueryAuditEventsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/audit/events?${stringifiedParams}`
    : `/v1/audit/events`;
};

/**
 * Paginated, newest-first view of the immutable audit log
 * belonging to the caller. limit is clamped server-side
 * (default 50, max 200). offset is stable as long as no new
 * rows land between calls -- since the Kafka consumer is
 * always writing, the SPA should refetch from offset=0 when
 * a filter changes or new rows are expected.
 *
 * @summary List the caller's audit events, newest first
 */
export const queryAuditEvents = async (
  params?: QueryAuditEventsParams,
  options?: RequestInit
): Promise<queryAuditEventsResponse> => {
  const res = await fetch(getQueryAuditEventsUrl(params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: queryAuditEventsResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as queryAuditEventsResponse;
};

export const getQueryAuditEventsKey = (params?: QueryAuditEventsParams) =>
  [`/v1/audit/events`, ...(params ? [params] : [])] as const;

export type queryDecisionStatsResponse200 = {
  data: QueryDecisionStatsResponse;
  status: 200;
};

export type queryDecisionStatsResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type queryDecisionStatsResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type queryDecisionStatsResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type queryDecisionStatsResponseSuccess =
  queryDecisionStatsResponse200 & {
    headers: Headers;
  };

export type queryDecisionStatsResponseError = (
  | queryDecisionStatsResponse400
  | queryDecisionStatsResponse401
  | queryDecisionStatsResponse403
) & {
  headers: Headers;
};

export type queryDecisionStatsResponse =
  | queryDecisionStatsResponseSuccess
  | queryDecisionStatsResponseError;

export const getQueryDecisionStatsUrl = (params?: QueryDecisionStatsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/audit/stats?${stringifiedParams}`
    : `/v1/audit/stats`;
};

/**
 * Server-side aggregate over the caller's pact.decisions rows in
 * [sinceUnix, untilUnix). Both bounds are optional; omitting both
 * aggregates over all of the caller's history. Mirrors the shape
 * of the client-side aggregatePipelineStats helper it replaces,
 * field for field, but computed exactly instead of over a
 * 200-event window.
 *
 * Gated behind the audit:stats permission (operator/admin only);
 * a caller without it gets a 403, not a filtered result.
 *
 * @summary Read aggregate decision stats for the pipeline dashboard
 */
export const queryDecisionStats = async (
  params?: QueryDecisionStatsParams,
  options?: RequestInit
): Promise<queryDecisionStatsResponse> => {
  const res = await fetch(getQueryDecisionStatsUrl(params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: queryDecisionStatsResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as queryDecisionStatsResponse;
};

export const getQueryDecisionStatsKey = (params?: QueryDecisionStatsParams) =>
  [`/v1/audit/stats`, ...(params ? [params] : [])] as const;

export type queryPolicyEventsResponse200 = {
  data: QueryPolicyEventsResponse;
  status: 200;
};

export type queryPolicyEventsResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type queryPolicyEventsResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type queryPolicyEventsResponseSuccess = queryPolicyEventsResponse200 & {
  headers: Headers;
};

export type queryPolicyEventsResponseError = (
  | queryPolicyEventsResponse400
  | queryPolicyEventsResponse401
) & {
  headers: Headers;
};

export type queryPolicyEventsResponse =
  | queryPolicyEventsResponseSuccess
  | queryPolicyEventsResponseError;

export const getQueryPolicyEventsUrl = (params?: QueryPolicyEventsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/audit/policy-events?${stringifiedParams}`
    : `/v1/audit/policy-events`;
};

/**
 * Paginated, newest-first view of the caller's pact.policy events --
 * one row per capability-token evaluation the gateway ran during a
 * /v1/check request. The topic is hard-scoped server-side to
 * pact.policy; callers cannot override it via the query string.
 *
 * Populated once pact-audit consumes the pact.policy topic
 * (PACT-308). Until then this returns an empty page, not an error --
 * an empty policy feed is expected in early deployments, not a bug.
 *
 * @summary Read the caller's policy decisions
 */
export const queryPolicyEvents = async (
  params?: QueryPolicyEventsParams,
  options?: RequestInit
): Promise<queryPolicyEventsResponse> => {
  const res = await fetch(getQueryPolicyEventsUrl(params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: queryPolicyEventsResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as queryPolicyEventsResponse;
};

export const getQueryPolicyEventsKey = (params?: QueryPolicyEventsParams) =>
  [`/v1/audit/policy-events`, ...(params ? [params] : [])] as const;
