'use client';

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr';
import useSWRMutation from 'swr/mutation';
import type { Arguments, Key, SWRConfiguration } from 'swr';
import type { SWRMutationConfiguration } from 'swr/mutation';

import type {
  AuditAnnotateDecisionRequest,
  AuditAnnotateDecisionResponse,
  AuditListDecisionAnnotationsRequest,
  AuditListDecisionAnnotationsResponse,
  AuditQueryAuditResponse,
  AuditQueryDecisionStatsResponse,
  AuditQueryPolicyEventsResponse,
  AuditRemoveDecisionAnnotationResponse,
  BoundaryErrorResponse,
  GetAuditEventsParams,
  GetAuditPolicyEventsParams,
  GetAuditStatsParams,
  RemoveDecisionAnnotationParams,
} from './types';

import {
  removeDecisionAnnotationResponse200,
  removeDecisionAnnotationResponse400,
  removeDecisionAnnotationResponse401,
  removeDecisionAnnotationResponseSuccess,
  removeDecisionAnnotationResponseError,
  getRemoveDecisionAnnotationUrl,
  removeDecisionAnnotationResponse,
  removeDecisionAnnotation,
  getRemoveDecisionAnnotationMutationFetcher,
  getRemoveDecisionAnnotationMutationKey,
  annotateDecisionResponse200,
  annotateDecisionResponse400,
  annotateDecisionResponse401,
  annotateDecisionResponseSuccess,
  annotateDecisionResponseError,
  getAnnotateDecisionUrl,
  annotateDecisionResponse,
  annotateDecision,
  getAnnotateDecisionMutationFetcher,
  getAnnotateDecisionMutationKey,
  listDecisionAnnotationsResponse200,
  listDecisionAnnotationsResponse400,
  listDecisionAnnotationsResponse401,
  listDecisionAnnotationsResponseSuccess,
  listDecisionAnnotationsResponseError,
  getListDecisionAnnotationsUrl,
  listDecisionAnnotationsResponse,
  listDecisionAnnotations,
  getListDecisionAnnotationsMutationFetcher,
  getListDecisionAnnotationsMutationKey,
  getAuditEventsResponse200,
  getAuditEventsResponse400,
  getAuditEventsResponse401,
  getAuditEventsResponseSuccess,
  getAuditEventsResponseError,
  getGetAuditEventsUrl,
  getAuditEventsResponse,
  getAuditEvents,
  getGetAuditEventsKey,
  getAuditPolicyEventsResponse200,
  getAuditPolicyEventsResponse400,
  getAuditPolicyEventsResponse401,
  getAuditPolicyEventsResponseSuccess,
  getAuditPolicyEventsResponseError,
  getGetAuditPolicyEventsUrl,
  getAuditPolicyEventsResponse,
  getAuditPolicyEvents,
  getGetAuditPolicyEventsKey,
  getAuditStatsResponse200,
  getAuditStatsResponse400,
  getAuditStatsResponse401,
  getAuditStatsResponse403,
  getAuditStatsResponseSuccess,
  getAuditStatsResponseError,
  getGetAuditStatsUrl,
  getAuditStatsResponse,
  getAuditStats,
  getGetAuditStatsKey,
} from './fetchers';

import { customFetch } from '../custom_fetch';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type RemoveDecisionAnnotationMutationResult = NonNullable<
  Awaited<ReturnType<typeof removeDecisionAnnotation>>
>;

/**
 * @summary Remove an operator annotation on a decision
 */
export const useRemoveDecisionAnnotation = <TError = string>(
  params: RemoveDecisionAnnotationParams,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof removeDecisionAnnotation>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof removeDecisionAnnotation>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customFetch>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey =
    swrOptions?.swrKey ?? getRemoveDecisionAnnotationMutationKey(params);
  const swrFn = getRemoveDecisionAnnotationMutationFetcher(
    params,
    requestOptions
  );

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type AnnotateDecisionMutationResult = NonNullable<
  Awaited<ReturnType<typeof annotateDecision>>
>;

/**
 * @summary Record an operator annotation on a decision
 */
export const useAnnotateDecision = <
  TError = BoundaryErrorResponse | string,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof annotateDecision>>,
    TError,
    Key,
    AuditAnnotateDecisionRequest,
    Awaited<ReturnType<typeof annotateDecision>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getAnnotateDecisionMutationKey();
  const swrFn = getAnnotateDecisionMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type ListDecisionAnnotationsMutationResult = NonNullable<
  Awaited<ReturnType<typeof listDecisionAnnotations>>
>;

/**
 * @summary Batch-read operator annotations for a set of decisions
 */
export const useListDecisionAnnotations = <
  TError = BoundaryErrorResponse | string,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof listDecisionAnnotations>>,
    TError,
    Key,
    AuditListDecisionAnnotationsRequest,
    Awaited<ReturnType<typeof listDecisionAnnotations>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getListDecisionAnnotationsMutationKey();
  const swrFn = getListDecisionAnnotationsMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type GetAuditEventsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuditEvents>>
>;

/**
 * @summary Read the caller's audit log
 */
export const useGetAuditEvents = <TError = string>(
  params?: GetAuditEventsParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof getAuditEvents>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    request?: SecondParameter<typeof customFetch>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getGetAuditEventsKey(params) : null));
  const swrFn = () => getAuditEvents(params, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions
  );

  return {
    swrKey,
    ...query,
  };
};

export type GetAuditPolicyEventsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuditPolicyEvents>>
>;

/**
 * @summary Read the caller's policy decisions
 */
export const useGetAuditPolicyEvents = <TError = string>(
  params?: GetAuditPolicyEventsParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof getAuditPolicyEvents>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    request?: SecondParameter<typeof customFetch>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getGetAuditPolicyEventsKey(params) : null));
  const swrFn = () => getAuditPolicyEvents(params, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions
  );

  return {
    swrKey,
    ...query,
  };
};

export type GetAuditStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuditStats>>
>;

/**
 * @summary Read aggregate decision stats for the pipeline dashboard
 */
export const useGetAuditStats = <TError = string>(
  params?: GetAuditStatsParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof getAuditStats>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    request?: SecondParameter<typeof customFetch>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getGetAuditStatsKey(params) : null));
  const swrFn = () => getAuditStats(params, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions
  );

  return {
    swrKey,
    ...query,
  };
};
