'use client';

/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * Audit Service
 * Read window into the append-only audit log for the signed-in
 * user. Mounted on pact-gateway at /v1/audit/*; the gateway resolves
 * user_id from the session cookie and forwards it to pact-audit as a
 * hard filter, so a regular caller can only see their own rows.
 *
 * pact-audit has no notion of identity: whoever holds a connection
 * to the gRPC :9590 listener reads anything they ask for. The gateway
 * is the only gate between the SPA and unfiltered access. There is
 * no admin override today; cross-user reads will land once sessions
 * carry an admin claim.
 *
 * The payloadJson field is the raw JSONB column from audit_events.
 * Schema is per-topic and evolves over time; decode lazily and
 * tolerate unknown fields.
 *
 * This spec is hand-maintained (schema/audit/services.config.json
 * sets "manual": true) because pact-audit is a gRPC-only service
 * with no swagger of its own; pact-gateway owns the REST surface
 * as a proxy and publishes its own per-tag slice at
 * api/swagger/audit.yaml. Keep this file in sync by hand when that
 * slice's audit paths change shape.
 *
 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr';
import useSWRMutation from 'swr/mutation';
import type { Key, SWRConfiguration } from 'swr';
import type { SWRMutationConfiguration } from 'swr/mutation';

import type { AxiosError, AxiosRequestConfig } from 'axios';

import type {
  AnnotateDecisionRequest,
  AnnotateDecisionResponse,
  BadRequestResponse,
  ForbiddenResponse,
  ListDecisionAnnotationsRequest,
  ListDecisionAnnotationsResponse,
  PlainTextBadRequestResponse,
  PlainTextUnauthorizedResponse,
  QueryAuditEventsParams,
  QueryAuditEventsResponse,
  QueryDecisionStatsParams,
  QueryDecisionStatsResponse,
  QueryPolicyEventsParams,
  QueryPolicyEventsResponse,
  TooManyRequestsResponse,
  UnauthorizedResponse,
} from './types';

import {
  queryAuditEventsResponse200,
  queryAuditEventsResponse400,
  queryAuditEventsResponse401,
  queryAuditEventsResponse429,
  queryAuditEventsResponseSuccess,
  queryAuditEventsResponseError,
  getQueryAuditEventsUrl,
  queryAuditEventsResponse,
  queryAuditEvents,
  getQueryAuditEventsKey,
  queryDecisionStatsResponse200,
  queryDecisionStatsResponse400,
  queryDecisionStatsResponse401,
  queryDecisionStatsResponse403,
  queryDecisionStatsResponseSuccess,
  queryDecisionStatsResponseError,
  getQueryDecisionStatsUrl,
  queryDecisionStatsResponse,
  queryDecisionStats,
  getQueryDecisionStatsKey,
  queryPolicyEventsResponse200,
  queryPolicyEventsResponse400,
  queryPolicyEventsResponse401,
  queryPolicyEventsResponseSuccess,
  queryPolicyEventsResponseError,
  getQueryPolicyEventsUrl,
  queryPolicyEventsResponse,
  queryPolicyEvents,
  getQueryPolicyEventsKey,
  annotateDecisionResponse200,
  annotateDecisionResponse400,
  annotateDecisionResponse401,
  annotateDecisionResponseSuccess,
  annotateDecisionResponseError,
  getAnnotateDecisionUrl,
  annotateDecisionResponse,
  annotateDecision,
  getAnnotateDecisionMutationFetcher,
  getAnnotateDecisionMutationKey,
  listDecisionAnnotationsResponse200,
  listDecisionAnnotationsResponse400,
  listDecisionAnnotationsResponse401,
  listDecisionAnnotationsResponseSuccess,
  listDecisionAnnotationsResponseError,
  getListDecisionAnnotationsUrl,
  listDecisionAnnotationsResponse,
  listDecisionAnnotations,
  getListDecisionAnnotationsMutationFetcher,
  getListDecisionAnnotationsMutationKey,
} from './fetchers';

export type QueryAuditEventsQueryResult = NonNullable<
  Awaited<ReturnType<typeof queryAuditEvents>>
>;

/**
 * @summary List the caller's audit events, newest first
 */
export const useQueryAuditEvents = <
  TError = Promise<
    BadRequestResponse | UnauthorizedResponse | TooManyRequestsResponse
  >,
>(
  params?: QueryAuditEventsParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof queryAuditEvents>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    fetch?: RequestInit;
  }
) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getQueryAuditEventsKey(params) : null));
  const swrFn = () => queryAuditEvents(params, fetchOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions
  );

  return {
    swrKey,
    ...query,
  };
};

export type QueryDecisionStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof queryDecisionStats>>
>;

/**
 * @summary Read aggregate decision stats for the pipeline dashboard
 */
export const useQueryDecisionStats = <
  TError = Promise<
    BadRequestResponse | UnauthorizedResponse | ForbiddenResponse
  >,
>(
  params?: QueryDecisionStatsParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof queryDecisionStats>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    fetch?: RequestInit;
  }
) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getQueryDecisionStatsKey(params) : null));
  const swrFn = () => queryDecisionStats(params, fetchOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions
  );

  return {
    swrKey,
    ...query,
  };
};

export type QueryPolicyEventsQueryResult = NonNullable<
  Awaited<ReturnType<typeof queryPolicyEvents>>
>;

/**
 * @summary Read the caller's policy decisions
 */
export const useQueryPolicyEvents = <
  TError = Promise<BadRequestResponse | UnauthorizedResponse>,
>(
  params?: QueryPolicyEventsParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof queryPolicyEvents>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    fetch?: RequestInit;
  }
) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getQueryPolicyEventsKey(params) : null));
  const swrFn = () => queryPolicyEvents(params, fetchOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions
  );

  return {
    swrKey,
    ...query,
  };
};

export type AnnotateDecisionMutationResult = NonNullable<
  Awaited<ReturnType<typeof annotateDecision>>
>;

/**
 * @summary Record an operator annotation on a decision
 */
export const useAnnotateDecision = <
  TError = Promise<PlainTextBadRequestResponse | PlainTextUnauthorizedResponse>,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof annotateDecision>>,
    TError,
    Key,
    AnnotateDecisionRequest,
    Awaited<ReturnType<typeof annotateDecision>>
  > & { swrKey?: string };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getAnnotateDecisionMutationKey();
  const swrFn = getAnnotateDecisionMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type ListDecisionAnnotationsMutationResult = NonNullable<
  Awaited<ReturnType<typeof listDecisionAnnotations>>
>;

/**
 * @summary Batch-read operator annotations for a set of decisions
 */
export const useListDecisionAnnotations = <
  TError = Promise<PlainTextBadRequestResponse | PlainTextUnauthorizedResponse>,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof listDecisionAnnotations>>,
    TError,
    Key,
    ListDecisionAnnotationsRequest,
    Awaited<ReturnType<typeof listDecisionAnnotations>>
  > & { swrKey?: string };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getListDecisionAnnotationsMutationKey();
  const swrFn = getListDecisionAnnotationsMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
