import { defineConfig } from 'orval';

// Auto-generated by scripts/rest-codegen.mjs — do not edit manually.
// Run `pnpm rest:codegen` to regenerate from schema/ swagger specs.
export default defineConfig({});
