/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */

export interface ClassifierLabelVerdictRequest {
  content?: string;
  correctionLabel?: string;
  note?: string;
  operatorLabel?: string;
  predictedConfidence?: number;
  predictedLabel?: string;
  requestId?: string;
  source?: string;
}
