/**
 * Generated by orval 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */
import type { AuditDecisionStatsClassifier } from './auditDecisionStatsClassifier';
import type { AuditDecisionStatsFilter } from './auditDecisionStatsFilter';
import type { AuditDecisionStatsRedactor } from './auditDecisionStatsRedactor';

export interface AuditQueryDecisionStatsResponse {
  classifier?: AuditDecisionStatsClassifier;
  filter?: AuditDecisionStatsFilter;
  latest_at_unix?: number;
  redactor?: AuditDecisionStatsRedactor;
  total?: number;
}
