/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * Audit Service
 * Read window into the append-only audit log for the signed-in
 * user. Mounted on pact-gateway at /v1/audit/*; the gateway resolves
 * user_id from the session cookie and forwards it to pact-audit as a
 * hard filter, so a regular caller can only see their own rows.
 *
 * pact-audit has no notion of identity: whoever holds a connection
 * to the gRPC :9590 listener reads anything they ask for. The gateway
 * is the only gate between the SPA and unfiltered access. There is
 * no admin override today; cross-user reads will land once sessions
 * carry an admin claim.
 *
 * The payloadJson field is the raw JSONB column from audit_events.
 * Schema is per-topic and evolves over time; decode lazily and
 * tolerate unknown fields.
 *
 * OpenAPI spec version: 0.1.0
 */

export interface AuditEvent {
  id: string;
  /** Kafka topic the underlying record came from. Stable values
   * today: pact.auth, pact.account, pact.files, pact.decisions.
   *  */
  topic: string;
  /** Producer-assigned event type (e.g. "user.logged_in"). May
   * be empty for legacy rows that pre-date the field.
   *  */
  eventId: string;
  /** Omitted when the underlying row has user_id IS NULL. */
  userId?: string;
  /** Gateway-assigned correlation id; may be empty. */
  requestId?: string;
  /** Raw JSONB payload from audit_events. Schema is per-topic
   * and evolves over time; clients should decode lazily and
   * tolerate unknown fields.
   *  */
  payloadJson: string;
  createdAt: string;
}
