/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * Audit Service
 * Read window into the append-only audit log for the signed-in
 * user. Mounted on pact-gateway at /v1/audit/*; the gateway resolves
 * user_id from the session cookie and forwards it to pact-audit as a
 * hard filter, so a regular caller can only see their own rows.
 *
 * pact-audit has no notion of identity: whoever holds a connection
 * to the gRPC :9590 listener reads anything they ask for. The gateway
 * is the only gate between the SPA and unfiltered access. There is
 * no admin override today; cross-user reads will land once sessions
 * carry an admin claim.
 *
 * The payloadJson field is the raw JSONB column from audit_events.
 * Schema is per-topic and evolves over time; decode lazily and
 * tolerate unknown fields.
 *
 * This spec is hand-maintained (schema/audit/services.config.json
 * sets "manual": true) because pact-audit is a gRPC-only service
 * with no swagger of its own; pact-gateway owns the REST surface
 * as a proxy and publishes its own per-tag slice at
 * api/swagger/audit.yaml. Keep this file in sync by hand when that
 * slice's audit paths change shape.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { DecisionStatsLabelCount } from './decisionStatsLabelCount';

export interface DecisionStatsClassifier {
  /** Decisions where the classifier returned a label. */
  responded: number;
  /** Decisions tagged with a non-benign label. */
  tagged: number;
  /** Most frequent non-benign label; empty if none. */
  top_label: string;
  /** Mean score across tagged decisions, as a 0-100 percentage. */
  avg_tagged_score: number;
  /** Decisions arbitrated by pact-consensus (sub-object present, not skipped). */
  consensus: number;
  /** Non-benign label distribution, highest first, max 3. */
  labels: DecisionStatsLabelCount[];
}
