/**
 * Generated by orval 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */

export type GetAuditStatsParams = {
  /**
   * Inclusive lower bound on createdAt (unix seconds UTC)
   */
  sinceUnix?: number;
  /**
   * Exclusive upper bound on createdAt (unix seconds UTC)
   */
  untilUnix?: number;
};
