/**
 * Generated by orval 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */

export type GetAuditPolicyEventsParams = {
  /**
   * Inclusive lower bound on createdAt (unix seconds UTC)
   */
  sinceUnix?: number;
  /**
   * Page size 1..200 (default 50)
   */
  limit?: number;
  /**
   * Page offset >= 0 (default 0)
   */
  offset?: number;
};
