/**
 * Generated by orval 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */

export type RemoveDecisionAnnotationKind =
  (typeof RemoveDecisionAnnotationKind)[keyof typeof RemoveDecisionAnnotationKind];

export const RemoveDecisionAnnotationKind = {
  false_positive: 'false_positive',
} as const;
