/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */

import type { Arguments, Key } from 'swr';

import type {
  AuthBeginMfaPasskeyAssertionRequest,
  AuthBeginPasskeyLoginRequest,
  AuthBeginPasskeyRegistrationRequest,
  AuthBeginTOTPEnrollmentResponse,
  AuthConfirmPasswordResetRequest,
  AuthConfirmTOTPEnrollmentRequest,
  AuthFinishMfaPasskeyAssertionRequest,
  AuthFinishPasskeyLoginRequest,
  AuthFinishPasskeyRegistrationRequest,
  AuthFinishPasskeyRegistrationResponse,
  AuthHandleCallbackRequest,
  AuthListIdentitiesResponse,
  AuthListMfaFactorsResponse,
  AuthListPasskeysResponse,
  AuthLoginRequest,
  AuthPasskeyCeremonyResponse,
  AuthRecoveryCodesResponse,
  AuthRefreshSessionRequest,
  AuthRegisterRequest,
  AuthRenamePasskeyRequest,
  AuthRequestPasswordResetRequest,
  AuthResendVerificationRequest,
  AuthSessionIntrospectionResponse,
  AuthSessionResponse,
  AuthStartLoginResponse,
  AuthVerifyEmailRequest,
  AuthVerifyMfaRequest,
  BoundaryErrorResponse,
  StartOAuthLoginParams,
} from './types';

import { customFetch } from '../custom_fetch';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type listIdentitiesResponse200 = {
  data: AuthListIdentitiesResponse;
  status: 200;
};

export type listIdentitiesResponse401 = {
  data: string;
  status: 401;
};

export type listIdentitiesResponseSuccess = listIdentitiesResponse200 & {
  headers: Headers;
};

export type listIdentitiesResponseError = listIdentitiesResponse401 & {
  headers: Headers;
};

export type listIdentitiesResponse =
  listIdentitiesResponseSuccess | listIdentitiesResponseError;

export const getListIdentitiesUrl = () => {
  return `/api/pact/gateway/v1/auth/identities`;
};

/**
 * @summary List the signed-in user's linked OAuth identities
 */
export const listIdentities = async (
  options?: RequestInit
): Promise<listIdentitiesResponse> => {
  return customFetch<listIdentitiesResponse>(getListIdentitiesUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getListIdentitiesKey = () =>
  [`/api/pact/gateway/v1/auth/identities`] as const;

export type unlinkIdentityResponse204 = {
  data: void;
  status: 204;
};

export type unlinkIdentityResponse401 = {
  data: string;
  status: 401;
};

export type unlinkIdentityResponse404 = {
  data: BoundaryErrorResponse;
  status: 404;
};

export type unlinkIdentityResponseSuccess = unlinkIdentityResponse204 & {
  headers: Headers;
};

export type unlinkIdentityResponseError = (
  unlinkIdentityResponse401 | unlinkIdentityResponse404
) & {
  headers: Headers;
};

export type unlinkIdentityResponse =
  unlinkIdentityResponseSuccess | unlinkIdentityResponseError;

export const getUnlinkIdentityUrl = (provider: string) => {
  return `/api/pact/gateway/v1/auth/identities/${provider}`;
};

/**
 * @summary Unlink a federated OAuth identity
 */
export const unlinkIdentity = async (
  provider: string,
  options?: RequestInit
): Promise<unlinkIdentityResponse> => {
  return customFetch<unlinkIdentityResponse>(getUnlinkIdentityUrl(provider), {
    ...options,
    method: 'DELETE',
  });
};

export const getUnlinkIdentityMutationFetcher = (
  provider: string,
  options?: SecondParameter<typeof customFetch>
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return unlinkIdentity(provider, options);
  };
};

export const getUnlinkIdentityMutationKey = (provider: string) =>
  [`/api/pact/gateway/v1/auth/identities/${provider}`] as const;

export type loginResponse200 = {
  data: AuthSessionResponse;
  status: 200;
};

export type loginResponse400 = {
  data: BoundaryErrorResponse;
  status: 400;
};

export type loginResponse401 = {
  data: BoundaryErrorResponse;
  status: 401;
};

export type loginResponseSuccess = loginResponse200 & {
  headers: Headers;
};

export type loginResponseError = (loginResponse400 | loginResponse401) & {
  headers: Headers;
};

export type loginResponse = loginResponseSuccess | loginResponseError;

export const getLoginUrl = () => {
  return `/api/pact/gateway/v1/auth/login`;
};

/**
 * @summary Log in with email and password
 */
export const login = async (
  authLoginRequest: AuthLoginRequest,
  options?: RequestInit
): Promise<loginResponse> => {
  return customFetch<loginResponse>(getLoginUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(authLoginRequest),
  });
};

export const getLoginMutationFetcher = (
  options?: SecondParameter<typeof customFetch>
) => {
  return (_: Key, { arg }: { arg: AuthLoginRequest }) => {
    return login(arg, options);
  };
};

export const getLoginMutationKey = () =>
  [`/api/pact/gateway/v1/auth/login`] as const;

export type logoutResponse204 = {
  data: void;
  status: 204;
};

export type logoutResponse401 = {
  data: string;
  status: 401;
};

export type logoutResponseSuccess = logoutResponse204 & {
  headers: Headers;
};

export type logoutResponseError = logoutResponse401 & {
  headers: Headers;
};

export type logoutResponse = logoutResponseSuccess | logoutResponseError;

export const getLogoutUrl = () => {
  return `/api/pact/gateway/v1/auth/logout`;
};

/**
 * @summary Revoke the signed-in session
 */
export const logout = async (
  options?: RequestInit
): Promise<logoutResponse> => {
  return customFetch<logoutResponse>(getLogoutUrl(), {
    ...options,
    method: 'POST',
  });
};

export const getLogoutMutationFetcher = (
  options?: SecondParameter<typeof customFetch>
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return logout(options);
  };
};

export const getLogoutMutationKey = () =>
  [`/api/pact/gateway/v1/auth/logout`] as const;

export type listMfaFactorsResponse200 = {
  data: AuthListMfaFactorsResponse;
  status: 200;
};

export type listMfaFactorsResponse401 = {
  data: string;
  status: 401;
};

export type listMfaFactorsResponseSuccess = listMfaFactorsResponse200 & {
  headers: Headers;
};

export type listMfaFactorsResponseError = listMfaFactorsResponse401 & {
  headers: Headers;
};

export type listMfaFactorsResponse =
  listMfaFactorsResponseSuccess | listMfaFactorsResponseError;

export const getListMfaFactorsUrl = () => {
  return `/api/pact/gateway/v1/auth/mfa/factors`;
};

/**
 * @summary List the signed-in user's enrolled MFA factors
 */
export const listMfaFactors = async (
  options?: RequestInit
): Promise<listMfaFactorsResponse> => {
  return customFetch<listMfaFactorsResponse>(getListMfaFactorsUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getListMfaFactorsKey = () =>
  [`/api/pact/gateway/v1/auth/mfa/factors`] as const;

export type revokeMfaFactorResponse204 = {
  data: void;
  status: 204;
};

export type revokeMfaFactorResponse401 = {
  data: string;
  status: 401;
};

export type revokeMfaFactorResponse404 = {
  data: BoundaryErrorResponse;
  status: 404;
};

export type revokeMfaFactorResponseSuccess = revokeMfaFactorResponse204 & {
  headers: Headers;
};

export type revokeMfaFactorResponseError = (
  revokeMfaFactorResponse401 | revokeMfaFactorResponse404
) & {
  headers: Headers;
};

export type revokeMfaFactorResponse =
  revokeMfaFactorResponseSuccess | revokeMfaFactorResponseError;

export const getRevokeMfaFactorUrl = (factorId: string) => {
  return `/api/pact/gateway/v1/auth/mfa/factors/${factorId}`;
};

/**
 * @summary Revoke an enrolled MFA factor
 */
export const revokeMfaFactor = async (
  factorId: string,
  options?: RequestInit
): Promise<revokeMfaFactorResponse> => {
  return customFetch<revokeMfaFactorResponse>(getRevokeMfaFactorUrl(factorId), {
    ...options,
    method: 'DELETE',
  });
};

export const getRevokeMfaFactorMutationFetcher = (
  factorId: string,
  options?: SecondParameter<typeof customFetch>
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return revokeMfaFactor(factorId, options);
  };
};

export const getRevokeMfaFactorMutationKey = (factorId: string) =>
  [`/api/pact/gateway/v1/auth/mfa/factors/${factorId}`] as const;

export type beginMfaPasskeyAssertionResponse200 = {
  data: AuthPasskeyCeremonyResponse;
  status: 200;
};

export type beginMfaPasskeyAssertionResponse400 = {
  data: BoundaryErrorResponse;
  status: 400;
};

export type beginMfaPasskeyAssertionResponse401 = {
  data: BoundaryErrorResponse;
  status: 401;
};

export type beginMfaPasskeyAssertionResponseSuccess =
  beginMfaPasskeyAssertionResponse200 & {
    headers: Headers;
  };

export type beginMfaPasskeyAssertionResponseError = (
  beginMfaPasskeyAssertionResponse400 | beginMfaPasskeyAssertionResponse401
) & {
  headers: Headers;
};

export type beginMfaPasskeyAssertionResponse =
  | beginMfaPasskeyAssertionResponseSuccess
  | beginMfaPasskeyAssertionResponseError;

export const getBeginMfaPasskeyAssertionUrl = () => {
  return `/api/pact/gateway/v1/auth/mfa/passkey/begin`;
};

/**
 * @summary Begin a passkey-assertion MFA step-up
 */
export const beginMfaPasskeyAssertion = async (
  authBeginMfaPasskeyAssertionRequest: AuthBeginMfaPasskeyAssertionRequest,
  options?: RequestInit
): Promise<beginMfaPasskeyAssertionResponse> => {
  return customFetch<beginMfaPasskeyAssertionResponse>(
    getBeginMfaPasskeyAssertionUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(authBeginMfaPasskeyAssertionRequest),
    }
  );
};

export const getBeginMfaPasskeyAssertionMutationFetcher = (
  options?: SecondParameter<typeof customFetch>
) => {
  return (_: Key, { arg }: { arg: AuthBeginMfaPasskeyAssertionRequest }) => {
    return beginMfaPasskeyAssertion(arg, options);
  };
};

export const getBeginMfaPasskeyAssertionMutationKey = () =>
  [`/api/pact/gateway/v1/auth/mfa/passkey/begin`] as const;

export type finishMfaPasskeyAssertionResponse200 = {
  data: AuthSessionResponse;
  status: 200;
};

export type finishMfaPasskeyAssertionResponse400 = {
  data: BoundaryErrorResponse;
  status: 400;
};

export type finishMfaPasskeyAssertionResponse401 = {
  data: BoundaryErrorResponse;
  status: 401;
};

export type finishMfaPasskeyAssertionResponseSuccess =
  finishMfaPasskeyAssertionResponse200 & {
    headers: Headers;
  };

export type finishMfaPasskeyAssertionResponseError = (
  finishMfaPasskeyAssertionResponse400 | finishMfaPasskeyAssertionResponse401
) & {
  headers: Headers;
};

export type finishMfaPasskeyAssertionResponse =
  | finishMfaPasskeyAssertionResponseSuccess
  | finishMfaPasskeyAssertionResponseError;

export const getFinishMfaPasskeyAssertionUrl = () => {
  return `/api/pact/gateway/v1/auth/mfa/passkey/finish`;
};

/**
 * @summary Finish a passkey-assertion MFA step-up
 */
export const finishMfaPasskeyAssertion = async (
  authFinishMfaPasskeyAssertionRequest: AuthFinishMfaPasskeyAssertionRequest,
  options?: RequestInit
): Promise<finishMfaPasskeyAssertionResponse> => {
  return customFetch<finishMfaPasskeyAssertionResponse>(
    getFinishMfaPasskeyAssertionUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(authFinishMfaPasskeyAssertionRequest),
    }
  );
};

export const getFinishMfaPasskeyAssertionMutationFetcher = (
  options?: SecondParameter<typeof customFetch>
) => {
  return (_: Key, { arg }: { arg: AuthFinishMfaPasskeyAssertionRequest }) => {
    return finishMfaPasskeyAssertion(arg, options);
  };
};

export const getFinishMfaPasskeyAssertionMutationKey = () =>
  [`/api/pact/gateway/v1/auth/mfa/passkey/finish`] as const;

export type regenerateRecoveryCodesResponse200 = {
  data: AuthRecoveryCodesResponse;
  status: 200;
};

export type regenerateRecoveryCodesResponse401 = {
  data: string;
  status: 401;
};

export type regenerateRecoveryCodesResponseSuccess =
  regenerateRecoveryCodesResponse200 & {
    headers: Headers;
  };

export type regenerateRecoveryCodesResponseError =
  regenerateRecoveryCodesResponse401 & {
    headers: Headers;
  };

export type regenerateRecoveryCodesResponse =
  regenerateRecoveryCodesResponseSuccess | regenerateRecoveryCodesResponseError;

export const getRegenerateRecoveryCodesUrl = () => {
  return `/api/pact/gateway/v1/auth/mfa/recovery-codes`;
};

/**
 * @summary Regenerate MFA recovery codes
 */
export const regenerateRecoveryCodes = async (
  options?: RequestInit
): Promise<regenerateRecoveryCodesResponse> => {
  return customFetch<regenerateRecoveryCodesResponse>(
    getRegenerateRecoveryCodesUrl(),
    {
      ...options,
      method: 'POST',
    }
  );
};

export const getRegenerateRecoveryCodesMutationFetcher = (
  options?: SecondParameter<typeof customFetch>
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return regenerateRecoveryCodes(options);
  };
};

export const getRegenerateRecoveryCodesMutationKey = () =>
  [`/api/pact/gateway/v1/auth/mfa/recovery-codes`] as const;

export type verifyMfaResponse200 = {
  data: AuthSessionResponse;
  status: 200;
};

export type verifyMfaResponse400 = {
  data: BoundaryErrorResponse;
  status: 400;
};

export type verifyMfaResponse401 = {
  data: BoundaryErrorResponse;
  status: 401;
};

export type verifyMfaResponseSuccess = verifyMfaResponse200 & {
  headers: Headers;
};

export type verifyMfaResponseError = (
  verifyMfaResponse400 | verifyMfaResponse401
) & {
  headers: Headers;
};

export type verifyMfaResponse =
  verifyMfaResponseSuccess | verifyMfaResponseError;

export const getVerifyMfaUrl = () => {
  return `/api/pact/gateway/v1/auth/mfa/verify`;
};

/**
 * @summary Complete a partial-auth login with an MFA code
 */
export const verifyMfa = async (
  authVerifyMfaRequest: AuthVerifyMfaRequest,
  options?: RequestInit
): Promise<verifyMfaResponse> => {
  return customFetch<verifyMfaResponse>(getVerifyMfaUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(authVerifyMfaRequest),
  });
};

export const getVerifyMfaMutationFetcher = (
  options?: SecondParameter<typeof customFetch>
) => {
  return (_: Key, { arg }: { arg: AuthVerifyMfaRequest }) => {
    return verifyMfa(arg, options);
  };
};

export const getVerifyMfaMutationKey = () =>
  [`/api/pact/gateway/v1/auth/mfa/verify`] as const;

export type handleOAuthCallbackResponse200 = {
  data: AuthSessionResponse;
  status: 200;
};

export type handleOAuthCallbackResponse400 = {
  data: BoundaryErrorResponse;
  status: 400;
};

export type handleOAuthCallbackResponse401 = {
  data: BoundaryErrorResponse;
  status: 401;
};

export type handleOAuthCallbackResponseSuccess =
  handleOAuthCallbackResponse200 & {
    headers: Headers;
  };

export type handleOAuthCallbackResponseError = (
  handleOAuthCallbackResponse400 | handleOAuthCallbackResponse401
) & {
  headers: Headers;
};

export type handleOAuthCallbackResponse =
  handleOAuthCallbackResponseSuccess | handleOAuthCallbackResponseError;

export const getHandleOAuthCallbackUrl = (provider: string) => {
  return `/api/pact/gateway/v1/auth/oauth/callback/${provider}`;
};

/**
 * @summary Complete a federated OAuth login
 */
export const handleOAuthCallback = async (
  provider: string,
  authHandleCallbackRequest: AuthHandleCallbackRequest,
  options?: RequestInit
): Promise<handleOAuthCallbackResponse> => {
  return customFetch<handleOAuthCallbackResponse>(
    getHandleOAuthCallbackUrl(provider),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(authHandleCallbackRequest),
    }
  );
};

export const getHandleOAuthCallbackMutationFetcher = (
  provider: string,
  options?: SecondParameter<typeof customFetch>
) => {
  return (_: Key, { arg }: { arg: AuthHandleCallbackRequest }) => {
    return handleOAuthCallback(provider, arg, options);
  };
};

export const getHandleOAuthCallbackMutationKey = (provider: string) =>
  [`/api/pact/gateway/v1/auth/oauth/callback/${provider}`] as const;

export type startOAuthLoginResponse200 = {
  data: AuthStartLoginResponse;
  status: 200;
};

export type startOAuthLoginResponse400 = {
  data: string;
  status: 400;
};

export type startOAuthLoginResponseSuccess = startOAuthLoginResponse200 & {
  headers: Headers;
};

export type startOAuthLoginResponseError = startOAuthLoginResponse400 & {
  headers: Headers;
};

export type startOAuthLoginResponse =
  startOAuthLoginResponseSuccess | startOAuthLoginResponseError;

export const getStartOAuthLoginUrl = (params: StartOAuthLoginParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/pact/gateway/v1/auth/oauth/start?${stringifiedParams}`
    : `/api/pact/gateway/v1/auth/oauth/start`;
};

/**
 * @summary Start a federated OAuth login
 */
export const startOAuthLogin = async (
  params: StartOAuthLoginParams,
  options?: RequestInit
): Promise<startOAuthLoginResponse> => {
  return customFetch<startOAuthLoginResponse>(getStartOAuthLoginUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getStartOAuthLoginKey = (params: StartOAuthLoginParams) =>
  [
    `/api/pact/gateway/v1/auth/oauth/start`,
    ...(params ? [params] : []),
  ] as const;

export type listPasskeysResponse200 = {
  data: AuthListPasskeysResponse;
  status: 200;
};

export type listPasskeysResponse401 = {
  data: string;
  status: 401;
};

export type listPasskeysResponseSuccess = listPasskeysResponse200 & {
  headers: Headers;
};

export type listPasskeysResponseError = listPasskeysResponse401 & {
  headers: Headers;
};

export type listPasskeysResponse =
  listPasskeysResponseSuccess | listPasskeysResponseError;

export const getListPasskeysUrl = () => {
  return `/api/pact/gateway/v1/auth/passkeys`;
};

/**
 * @summary List the signed-in user's passkeys
 */
export const listPasskeys = async (
  options?: RequestInit
): Promise<listPasskeysResponse> => {
  return customFetch<listPasskeysResponse>(getListPasskeysUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getListPasskeysKey = () =>
  [`/api/pact/gateway/v1/auth/passkeys`] as const;

export type deletePasskeyResponse204 = {
  data: void;
  status: 204;
};

export type deletePasskeyResponse401 = {
  data: string;
  status: 401;
};

export type deletePasskeyResponse404 = {
  data: BoundaryErrorResponse;
  status: 404;
};

export type deletePasskeyResponseSuccess = deletePasskeyResponse204 & {
  headers: Headers;
};

export type deletePasskeyResponseError = (
  deletePasskeyResponse401 | deletePasskeyResponse404
) & {
  headers: Headers;
};

export type deletePasskeyResponse =
  deletePasskeyResponseSuccess | deletePasskeyResponseError;

export const getDeletePasskeyUrl = (passkeyId: string) => {
  return `/api/pact/gateway/v1/auth/passkeys/${passkeyId}`;
};

/**
 * @summary Delete a passkey
 */
export const deletePasskey = async (
  passkeyId: string,
  options?: RequestInit
): Promise<deletePasskeyResponse> => {
  return customFetch<deletePasskeyResponse>(getDeletePasskeyUrl(passkeyId), {
    ...options,
    method: 'DELETE',
  });
};

export const getDeletePasskeyMutationFetcher = (
  passkeyId: string,
  options?: SecondParameter<typeof customFetch>
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deletePasskey(passkeyId, options);
  };
};

export const getDeletePasskeyMutationKey = (passkeyId: string) =>
  [`/api/pact/gateway/v1/auth/passkeys/${passkeyId}`] as const;

export type renamePasskeyResponse204 = {
  data: void;
  status: 204;
};

export type renamePasskeyResponse400 = {
  data: BoundaryErrorResponse;
  status: 400;
};

export type renamePasskeyResponse401 = {
  data: string;
  status: 401;
};

export type renamePasskeyResponse404 = {
  data: BoundaryErrorResponse;
  status: 404;
};

export type renamePasskeyResponseSuccess = renamePasskeyResponse204 & {
  headers: Headers;
};

export type renamePasskeyResponseError = (
  renamePasskeyResponse400 | renamePasskeyResponse401 | renamePasskeyResponse404
) & {
  headers: Headers;
};

export type renamePasskeyResponse =
  renamePasskeyResponseSuccess | renamePasskeyResponseError;

export const getRenamePasskeyUrl = (passkeyId: string) => {
  return `/api/pact/gateway/v1/auth/passkeys/${passkeyId}`;
};

/**
 * @summary Rename a passkey
 */
export const renamePasskey = async (
  passkeyId: string,
  authRenamePasskeyRequest: AuthRenamePasskeyRequest,
  options?: RequestInit
): Promise<renamePasskeyResponse> => {
  return customFetch<renamePasskeyResponse>(getRenamePasskeyUrl(passkeyId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(authRenamePasskeyRequest),
  });
};

export const getRenamePasskeyMutationFetcher = (
  passkeyId: string,
  options?: SecondParameter<typeof customFetch>
) => {
  return (_: Key, { arg }: { arg: AuthRenamePasskeyRequest }) => {
    return renamePasskey(passkeyId, arg, options);
  };
};

export const getRenamePasskeyMutationKey = (passkeyId: string) =>
  [`/api/pact/gateway/v1/auth/passkeys/${passkeyId}`] as const;

export type beginPasskeyLoginResponse200 = {
  data: AuthPasskeyCeremonyResponse;
  status: 200;
};

export type beginPasskeyLoginResponse400 = {
  data: BoundaryErrorResponse;
  status: 400;
};

export type beginPasskeyLoginResponseSuccess = beginPasskeyLoginResponse200 & {
  headers: Headers;
};

export type beginPasskeyLoginResponseError = beginPasskeyLoginResponse400 & {
  headers: Headers;
};

export type beginPasskeyLoginResponse =
  beginPasskeyLoginResponseSuccess | beginPasskeyLoginResponseError;

export const getBeginPasskeyLoginUrl = () => {
  return `/api/pact/gateway/v1/auth/passkeys/login/begin`;
};

/**
 * @summary Begin a passkey login
 */
export const beginPasskeyLogin = async (
  authBeginPasskeyLoginRequest: AuthBeginPasskeyLoginRequest,
  options?: RequestInit
): Promise<beginPasskeyLoginResponse> => {
  return customFetch<beginPasskeyLoginResponse>(getBeginPasskeyLoginUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(authBeginPasskeyLoginRequest),
  });
};

export const getBeginPasskeyLoginMutationFetcher = (
  options?: SecondParameter<typeof customFetch>
) => {
  return (_: Key, { arg }: { arg: AuthBeginPasskeyLoginRequest }) => {
    return beginPasskeyLogin(arg, options);
  };
};

export const getBeginPasskeyLoginMutationKey = () =>
  [`/api/pact/gateway/v1/auth/passkeys/login/begin`] as const;

export type finishPasskeyLoginResponse200 = {
  data: AuthSessionResponse;
  status: 200;
};

export type finishPasskeyLoginResponse400 = {
  data: BoundaryErrorResponse;
  status: 400;
};

export type finishPasskeyLoginResponse401 = {
  data: BoundaryErrorResponse;
  status: 401;
};

export type finishPasskeyLoginResponseSuccess =
  finishPasskeyLoginResponse200 & {
    headers: Headers;
  };

export type finishPasskeyLoginResponseError = (
  finishPasskeyLoginResponse400 | finishPasskeyLoginResponse401
) & {
  headers: Headers;
};

export type finishPasskeyLoginResponse =
  finishPasskeyLoginResponseSuccess | finishPasskeyLoginResponseError;

export const getFinishPasskeyLoginUrl = () => {
  return `/api/pact/gateway/v1/auth/passkeys/login/finish`;
};

/**
 * @summary Finish a passkey login
 */
export const finishPasskeyLogin = async (
  authFinishPasskeyLoginRequest: AuthFinishPasskeyLoginRequest,
  options?: RequestInit
): Promise<finishPasskeyLoginResponse> => {
  return customFetch<finishPasskeyLoginResponse>(getFinishPasskeyLoginUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(authFinishPasskeyLoginRequest),
  });
};

export const getFinishPasskeyLoginMutationFetcher = (
  options?: SecondParameter<typeof customFetch>
) => {
  return (_: Key, { arg }: { arg: AuthFinishPasskeyLoginRequest }) => {
    return finishPasskeyLogin(arg, options);
  };
};

export const getFinishPasskeyLoginMutationKey = () =>
  [`/api/pact/gateway/v1/auth/passkeys/login/finish`] as const;

export type beginPasskeyRegistrationResponse200 = {
  data: AuthPasskeyCeremonyResponse;
  status: 200;
};

export type beginPasskeyRegistrationResponse400 = {
  data: BoundaryErrorResponse;
  status: 400;
};

export type beginPasskeyRegistrationResponse401 = {
  data: string;
  status: 401;
};

export type beginPasskeyRegistrationResponseSuccess =
  beginPasskeyRegistrationResponse200 & {
    headers: Headers;
  };

export type beginPasskeyRegistrationResponseError = (
  beginPasskeyRegistrationResponse400 | beginPasskeyRegistrationResponse401
) & {
  headers: Headers;
};

export type beginPasskeyRegistrationResponse =
  | beginPasskeyRegistrationResponseSuccess
  | beginPasskeyRegistrationResponseError;

export const getBeginPasskeyRegistrationUrl = () => {
  return `/api/pact/gateway/v1/auth/passkeys/register/begin`;
};

/**
 * @summary Begin passkey registration
 */
export const beginPasskeyRegistration = async (
  authBeginPasskeyRegistrationRequest: AuthBeginPasskeyRegistrationRequest,
  options?: RequestInit
): Promise<beginPasskeyRegistrationResponse> => {
  return customFetch<beginPasskeyRegistrationResponse>(
    getBeginPasskeyRegistrationUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(authBeginPasskeyRegistrationRequest),
    }
  );
};

export const getBeginPasskeyRegistrationMutationFetcher = (
  options?: SecondParameter<typeof customFetch>
) => {
  return (_: Key, { arg }: { arg: AuthBeginPasskeyRegistrationRequest }) => {
    return beginPasskeyRegistration(arg, options);
  };
};

export const getBeginPasskeyRegistrationMutationKey = () =>
  [`/api/pact/gateway/v1/auth/passkeys/register/begin`] as const;

export type finishPasskeyRegistrationResponse200 = {
  data: AuthFinishPasskeyRegistrationResponse;
  status: 200;
};

export type finishPasskeyRegistrationResponse400 = {
  data: BoundaryErrorResponse;
  status: 400;
};

export type finishPasskeyRegistrationResponse401 = {
  data: string;
  status: 401;
};

export type finishPasskeyRegistrationResponseSuccess =
  finishPasskeyRegistrationResponse200 & {
    headers: Headers;
  };

export type finishPasskeyRegistrationResponseError = (
  finishPasskeyRegistrationResponse400 | finishPasskeyRegistrationResponse401
) & {
  headers: Headers;
};

export type finishPasskeyRegistrationResponse =
  | finishPasskeyRegistrationResponseSuccess
  | finishPasskeyRegistrationResponseError;

export const getFinishPasskeyRegistrationUrl = () => {
  return `/api/pact/gateway/v1/auth/passkeys/register/finish`;
};

/**
 * @summary Finish passkey registration
 */
export const finishPasskeyRegistration = async (
  authFinishPasskeyRegistrationRequest: AuthFinishPasskeyRegistrationRequest,
  options?: RequestInit
): Promise<finishPasskeyRegistrationResponse> => {
  return customFetch<finishPasskeyRegistrationResponse>(
    getFinishPasskeyRegistrationUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(authFinishPasskeyRegistrationRequest),
    }
  );
};

export const getFinishPasskeyRegistrationMutationFetcher = (
  options?: SecondParameter<typeof customFetch>
) => {
  return (_: Key, { arg }: { arg: AuthFinishPasskeyRegistrationRequest }) => {
    return finishPasskeyRegistration(arg, options);
  };
};

export const getFinishPasskeyRegistrationMutationKey = () =>
  [`/api/pact/gateway/v1/auth/passkeys/register/finish`] as const;

export type confirmPasswordResetResponse200 = {
  data: AuthSessionResponse;
  status: 200;
};

export type confirmPasswordResetResponse400 = {
  data: BoundaryErrorResponse;
  status: 400;
};

export type confirmPasswordResetResponse401 = {
  data: BoundaryErrorResponse;
  status: 401;
};

export type confirmPasswordResetResponseSuccess =
  confirmPasswordResetResponse200 & {
    headers: Headers;
  };

export type confirmPasswordResetResponseError = (
  confirmPasswordResetResponse400 | confirmPasswordResetResponse401
) & {
  headers: Headers;
};

export type confirmPasswordResetResponse =
  confirmPasswordResetResponseSuccess | confirmPasswordResetResponseError;

export const getConfirmPasswordResetUrl = () => {
  return `/api/pact/gateway/v1/auth/password-reset/confirm`;
};

/**
 * @summary Confirm a password reset with the emailed token
 */
export const confirmPasswordReset = async (
  authConfirmPasswordResetRequest: AuthConfirmPasswordResetRequest,
  options?: RequestInit
): Promise<confirmPasswordResetResponse> => {
  return customFetch<confirmPasswordResetResponse>(
    getConfirmPasswordResetUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(authConfirmPasswordResetRequest),
    }
  );
};

export const getConfirmPasswordResetMutationFetcher = (
  options?: SecondParameter<typeof customFetch>
) => {
  return (_: Key, { arg }: { arg: AuthConfirmPasswordResetRequest }) => {
    return confirmPasswordReset(arg, options);
  };
};

export const getConfirmPasswordResetMutationKey = () =>
  [`/api/pact/gateway/v1/auth/password-reset/confirm`] as const;

export type requestPasswordResetResponse202 = {
  data: void;
  status: 202;
};

export type requestPasswordResetResponse400 = {
  data: BoundaryErrorResponse;
  status: 400;
};

export type requestPasswordResetResponseSuccess =
  requestPasswordResetResponse202 & {
    headers: Headers;
  };

export type requestPasswordResetResponseError =
  requestPasswordResetResponse400 & {
    headers: Headers;
  };

export type requestPasswordResetResponse =
  requestPasswordResetResponseSuccess | requestPasswordResetResponseError;

export const getRequestPasswordResetUrl = () => {
  return `/api/pact/gateway/v1/auth/password-reset/request`;
};

/**
 * @summary Request a password-reset email
 */
export const requestPasswordReset = async (
  authRequestPasswordResetRequest: AuthRequestPasswordResetRequest,
  options?: RequestInit
): Promise<requestPasswordResetResponse> => {
  return customFetch<requestPasswordResetResponse>(
    getRequestPasswordResetUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(authRequestPasswordResetRequest),
    }
  );
};

export const getRequestPasswordResetMutationFetcher = (
  options?: SecondParameter<typeof customFetch>
) => {
  return (_: Key, { arg }: { arg: AuthRequestPasswordResetRequest }) => {
    return requestPasswordReset(arg, options);
  };
};

export const getRequestPasswordResetMutationKey = () =>
  [`/api/pact/gateway/v1/auth/password-reset/request`] as const;

export type registerAccountResponse201 = {
  data: void;
  status: 201;
};

export type registerAccountResponse400 = {
  data: BoundaryErrorResponse;
  status: 400;
};

export type registerAccountResponse409 = {
  data: BoundaryErrorResponse;
  status: 409;
};

export type registerAccountResponseSuccess = registerAccountResponse201 & {
  headers: Headers;
};

export type registerAccountResponseError = (
  registerAccountResponse400 | registerAccountResponse409
) & {
  headers: Headers;
};

export type registerAccountResponse =
  registerAccountResponseSuccess | registerAccountResponseError;

export const getRegisterAccountUrl = () => {
  return `/api/pact/gateway/v1/auth/register`;
};

/**
 * @summary Register a new account
 */
export const registerAccount = async (
  authRegisterRequest: AuthRegisterRequest,
  options?: RequestInit
): Promise<registerAccountResponse> => {
  return customFetch<registerAccountResponse>(getRegisterAccountUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(authRegisterRequest),
  });
};

export const getRegisterAccountMutationFetcher = (
  options?: SecondParameter<typeof customFetch>
) => {
  return (_: Key, { arg }: { arg: AuthRegisterRequest }) => {
    return registerAccount(arg, options);
  };
};

export const getRegisterAccountMutationKey = () =>
  [`/api/pact/gateway/v1/auth/register`] as const;

export type getSessionResponse200 = {
  data: AuthSessionIntrospectionResponse;
  status: 200;
};

export type getSessionResponse401 = {
  data: string;
  status: 401;
};

export type getSessionResponseSuccess = getSessionResponse200 & {
  headers: Headers;
};

export type getSessionResponseError = getSessionResponse401 & {
  headers: Headers;
};

export type getSessionResponse =
  getSessionResponseSuccess | getSessionResponseError;

export const getGetSessionUrl = () => {
  return `/api/pact/gateway/v1/auth/session`;
};

/**
 * @summary Introspect the bearer token's session
 */
export const getSession = async (
  options?: RequestInit
): Promise<getSessionResponse> => {
  return customFetch<getSessionResponse>(getGetSessionUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getGetSessionKey = () =>
  [`/api/pact/gateway/v1/auth/session`] as const;

export type refreshSessionResponse200 = {
  data: AuthSessionResponse;
  status: 200;
};

export type refreshSessionResponse400 = {
  data: BoundaryErrorResponse;
  status: 400;
};

export type refreshSessionResponse401 = {
  data: string;
  status: 401;
};

export type refreshSessionResponseSuccess = refreshSessionResponse200 & {
  headers: Headers;
};

export type refreshSessionResponseError = (
  refreshSessionResponse400 | refreshSessionResponse401
) & {
  headers: Headers;
};

export type refreshSessionResponse =
  refreshSessionResponseSuccess | refreshSessionResponseError;

export const getRefreshSessionUrl = () => {
  return `/api/pact/gateway/v1/auth/session/refresh`;
};

/**
 * @summary Redeem a refresh token for a new session
 */
export const refreshSession = async (
  authRefreshSessionRequest?: AuthRefreshSessionRequest,
  options?: RequestInit
): Promise<refreshSessionResponse> => {
  return customFetch<refreshSessionResponse>(getRefreshSessionUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(authRefreshSessionRequest),
  });
};

export const getRefreshSessionMutationFetcher = (
  options?: SecondParameter<typeof customFetch>
) => {
  return (_: Key, { arg }: { arg: AuthRefreshSessionRequest | undefined }) => {
    return refreshSession(arg, options);
  };
};

export const getRefreshSessionMutationKey = () =>
  [`/api/pact/gateway/v1/auth/session/refresh`] as const;

export type beginTOTPEnrollmentResponse200 = {
  data: AuthBeginTOTPEnrollmentResponse;
  status: 200;
};

export type beginTOTPEnrollmentResponse401 = {
  data: string;
  status: 401;
};

export type beginTOTPEnrollmentResponseSuccess =
  beginTOTPEnrollmentResponse200 & {
    headers: Headers;
  };

export type beginTOTPEnrollmentResponseError =
  beginTOTPEnrollmentResponse401 & {
    headers: Headers;
  };

export type beginTOTPEnrollmentResponse =
  beginTOTPEnrollmentResponseSuccess | beginTOTPEnrollmentResponseError;

export const getBeginTOTPEnrollmentUrl = () => {
  return `/api/pact/gateway/v1/auth/totp/enroll/begin`;
};

/**
 * @summary Begin TOTP enrollment
 */
export const beginTOTPEnrollment = async (
  options?: RequestInit
): Promise<beginTOTPEnrollmentResponse> => {
  return customFetch<beginTOTPEnrollmentResponse>(getBeginTOTPEnrollmentUrl(), {
    ...options,
    method: 'POST',
  });
};

export const getBeginTOTPEnrollmentMutationFetcher = (
  options?: SecondParameter<typeof customFetch>
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return beginTOTPEnrollment(options);
  };
};

export const getBeginTOTPEnrollmentMutationKey = () =>
  [`/api/pact/gateway/v1/auth/totp/enroll/begin`] as const;

export type confirmTOTPEnrollmentResponse200 = {
  data: AuthRecoveryCodesResponse;
  status: 200;
};

export type confirmTOTPEnrollmentResponse400 = {
  data: BoundaryErrorResponse;
  status: 400;
};

export type confirmTOTPEnrollmentResponse401 = {
  data: string;
  status: 401;
};

export type confirmTOTPEnrollmentResponseSuccess =
  confirmTOTPEnrollmentResponse200 & {
    headers: Headers;
  };

export type confirmTOTPEnrollmentResponseError = (
  confirmTOTPEnrollmentResponse400 | confirmTOTPEnrollmentResponse401
) & {
  headers: Headers;
};

export type confirmTOTPEnrollmentResponse =
  confirmTOTPEnrollmentResponseSuccess | confirmTOTPEnrollmentResponseError;

export const getConfirmTOTPEnrollmentUrl = () => {
  return `/api/pact/gateway/v1/auth/totp/enroll/confirm`;
};

/**
 * @summary Confirm TOTP enrollment with a generated code
 */
export const confirmTOTPEnrollment = async (
  authConfirmTOTPEnrollmentRequest: AuthConfirmTOTPEnrollmentRequest,
  options?: RequestInit
): Promise<confirmTOTPEnrollmentResponse> => {
  return customFetch<confirmTOTPEnrollmentResponse>(
    getConfirmTOTPEnrollmentUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(authConfirmTOTPEnrollmentRequest),
    }
  );
};

export const getConfirmTOTPEnrollmentMutationFetcher = (
  options?: SecondParameter<typeof customFetch>
) => {
  return (_: Key, { arg }: { arg: AuthConfirmTOTPEnrollmentRequest }) => {
    return confirmTOTPEnrollment(arg, options);
  };
};

export const getConfirmTOTPEnrollmentMutationKey = () =>
  [`/api/pact/gateway/v1/auth/totp/enroll/confirm`] as const;

export type verifyEmailResponse200 = {
  data: AuthSessionResponse;
  status: 200;
};

export type verifyEmailResponse400 = {
  data: BoundaryErrorResponse;
  status: 400;
};

export type verifyEmailResponse401 = {
  data: BoundaryErrorResponse;
  status: 401;
};

export type verifyEmailResponseSuccess = verifyEmailResponse200 & {
  headers: Headers;
};

export type verifyEmailResponseError = (
  verifyEmailResponse400 | verifyEmailResponse401
) & {
  headers: Headers;
};

export type verifyEmailResponse =
  verifyEmailResponseSuccess | verifyEmailResponseError;

export const getVerifyEmailUrl = () => {
  return `/api/pact/gateway/v1/auth/verify-email`;
};

/**
 * @summary Verify an account email with the emailed token
 */
export const verifyEmail = async (
  authVerifyEmailRequest: AuthVerifyEmailRequest,
  options?: RequestInit
): Promise<verifyEmailResponse> => {
  return customFetch<verifyEmailResponse>(getVerifyEmailUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(authVerifyEmailRequest),
  });
};

export const getVerifyEmailMutationFetcher = (
  options?: SecondParameter<typeof customFetch>
) => {
  return (_: Key, { arg }: { arg: AuthVerifyEmailRequest }) => {
    return verifyEmail(arg, options);
  };
};

export const getVerifyEmailMutationKey = () =>
  [`/api/pact/gateway/v1/auth/verify-email`] as const;

export type resendVerificationResponse202 = {
  data: void;
  status: 202;
};

export type resendVerificationResponse400 = {
  data: BoundaryErrorResponse;
  status: 400;
};

export type resendVerificationResponseSuccess =
  resendVerificationResponse202 & {
    headers: Headers;
  };

export type resendVerificationResponseError = resendVerificationResponse400 & {
  headers: Headers;
};

export type resendVerificationResponse =
  resendVerificationResponseSuccess | resendVerificationResponseError;

export const getResendVerificationUrl = () => {
  return `/api/pact/gateway/v1/auth/verify-email/resend`;
};

/**
 * @summary Resend the account verification email
 */
export const resendVerification = async (
  authResendVerificationRequest: AuthResendVerificationRequest,
  options?: RequestInit
): Promise<resendVerificationResponse> => {
  return customFetch<resendVerificationResponse>(getResendVerificationUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(authResendVerificationRequest),
  });
};

export const getResendVerificationMutationFetcher = (
  options?: SecondParameter<typeof customFetch>
) => {
  return (_: Key, { arg }: { arg: AuthResendVerificationRequest }) => {
    return resendVerification(arg, options);
  };
};

export const getResendVerificationMutationKey = () =>
  [`/api/pact/gateway/v1/auth/verify-email/resend`] as const;
