'use client';

/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr';
import useSWRMutation from 'swr/mutation';
import type { Arguments, Key, SWRConfiguration } from 'swr';
import type { SWRMutationConfiguration } from 'swr/mutation';

import type {
  AuthBeginMfaPasskeyAssertionRequest,
  AuthBeginPasskeyLoginRequest,
  AuthBeginPasskeyRegistrationRequest,
  AuthBeginTOTPEnrollmentResponse,
  AuthConfirmPasswordResetRequest,
  AuthConfirmTOTPEnrollmentRequest,
  AuthFinishMfaPasskeyAssertionRequest,
  AuthFinishPasskeyLoginRequest,
  AuthFinishPasskeyRegistrationRequest,
  AuthFinishPasskeyRegistrationResponse,
  AuthHandleCallbackRequest,
  AuthListIdentitiesResponse,
  AuthListMfaFactorsResponse,
  AuthListPasskeysResponse,
  AuthLoginRequest,
  AuthPasskeyCeremonyResponse,
  AuthRecoveryCodesResponse,
  AuthRefreshSessionRequest,
  AuthRegisterRequest,
  AuthRenamePasskeyRequest,
  AuthRequestPasswordResetRequest,
  AuthResendVerificationRequest,
  AuthSessionIntrospectionResponse,
  AuthSessionResponse,
  AuthStartLoginResponse,
  AuthVerifyEmailRequest,
  AuthVerifyMfaRequest,
  BoundaryErrorResponse,
  StartOAuthLoginParams,
} from './types';

import {
  listIdentitiesResponse200,
  listIdentitiesResponse401,
  listIdentitiesResponseSuccess,
  listIdentitiesResponseError,
  getListIdentitiesUrl,
  listIdentitiesResponse,
  listIdentities,
  getListIdentitiesKey,
  unlinkIdentityResponse204,
  unlinkIdentityResponse401,
  unlinkIdentityResponse404,
  unlinkIdentityResponseSuccess,
  unlinkIdentityResponseError,
  getUnlinkIdentityUrl,
  unlinkIdentityResponse,
  unlinkIdentity,
  getUnlinkIdentityMutationFetcher,
  getUnlinkIdentityMutationKey,
  loginResponse200,
  loginResponse400,
  loginResponse401,
  loginResponseSuccess,
  loginResponseError,
  getLoginUrl,
  loginResponse,
  login,
  getLoginMutationFetcher,
  getLoginMutationKey,
  logoutResponse204,
  logoutResponse401,
  logoutResponseSuccess,
  logoutResponseError,
  getLogoutUrl,
  logoutResponse,
  logout,
  getLogoutMutationFetcher,
  getLogoutMutationKey,
  listMfaFactorsResponse200,
  listMfaFactorsResponse401,
  listMfaFactorsResponseSuccess,
  listMfaFactorsResponseError,
  getListMfaFactorsUrl,
  listMfaFactorsResponse,
  listMfaFactors,
  getListMfaFactorsKey,
  revokeMfaFactorResponse204,
  revokeMfaFactorResponse401,
  revokeMfaFactorResponse404,
  revokeMfaFactorResponseSuccess,
  revokeMfaFactorResponseError,
  getRevokeMfaFactorUrl,
  revokeMfaFactorResponse,
  revokeMfaFactor,
  getRevokeMfaFactorMutationFetcher,
  getRevokeMfaFactorMutationKey,
  beginMfaPasskeyAssertionResponse200,
  beginMfaPasskeyAssertionResponse400,
  beginMfaPasskeyAssertionResponse401,
  beginMfaPasskeyAssertionResponseSuccess,
  beginMfaPasskeyAssertionResponseError,
  getBeginMfaPasskeyAssertionUrl,
  beginMfaPasskeyAssertionResponse,
  beginMfaPasskeyAssertion,
  getBeginMfaPasskeyAssertionMutationFetcher,
  getBeginMfaPasskeyAssertionMutationKey,
  finishMfaPasskeyAssertionResponse200,
  finishMfaPasskeyAssertionResponse400,
  finishMfaPasskeyAssertionResponse401,
  finishMfaPasskeyAssertionResponseSuccess,
  finishMfaPasskeyAssertionResponseError,
  getFinishMfaPasskeyAssertionUrl,
  finishMfaPasskeyAssertionResponse,
  finishMfaPasskeyAssertion,
  getFinishMfaPasskeyAssertionMutationFetcher,
  getFinishMfaPasskeyAssertionMutationKey,
  regenerateRecoveryCodesResponse200,
  regenerateRecoveryCodesResponse401,
  regenerateRecoveryCodesResponseSuccess,
  regenerateRecoveryCodesResponseError,
  getRegenerateRecoveryCodesUrl,
  regenerateRecoveryCodesResponse,
  regenerateRecoveryCodes,
  getRegenerateRecoveryCodesMutationFetcher,
  getRegenerateRecoveryCodesMutationKey,
  verifyMfaResponse200,
  verifyMfaResponse400,
  verifyMfaResponse401,
  verifyMfaResponseSuccess,
  verifyMfaResponseError,
  getVerifyMfaUrl,
  verifyMfaResponse,
  verifyMfa,
  getVerifyMfaMutationFetcher,
  getVerifyMfaMutationKey,
  handleOAuthCallbackResponse200,
  handleOAuthCallbackResponse400,
  handleOAuthCallbackResponse401,
  handleOAuthCallbackResponseSuccess,
  handleOAuthCallbackResponseError,
  getHandleOAuthCallbackUrl,
  handleOAuthCallbackResponse,
  handleOAuthCallback,
  getHandleOAuthCallbackMutationFetcher,
  getHandleOAuthCallbackMutationKey,
  startOAuthLoginResponse200,
  startOAuthLoginResponse400,
  startOAuthLoginResponseSuccess,
  startOAuthLoginResponseError,
  getStartOAuthLoginUrl,
  startOAuthLoginResponse,
  startOAuthLogin,
  getStartOAuthLoginKey,
  listPasskeysResponse200,
  listPasskeysResponse401,
  listPasskeysResponseSuccess,
  listPasskeysResponseError,
  getListPasskeysUrl,
  listPasskeysResponse,
  listPasskeys,
  getListPasskeysKey,
  deletePasskeyResponse204,
  deletePasskeyResponse401,
  deletePasskeyResponse404,
  deletePasskeyResponseSuccess,
  deletePasskeyResponseError,
  getDeletePasskeyUrl,
  deletePasskeyResponse,
  deletePasskey,
  getDeletePasskeyMutationFetcher,
  getDeletePasskeyMutationKey,
  renamePasskeyResponse204,
  renamePasskeyResponse400,
  renamePasskeyResponse401,
  renamePasskeyResponse404,
  renamePasskeyResponseSuccess,
  renamePasskeyResponseError,
  getRenamePasskeyUrl,
  renamePasskeyResponse,
  renamePasskey,
  getRenamePasskeyMutationFetcher,
  getRenamePasskeyMutationKey,
  beginPasskeyLoginResponse200,
  beginPasskeyLoginResponse400,
  beginPasskeyLoginResponseSuccess,
  beginPasskeyLoginResponseError,
  getBeginPasskeyLoginUrl,
  beginPasskeyLoginResponse,
  beginPasskeyLogin,
  getBeginPasskeyLoginMutationFetcher,
  getBeginPasskeyLoginMutationKey,
  finishPasskeyLoginResponse200,
  finishPasskeyLoginResponse400,
  finishPasskeyLoginResponse401,
  finishPasskeyLoginResponseSuccess,
  finishPasskeyLoginResponseError,
  getFinishPasskeyLoginUrl,
  finishPasskeyLoginResponse,
  finishPasskeyLogin,
  getFinishPasskeyLoginMutationFetcher,
  getFinishPasskeyLoginMutationKey,
  beginPasskeyRegistrationResponse200,
  beginPasskeyRegistrationResponse400,
  beginPasskeyRegistrationResponse401,
  beginPasskeyRegistrationResponseSuccess,
  beginPasskeyRegistrationResponseError,
  getBeginPasskeyRegistrationUrl,
  beginPasskeyRegistrationResponse,
  beginPasskeyRegistration,
  getBeginPasskeyRegistrationMutationFetcher,
  getBeginPasskeyRegistrationMutationKey,
  finishPasskeyRegistrationResponse200,
  finishPasskeyRegistrationResponse400,
  finishPasskeyRegistrationResponse401,
  finishPasskeyRegistrationResponseSuccess,
  finishPasskeyRegistrationResponseError,
  getFinishPasskeyRegistrationUrl,
  finishPasskeyRegistrationResponse,
  finishPasskeyRegistration,
  getFinishPasskeyRegistrationMutationFetcher,
  getFinishPasskeyRegistrationMutationKey,
  confirmPasswordResetResponse200,
  confirmPasswordResetResponse400,
  confirmPasswordResetResponse401,
  confirmPasswordResetResponseSuccess,
  confirmPasswordResetResponseError,
  getConfirmPasswordResetUrl,
  confirmPasswordResetResponse,
  confirmPasswordReset,
  getConfirmPasswordResetMutationFetcher,
  getConfirmPasswordResetMutationKey,
  requestPasswordResetResponse202,
  requestPasswordResetResponse400,
  requestPasswordResetResponseSuccess,
  requestPasswordResetResponseError,
  getRequestPasswordResetUrl,
  requestPasswordResetResponse,
  requestPasswordReset,
  getRequestPasswordResetMutationFetcher,
  getRequestPasswordResetMutationKey,
  registerAccountResponse201,
  registerAccountResponse400,
  registerAccountResponse409,
  registerAccountResponseSuccess,
  registerAccountResponseError,
  getRegisterAccountUrl,
  registerAccountResponse,
  registerAccount,
  getRegisterAccountMutationFetcher,
  getRegisterAccountMutationKey,
  getSessionResponse200,
  getSessionResponse401,
  getSessionResponseSuccess,
  getSessionResponseError,
  getGetSessionUrl,
  getSessionResponse,
  getSession,
  getGetSessionKey,
  refreshSessionResponse200,
  refreshSessionResponse400,
  refreshSessionResponse401,
  refreshSessionResponseSuccess,
  refreshSessionResponseError,
  getRefreshSessionUrl,
  refreshSessionResponse,
  refreshSession,
  getRefreshSessionMutationFetcher,
  getRefreshSessionMutationKey,
  beginTOTPEnrollmentResponse200,
  beginTOTPEnrollmentResponse401,
  beginTOTPEnrollmentResponseSuccess,
  beginTOTPEnrollmentResponseError,
  getBeginTOTPEnrollmentUrl,
  beginTOTPEnrollmentResponse,
  beginTOTPEnrollment,
  getBeginTOTPEnrollmentMutationFetcher,
  getBeginTOTPEnrollmentMutationKey,
  confirmTOTPEnrollmentResponse200,
  confirmTOTPEnrollmentResponse400,
  confirmTOTPEnrollmentResponse401,
  confirmTOTPEnrollmentResponseSuccess,
  confirmTOTPEnrollmentResponseError,
  getConfirmTOTPEnrollmentUrl,
  confirmTOTPEnrollmentResponse,
  confirmTOTPEnrollment,
  getConfirmTOTPEnrollmentMutationFetcher,
  getConfirmTOTPEnrollmentMutationKey,
  verifyEmailResponse200,
  verifyEmailResponse400,
  verifyEmailResponse401,
  verifyEmailResponseSuccess,
  verifyEmailResponseError,
  getVerifyEmailUrl,
  verifyEmailResponse,
  verifyEmail,
  getVerifyEmailMutationFetcher,
  getVerifyEmailMutationKey,
  resendVerificationResponse202,
  resendVerificationResponse400,
  resendVerificationResponseSuccess,
  resendVerificationResponseError,
  getResendVerificationUrl,
  resendVerificationResponse,
  resendVerification,
  getResendVerificationMutationFetcher,
  getResendVerificationMutationKey,
} from './fetchers';

import { customFetch } from '../custom_fetch';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type ListIdentitiesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listIdentities>>
>;

/**
 * @summary List the signed-in user's linked OAuth identities
 */
export const useListIdentities = <TError = string>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof listIdentities>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getListIdentitiesKey() : null));
  const swrFn = () => listIdentities(requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions
  );

  return {
    swrKey,
    ...query,
  };
};

export type UnlinkIdentityMutationResult = NonNullable<
  Awaited<ReturnType<typeof unlinkIdentity>>
>;

/**
 * @summary Unlink a federated OAuth identity
 */
export const useUnlinkIdentity = <TError = string | BoundaryErrorResponse>(
  provider: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof unlinkIdentity>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof unlinkIdentity>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customFetch>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getUnlinkIdentityMutationKey(provider);
  const swrFn = getUnlinkIdentityMutationFetcher(provider, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type LoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof login>>
>;

/**
 * @summary Log in with email and password
 */
export const useLogin = <TError = string>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof login>>,
    TError,
    Key,
    AuthLoginRequest,
    Awaited<ReturnType<typeof login>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getLoginMutationKey();
  const swrFn = getLoginMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type LogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof logout>>
>;

/**
 * @summary Revoke the signed-in session
 */
export const useLogout = <TError = string>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof logout>>,
    TError,
    Key,
    Arguments,
    Awaited<ReturnType<typeof logout>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getLogoutMutationKey();
  const swrFn = getLogoutMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type ListMfaFactorsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listMfaFactors>>
>;

/**
 * @summary List the signed-in user's enrolled MFA factors
 */
export const useListMfaFactors = <TError = string>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof listMfaFactors>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getListMfaFactorsKey() : null));
  const swrFn = () => listMfaFactors(requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions
  );

  return {
    swrKey,
    ...query,
  };
};

export type RevokeMfaFactorMutationResult = NonNullable<
  Awaited<ReturnType<typeof revokeMfaFactor>>
>;

/**
 * @summary Revoke an enrolled MFA factor
 */
export const useRevokeMfaFactor = <TError = string | BoundaryErrorResponse>(
  factorId: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof revokeMfaFactor>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof revokeMfaFactor>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customFetch>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getRevokeMfaFactorMutationKey(factorId);
  const swrFn = getRevokeMfaFactorMutationFetcher(factorId, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type BeginMfaPasskeyAssertionMutationResult = NonNullable<
  Awaited<ReturnType<typeof beginMfaPasskeyAssertion>>
>;

/**
 * @summary Begin a passkey-assertion MFA step-up
 */
export const useBeginMfaPasskeyAssertion = <TError = string>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof beginMfaPasskeyAssertion>>,
    TError,
    Key,
    AuthBeginMfaPasskeyAssertionRequest,
    Awaited<ReturnType<typeof beginMfaPasskeyAssertion>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getBeginMfaPasskeyAssertionMutationKey();
  const swrFn = getBeginMfaPasskeyAssertionMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type FinishMfaPasskeyAssertionMutationResult = NonNullable<
  Awaited<ReturnType<typeof finishMfaPasskeyAssertion>>
>;

/**
 * @summary Finish a passkey-assertion MFA step-up
 */
export const useFinishMfaPasskeyAssertion = <TError = string>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof finishMfaPasskeyAssertion>>,
    TError,
    Key,
    AuthFinishMfaPasskeyAssertionRequest,
    Awaited<ReturnType<typeof finishMfaPasskeyAssertion>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey =
    swrOptions?.swrKey ?? getFinishMfaPasskeyAssertionMutationKey();
  const swrFn = getFinishMfaPasskeyAssertionMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type RegenerateRecoveryCodesMutationResult = NonNullable<
  Awaited<ReturnType<typeof regenerateRecoveryCodes>>
>;

/**
 * @summary Regenerate MFA recovery codes
 */
export const useRegenerateRecoveryCodes = <TError = string>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof regenerateRecoveryCodes>>,
    TError,
    Key,
    Arguments,
    Awaited<ReturnType<typeof regenerateRecoveryCodes>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getRegenerateRecoveryCodesMutationKey();
  const swrFn = getRegenerateRecoveryCodesMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type VerifyMfaMutationResult = NonNullable<
  Awaited<ReturnType<typeof verifyMfa>>
>;

/**
 * @summary Complete a partial-auth login with an MFA code
 */
export const useVerifyMfa = <TError = string>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof verifyMfa>>,
    TError,
    Key,
    AuthVerifyMfaRequest,
    Awaited<ReturnType<typeof verifyMfa>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getVerifyMfaMutationKey();
  const swrFn = getVerifyMfaMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type HandleOAuthCallbackMutationResult = NonNullable<
  Awaited<ReturnType<typeof handleOAuthCallback>>
>;

/**
 * @summary Complete a federated OAuth login
 */
export const useHandleOAuthCallback = <TError = string>(
  provider: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof handleOAuthCallback>>,
      TError,
      Key,
      AuthHandleCallbackRequest,
      Awaited<ReturnType<typeof handleOAuthCallback>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customFetch>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey =
    swrOptions?.swrKey ?? getHandleOAuthCallbackMutationKey(provider);
  const swrFn = getHandleOAuthCallbackMutationFetcher(provider, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type StartOAuthLoginQueryResult = NonNullable<
  Awaited<ReturnType<typeof startOAuthLogin>>
>;

/**
 * @summary Start a federated OAuth login
 */
export const useStartOAuthLogin = <TError = string>(
  params: StartOAuthLoginParams,
  options?: {
    swr?: SWRConfiguration<
      Awaited<ReturnType<typeof startOAuthLogin>>,
      TError
    > & { swrKey?: Key; enabled?: boolean };
    request?: SecondParameter<typeof customFetch>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getStartOAuthLoginKey(params) : null));
  const swrFn = () => startOAuthLogin(params, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions
  );

  return {
    swrKey,
    ...query,
  };
};

export type ListPasskeysQueryResult = NonNullable<
  Awaited<ReturnType<typeof listPasskeys>>
>;

/**
 * @summary List the signed-in user's passkeys
 */
export const useListPasskeys = <TError = string>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof listPasskeys>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getListPasskeysKey() : null));
  const swrFn = () => listPasskeys(requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions
  );

  return {
    swrKey,
    ...query,
  };
};

export type DeletePasskeyMutationResult = NonNullable<
  Awaited<ReturnType<typeof deletePasskey>>
>;

/**
 * @summary Delete a passkey
 */
export const useDeletePasskey = <TError = string | BoundaryErrorResponse>(
  passkeyId: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof deletePasskey>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof deletePasskey>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customFetch>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getDeletePasskeyMutationKey(passkeyId);
  const swrFn = getDeletePasskeyMutationFetcher(passkeyId, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type RenamePasskeyMutationResult = NonNullable<
  Awaited<ReturnType<typeof renamePasskey>>
>;

/**
 * @summary Rename a passkey
 */
export const useRenamePasskey = <TError = string | BoundaryErrorResponse>(
  passkeyId: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof renamePasskey>>,
      TError,
      Key,
      AuthRenamePasskeyRequest,
      Awaited<ReturnType<typeof renamePasskey>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customFetch>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getRenamePasskeyMutationKey(passkeyId);
  const swrFn = getRenamePasskeyMutationFetcher(passkeyId, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type BeginPasskeyLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof beginPasskeyLogin>>
>;

/**
 * @summary Begin a passkey login
 */
export const useBeginPasskeyLogin = <TError = string>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof beginPasskeyLogin>>,
    TError,
    Key,
    AuthBeginPasskeyLoginRequest,
    Awaited<ReturnType<typeof beginPasskeyLogin>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getBeginPasskeyLoginMutationKey();
  const swrFn = getBeginPasskeyLoginMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type FinishPasskeyLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof finishPasskeyLogin>>
>;

/**
 * @summary Finish a passkey login
 */
export const useFinishPasskeyLogin = <TError = string>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof finishPasskeyLogin>>,
    TError,
    Key,
    AuthFinishPasskeyLoginRequest,
    Awaited<ReturnType<typeof finishPasskeyLogin>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getFinishPasskeyLoginMutationKey();
  const swrFn = getFinishPasskeyLoginMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type BeginPasskeyRegistrationMutationResult = NonNullable<
  Awaited<ReturnType<typeof beginPasskeyRegistration>>
>;

/**
 * @summary Begin passkey registration
 */
export const useBeginPasskeyRegistration = <TError = string>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof beginPasskeyRegistration>>,
    TError,
    Key,
    AuthBeginPasskeyRegistrationRequest,
    Awaited<ReturnType<typeof beginPasskeyRegistration>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getBeginPasskeyRegistrationMutationKey();
  const swrFn = getBeginPasskeyRegistrationMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type FinishPasskeyRegistrationMutationResult = NonNullable<
  Awaited<ReturnType<typeof finishPasskeyRegistration>>
>;

/**
 * @summary Finish passkey registration
 */
export const useFinishPasskeyRegistration = <TError = string>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof finishPasskeyRegistration>>,
    TError,
    Key,
    AuthFinishPasskeyRegistrationRequest,
    Awaited<ReturnType<typeof finishPasskeyRegistration>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey =
    swrOptions?.swrKey ?? getFinishPasskeyRegistrationMutationKey();
  const swrFn = getFinishPasskeyRegistrationMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type ConfirmPasswordResetMutationResult = NonNullable<
  Awaited<ReturnType<typeof confirmPasswordReset>>
>;

/**
 * @summary Confirm a password reset with the emailed token
 */
export const useConfirmPasswordReset = <TError = string>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof confirmPasswordReset>>,
    TError,
    Key,
    AuthConfirmPasswordResetRequest,
    Awaited<ReturnType<typeof confirmPasswordReset>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getConfirmPasswordResetMutationKey();
  const swrFn = getConfirmPasswordResetMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type RequestPasswordResetMutationResult = NonNullable<
  Awaited<ReturnType<typeof requestPasswordReset>>
>;

/**
 * @summary Request a password-reset email
 */
export const useRequestPasswordReset = <TError = string>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof requestPasswordReset>>,
    TError,
    Key,
    AuthRequestPasswordResetRequest,
    Awaited<ReturnType<typeof requestPasswordReset>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getRequestPasswordResetMutationKey();
  const swrFn = getRequestPasswordResetMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type RegisterAccountMutationResult = NonNullable<
  Awaited<ReturnType<typeof registerAccount>>
>;

/**
 * @summary Register a new account
 */
export const useRegisterAccount = <
  TError = string | BoundaryErrorResponse,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof registerAccount>>,
    TError,
    Key,
    AuthRegisterRequest,
    Awaited<ReturnType<typeof registerAccount>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getRegisterAccountMutationKey();
  const swrFn = getRegisterAccountMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type GetSessionQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSession>>
>;

/**
 * @summary Introspect the bearer token's session
 */
export const useGetSession = <TError = string>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof getSession>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetSessionKey() : null));
  const swrFn = () => getSession(requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions
  );

  return {
    swrKey,
    ...query,
  };
};

export type RefreshSessionMutationResult = NonNullable<
  Awaited<ReturnType<typeof refreshSession>>
>;

/**
 * @summary Redeem a refresh token for a new session
 */
export const useRefreshSession = <TError = string>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof refreshSession>>,
    TError,
    Key,
    AuthRefreshSessionRequest | undefined,
    Awaited<ReturnType<typeof refreshSession>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getRefreshSessionMutationKey();
  const swrFn = getRefreshSessionMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type BeginTOTPEnrollmentMutationResult = NonNullable<
  Awaited<ReturnType<typeof beginTOTPEnrollment>>
>;

/**
 * @summary Begin TOTP enrollment
 */
export const useBeginTOTPEnrollment = <TError = string>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof beginTOTPEnrollment>>,
    TError,
    Key,
    Arguments,
    Awaited<ReturnType<typeof beginTOTPEnrollment>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getBeginTOTPEnrollmentMutationKey();
  const swrFn = getBeginTOTPEnrollmentMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type ConfirmTOTPEnrollmentMutationResult = NonNullable<
  Awaited<ReturnType<typeof confirmTOTPEnrollment>>
>;

/**
 * @summary Confirm TOTP enrollment with a generated code
 */
export const useConfirmTOTPEnrollment = <TError = string>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof confirmTOTPEnrollment>>,
    TError,
    Key,
    AuthConfirmTOTPEnrollmentRequest,
    Awaited<ReturnType<typeof confirmTOTPEnrollment>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getConfirmTOTPEnrollmentMutationKey();
  const swrFn = getConfirmTOTPEnrollmentMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type VerifyEmailMutationResult = NonNullable<
  Awaited<ReturnType<typeof verifyEmail>>
>;

/**
 * @summary Verify an account email with the emailed token
 */
export const useVerifyEmail = <TError = string>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof verifyEmail>>,
    TError,
    Key,
    AuthVerifyEmailRequest,
    Awaited<ReturnType<typeof verifyEmail>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getVerifyEmailMutationKey();
  const swrFn = getVerifyEmailMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type ResendVerificationMutationResult = NonNullable<
  Awaited<ReturnType<typeof resendVerification>>
>;

/**
 * @summary Resend the account verification email
 */
export const useResendVerification = <TError = string>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof resendVerification>>,
    TError,
    Key,
    AuthResendVerificationRequest,
    Awaited<ReturnType<typeof resendVerification>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getResendVerificationMutationKey();
  const swrFn = getResendVerificationMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
