import { type NextRequest, NextResponse } from 'next/server';

// Edge-side proxy for /v1/account/* into pact-gateway. The hooks
// generated by Orval call /v1/account/profile (and friends) directly
// from the browser; this route exists so those calls never have to
// know the gateway's host -- the SPA only ever talks to its own
// origin, and we can swap PACT_GATEWAY_URL between dev/staging/prod
// without rebuilding the bundle.
//
// In mock mode (NEXT_PUBLIC_API_MOCKING=enabled) MSW intercepts the
// fetch in the browser before it reaches Next.js, so this route is a
// no-op fallback. In real mode, every /v1/account/* request lands
// here, gets the session cookie translated into the Bearer header
// pact-gateway's authMiddleware expects, and is forwarded.

const GATEWAY_URL = process.env.PACT_GATEWAY_URL ?? 'http://localhost:8080';
const SESSION_COOKIE = 'pact_session';
// Header name used by pact-gateway's refresh-on-near-expiry path.
// Forwarded inbound (request side) and reflected outbound (response
// side) so the SPA can roll the cookie forward when the gateway
// returns a fresh session/refresh pair. Keeping the names in sync
// with internal/app/middleware.go (headerRefreshToken et al.).
const REFRESH_HEADER = 'x-pact-refresh-token';
const NEW_SESSION_HEADER = 'x-pact-new-session-token';
const NEW_REFRESH_HEADER = 'x-pact-new-refresh-token';
const NEW_EXPIRES_HEADER = 'x-pact-new-expires-at-unix';

type RouteContext = { params: Promise<{ path: string[] }> };

async function proxy(req: NextRequest, { params }: RouteContext) {
  const { path } = await params;
  const target = `${GATEWAY_URL}/v1/account/${path.join('/')}${req.nextUrl.search}`;

  // Build a fresh header map: never blindly forward the inbound Cookie
  // (which contains pact_session and any other browser cookies); only
  // surface the bearer token the gateway actually consumes.
  const session = req.cookies.get(SESSION_COOKIE)?.value;
  const headers = new Headers();
  // Content-Type must survive so the gateway can parse JSON bodies.
  const ct = req.headers.get('content-type');
  if (ct) headers.set('content-type', ct);
  if (session) headers.set('authorization', `Bearer ${session}`);
  // The SPA may pass a refresh-token header on near-expiry calls so
  // the gateway can rotate the session without bouncing the user.
  // Treat the refresh token as a credential -- only forward it, never
  // log it or echo it.
  const refresh = req.headers.get(REFRESH_HEADER);
  if (refresh) headers.set(REFRESH_HEADER, refresh);

  const hasBody = req.method !== 'GET' && req.method !== 'HEAD';
  const upstream = await fetch(target, {
    method: req.method,
    headers,
    ...(hasBody && { body: req.body, duplex: 'half' }),
  } as RequestInit);

  // Surface the gateway's response. Strip transport-level headers
  // that don't survive a re-stream (Node sets these itself on the
  // outbound response). The X-Pact-New-* headers from a refresh are
  // reflected so the SPA can update its session cookie.
  const out = new Headers();
  upstream.headers.forEach((value, key) => {
    const k = key.toLowerCase();
    if (
      k === 'content-encoding' ||
      k === 'transfer-encoding' ||
      k === 'connection'
    ) {
      return;
    }
    out.set(key, value);
  });
  // If the gateway minted a new session pair, roll the cookie forward
  // server-side so the next browser request already has it. The body
  // headers are still surfaced for clients that want to observe the
  // rotation directly (e.g. a custom SDK).
  const newSession = upstream.headers.get(NEW_SESSION_HEADER);
  const newExpires = upstream.headers.get(NEW_EXPIRES_HEADER);
  const res = new NextResponse(upstream.body, {
    status: upstream.status,
    headers: out,
  });
  if (newSession && newExpires) {
    res.cookies.set({
      name: SESSION_COOKIE,
      value: newSession,
      httpOnly: true,
      sameSite: 'lax',
      secure: process.env.NODE_ENV === 'production',
      path: '/',
      expires: new Date(Number(newExpires) * 1000),
    });
  }
  // Preserve the new refresh-token header so the SPA can persist it
  // wherever it stores refresh credentials (typically a separate
  // httpOnly cookie set by /api/auth/login).
  const newRefresh = upstream.headers.get(NEW_REFRESH_HEADER);
  if (newRefresh) {
    res.headers.set(NEW_REFRESH_HEADER, newRefresh);
  }

  return res;
}

export const GET = (req: NextRequest, ctx: RouteContext) => proxy(req, ctx);
export const POST = (req: NextRequest, ctx: RouteContext) => proxy(req, ctx);
export const PUT = (req: NextRequest, ctx: RouteContext) => proxy(req, ctx);
export const PATCH = (req: NextRequest, ctx: RouteContext) => proxy(req, ctx);
export const DELETE = (req: NextRequest, ctx: RouteContext) => proxy(req, ctx);
