/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */

export interface ConfigConfigResponse {
  /** ClassifierEnforceMode is "shadow" or "enforce". In shadow mode the
   * classifier tag is recorded but never promotes to a block verdict. */
  classifierEnforceMode?: string;
  /** ConsensusMode is "inline" or "shadow" (PACT-432). Inline blocks the
   * /v1/check response until pact-consensus votes; shadow defers the vote
   * to a background completion. Added alongside the runtime enforcement
   * write surface (PACT-472) so GET reflects the full live posture that
   * PATCH /v1/config/enforcement can change. */
  consensusMode?: string;
  /** ConsensusThreshold is the classifier score below which pact-consensus
   * is consulted. Scores in [0, threshold) go to consensus; scores in
   * [threshold, 1] pass straight through. */
  consensusThreshold?: number;
  /** DiagnosticsEnabled indicates whether the causal-diagnostic harness
   * runs counterfactual span-replay on every block decision. */
  diagnosticsEnabled?: boolean;
  /** RequestTimeoutSeconds is the wall-clock budget for a /v1/check request
   * (auth check + pipeline combined) before the gateway gives up. */
  requestTimeoutSeconds?: number;
  /** SandboxEnabled indicates whether external_refs in /v1/check requests
   * trigger an isolated fetch + re-scan. */
  sandboxEnabled?: boolean;
  /** SandboxIsolation is the worker containment level: "none" (plain
   * process) or "namespace" (Linux user+mount namespace with /proc masked). */
  sandboxIsolation?: string;
  /** SandboxRuntimeWrapped indicates whether sandbox workers are spawned under
   * an external runtime wrapper (e.g. gVisor). Only the boolean posture is
   * exposed; the raw runtime argv is intentionally not surfaced. */
  sandboxRuntimeWrapped?: boolean;
  /** SpotlightFormat is the marker style used when spotlight_chunks are
   * present in /v1/check: "delim", "xml", or "json". */
  spotlightFormat?: string;
  /** VectorEnforceMode is "shadow" or "enforce". Controls the filter's
   * SUSPICIOUS verdict (vector engine path). */
  vectorEnforceMode?: string;
}
