/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */

export interface ConfigEnforcementPatchRequest {
  /** ClassifierEnforceMode, if present, must be "shadow" or "enforce". */
  classifierEnforceMode?: string;
  /** ConsensusMode, if present, must be "inline" or "shadow". */
  consensusMode?: string;
  /** VectorEnforceMode, if present, must be "shadow" or "enforce". */
  vectorEnforceMode?: string;
}
