/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */

import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

import type { Key } from 'swr';

import type { CheckCheckRequest, CheckCheckResponse } from './types';

export type checkContentResponse200 = {
  data: CheckCheckResponse;
  status: 200;
};

export type checkContentResponse400 = {
  data: string;
  status: 400;
};

export type checkContentResponse401 = {
  data: string;
  status: 401;
};

export type checkContentResponse429 = {
  data: string;
  status: 429;
};

export type checkContentResponse503 = {
  data: string;
  status: 503;
};

export type checkContentResponse504 = {
  data: string;
  status: 504;
};

export type checkContentResponseSuccess = checkContentResponse200 & {
  headers: Headers;
};

export type checkContentResponseError = (
  | checkContentResponse400
  | checkContentResponse401
  | checkContentResponse429
  | checkContentResponse503
  | checkContentResponse504
) & {
  headers: Headers;
};

export type checkContentResponse =
  | checkContentResponseSuccess
  | checkContentResponseError;

export const getCheckContentUrl = () => {
  return `/api/pact/gateway/v1/check`;
};

/**
 * @summary Evaluate content against the safety pipeline
 */
export const checkContent = async (
  checkCheckRequest: CheckCheckRequest,
  options?: RequestInit
): Promise<checkContentResponse> => {
  const res = await fetch(getCheckContentUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(checkCheckRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: checkContentResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as checkContentResponse;
};

export const getCheckContentMutationFetcher = (options?: RequestInit) => {
  return (_: Key, { arg }: { arg: CheckCheckRequest }) => {
    return checkContent(arg, options);
  };
};

export const getCheckContentMutationKey = () =>
  [`/api/pact/gateway/v1/check`] as const;
