'use client';

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */
import useSWRMutation from 'swr/mutation';
import type { Key } from 'swr';
import type { SWRMutationConfiguration } from 'swr/mutation';

import type { CheckCheckRequest, CheckCheckResponse } from './types';

import {
  checkContentResponse200,
  checkContentResponse400,
  checkContentResponse401,
  checkContentResponse429,
  checkContentResponse503,
  checkContentResponse504,
  checkContentResponseSuccess,
  checkContentResponseError,
  getCheckContentUrl,
  checkContentResponse,
  checkContent,
  getCheckContentMutationFetcher,
  getCheckContentMutationKey,
} from './fetchers';

import { customFetch } from '../custom_fetch';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type CheckContentMutationResult = NonNullable<
  Awaited<ReturnType<typeof checkContent>>
>;

/**
 * @summary Evaluate content against the safety pipeline
 */
export const useCheckContent = <TError = string>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof checkContent>>,
    TError,
    Key,
    CheckCheckRequest,
    Awaited<ReturnType<typeof checkContent>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getCheckContentMutationKey();
  const swrFn = getCheckContentMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
