/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */

export interface FilesFileResponse {
  contentType?: string;
  createdAt?: string;
  filename?: string;
  id?: string;
  purpose?: string;
  sizeBytes?: number;
  status?: string;
  storageKey?: string;
  thumbnailKey?: string;
  updatedAt?: string;
  userId?: string;
}
