/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Files Service
 * Object-storage lifecycle for the signed-in user. Mounted on
pact-gateway at /v1/files/*; the gateway resolves the user_id
from the session cookie before proxying to pact-files over gRPC.
The HTTP body never carries a userId -- the gateway is the only
authority on which user is being acted on.

**File bytes never traverse the gateway.** The browser PUTs and
GETs them directly against object storage using short-lived
presigned URLs. The /v1/files/* surface carries only metadata
and the URLs themselves.

 * OpenAPI spec version: 0.1.0
 */
import type { FileRecordStatus } from './fileRecordStatus';

export interface FileRecord {
  id: string;
  userId: string;
  filename: string;
  /** IANA media type. */
  contentType: string;
  sizeBytes: number;
  /** Caller-supplied tag. Canonical values today: avatar,
  document, attachment. Free-form so new purposes can be
  added without a schema change.
   */
  purpose: string;
  /** Lifecycle:
  - pending    -> RequestUpload returned a presigned PUT URL; awaiting the browser to upload.
  - processing -> ConfirmUpload accepted the upload; MIME / virus / thumbnail pipeline running.
  - ready      -> Pipeline completed; download URLs may be issued.
  - rejected   -> MIME mismatch, virus hit, or other validation failure.
  - deleted    -> Soft-deleted by the user; storage cleanup is async.
   */
  status: FileRecordStatus;
  /** Opaque object key. Not directly addressable. */
  storageKey: string;
  /** Present only for image uploads after thumbnail generation
  completes. Empty for non-images and during processing.
   */
  thumbnailKey: string;
  createdAt: string;
  updatedAt: string;
}
