/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Files Service
 * Object-storage lifecycle for the signed-in user. Mounted on
pact-gateway at /v1/files/*; the gateway resolves the user_id
from the session cookie before proxying to pact-files over gRPC.
The HTTP body never carries a userId -- the gateway is the only
authority on which user is being acted on.

**File bytes never traverse the gateway.** The browser PUTs and
GETs them directly against object storage using short-lived
presigned URLs. The /v1/files/* surface carries only metadata
and the URLs themselves.

 * OpenAPI spec version: 0.1.0
 */
import type { FileRecord } from './fileRecord';

export interface GetFileResponse {
  file: FileRecord;
  /** Presigned GET URL. Present only when status="ready";
  omitted otherwise so the SPA can branch on its presence
  rather than render "click to download" pointing at the
  empty string.
   */
  downloadUrl?: string;
  /** Absolute deadline for the GET. Omitted when downloadUrl is omitted. */
  downloadUrlExpiresAt?: string;
}
