/**
 * Auto-generated from pact-contracts' decisions/pact.decisions.schema.json
 * (vendored at schema/pact-decisions/pact.decisions.schema.json).
 * Do not edit this file manually - run `pnpm schema:codegen` to regenerate.
 */

export * from './decisions';
