/**
 * Auto-generated barrel for pact-contracts' vendored decisions/ artifacts
 * (schema/pact-decisions/pact.decisions.schema.json and
 * schema/pact-decisions/benign_labels.json).
 * Do not edit this file manually - run `pnpm schema:codegen` to regenerate.
 */

export * from './decisions';
export * from './benign_labels';
