/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * Feature Service
 * Feature flag management for PACT
 * OpenAPI spec version: 1.0.0
 */

export interface Feature {
  id: string;
  title: string;
  isEnabled: boolean;
}
