/**
 * Generated by orval 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */
import type { AccountConsentResponse } from './accountConsentResponse';

export interface AccountConsentsResponse {
  consents?: AccountConsentResponse[];
}
