/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Account Service
 * Profile, preferences, consents, and GDPR data-rights surface for the
signed-in user. Mounted on pact-gateway at /v1/account/*; the
gateway resolves the user_id from the session cookie before
proxying to pact-account over gRPC. The HTTP body never carries a
userId -- the gateway is the only authority on which user is
being acted on.

 * OpenAPI spec version: 0.1.0
 */

export interface Preferences {
  userId: string;
  /** Operational toggle for marketing emails. The legal evidence
  for this consent lives in the consents collection
  (RecordConsent with document="marketing_email").
   */
  marketingEmail: boolean;
  /** Operational toggle for product/changelog emails. */
  productEmail: boolean;
  updatedAt: string;
}
