/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * Account Service
 * Profile, preferences, consents, and GDPR data-rights surface for the
 * signed-in user. Mounted on pact-gateway at /v1/account/*; the
 * gateway resolves the user_id from the session cookie before
 * proxying to pact-account over gRPC. The HTTP body never carries a
 * userId -- the gateway is the only authority on which user is
 * being acted on.
 *
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateProfileRequest {
  displayName?: string;
  avatarUrl?: string;
  locale?: string;
  timezone?: string;
  bio?: string;
  /** Field names the caller intends to write. Unlisted fields keep
   * their stored value. Allowed: display_name, avatar_url,
   * locale, timezone, bio.
   *  */
  updateMask: string[];
}
