/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Files Service
 * Object-storage lifecycle for the signed-in user. Mounted on
pact-gateway at /v1/files/*; the gateway resolves the user_id
from the session cookie before proxying to pact-files over gRPC.
The HTTP body never carries a userId -- the gateway is the only
authority on which user is being acted on.

**File bytes never traverse the gateway.** The browser PUTs and
GETs them directly against object storage using short-lived
presigned URLs. The /v1/files/* surface carries only metadata
and the URLs themselves.

 * OpenAPI spec version: 0.1.0
 */

import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

import type { Arguments, Key } from 'swr';

import type {
  BadRequestResponse,
  FileRecord,
  GetFileResponse,
  ListFilesParams,
  ListFilesResponse,
  NotFoundResponse,
  RequestUploadRequest,
  RequestUploadResponse,
  TooManyRequestsResponse,
  UnauthorizedResponse,
} from './types';

export type listFilesResponse200 = {
  data: ListFilesResponse;
  status: 200;
};

export type listFilesResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type listFilesResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type listFilesResponseSuccess = listFilesResponse200 & {
  headers: Headers;
};

export type listFilesResponseError = (
  | listFilesResponse400
  | listFilesResponse401
) & {
  headers: Headers;
};

export type listFilesResponse =
  | listFilesResponseSuccess
  | listFilesResponseError;

export const getListFilesUrl = (params?: ListFilesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/files/?${stringifiedParams}`
    : `/v1/files/`;
};

/**
 * Returns a paginated page of FileRecords owned by the caller,
ordered by created_at descending. Soft-deleted rows are
excluded. The `total` field is the caller's non-deleted row
count so the SPA can render "page x of y" without a
follow-up count call. Download URLs are NOT included on
list rows -- call GET /v1/files/{id} after the user picks
a row.

 * @summary List the caller's files, newest first
 */
export const listFiles = async (
  params?: ListFilesParams,
  options?: RequestInit
): Promise<listFilesResponse> => {
  const res = await fetch(getListFilesUrl(params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listFilesResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listFilesResponse;
};

export const getListFilesKey = (params?: ListFilesParams) =>
  [`/v1/files/`, ...(params ? [params] : [])] as const;

export type requestFileUploadResponse201 = {
  data: RequestUploadResponse;
  status: 201;
};

export type requestFileUploadResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type requestFileUploadResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type requestFileUploadResponse429 = {
  data: TooManyRequestsResponse;
  status: 429;
};

export type requestFileUploadResponseSuccess = requestFileUploadResponse201 & {
  headers: Headers;
};

export type requestFileUploadResponseError = (
  | requestFileUploadResponse400
  | requestFileUploadResponse401
  | requestFileUploadResponse429
) & {
  headers: Headers;
};

export type requestFileUploadResponse =
  | requestFileUploadResponseSuccess
  | requestFileUploadResponseError;

export const getRequestFileUploadUrl = () => {
  return `/v1/files/`;
};

/**
 * Creates a pending FileRecord and returns a short-lived
presigned PUT URL the browser uses to upload the bytes
directly to object storage. Follow up with
POST /v1/files/{id}/confirm once the PUT succeeds.

 * @summary Request a presigned upload URL
 */
export const requestFileUpload = async (
  requestUploadRequest: RequestUploadRequest,
  options?: RequestInit
): Promise<requestFileUploadResponse> => {
  const res = await fetch(getRequestFileUploadUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(requestUploadRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: requestFileUploadResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as requestFileUploadResponse;
};

export const getRequestFileUploadMutationFetcher = (options?: RequestInit) => {
  return (_: Key, { arg }: { arg: RequestUploadRequest }) => {
    return requestFileUpload(arg, options);
  };
};

export const getRequestFileUploadMutationKey = () => [`/v1/files/`] as const;

export type confirmFileUploadResponse200 = {
  data: FileRecord;
  status: 200;
};

export type confirmFileUploadResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type confirmFileUploadResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type confirmFileUploadResponseSuccess = confirmFileUploadResponse200 & {
  headers: Headers;
};

export type confirmFileUploadResponseError = (
  | confirmFileUploadResponse401
  | confirmFileUploadResponse404
) & {
  headers: Headers;
};

export type confirmFileUploadResponse =
  | confirmFileUploadResponseSuccess
  | confirmFileUploadResponseError;

export const getConfirmFileUploadUrl = (id: string) => {
  return `/v1/files/${id}/confirm`;
};

/**
 * Moves the record from "pending" -> "processing". pact-files
cross-checks the actual object against the declared MIME and
size, runs ClamAV, and generates a thumbnail for images.
Status flips to "ready" or "rejected" asynchronously -- the
SPA polls GET /v1/files/{id} until the terminal state.

 * @summary Confirm a completed upload and kick off validation
 */
export const confirmFileUpload = async (
  id: string,
  options?: RequestInit
): Promise<confirmFileUploadResponse> => {
  const res = await fetch(getConfirmFileUploadUrl(id), {
    ...options,
    method: 'POST',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: confirmFileUploadResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as confirmFileUploadResponse;
};

export const getConfirmFileUploadMutationFetcher = (
  id: string,
  options?: RequestInit
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return confirmFileUpload(id, options);
  };
};

export const getConfirmFileUploadMutationKey = (id: string) =>
  [`/v1/files/${id}/confirm`] as const;

export type getFileResponse200 = {
  data: GetFileResponse;
  status: 200;
};

export type getFileResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type getFileResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getFileResponseSuccess = getFileResponse200 & {
  headers: Headers;
};

export type getFileResponseError = (getFileResponse401 | getFileResponse404) & {
  headers: Headers;
};

export type getFileResponse = getFileResponseSuccess | getFileResponseError;

export const getGetFileUrl = (id: string) => {
  return `/v1/files/${id}`;
};

/**
 * @summary Get file metadata, plus a presigned download URL when ready
 */
export const getFile = async (
  id: string,
  options?: RequestInit
): Promise<getFileResponse> => {
  const res = await fetch(getGetFileUrl(id), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getFileResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getFileResponse;
};

export const getGetFileKey = (id: string) => [`/v1/files/${id}`] as const;

export type deleteFileResponse204 = {
  data: void;
  status: 204;
};

export type deleteFileResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type deleteFileResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type deleteFileResponseSuccess = deleteFileResponse204 & {
  headers: Headers;
};

export type deleteFileResponseError = (
  | deleteFileResponse401
  | deleteFileResponse404
) & {
  headers: Headers;
};

export type deleteFileResponse =
  | deleteFileResponseSuccess
  | deleteFileResponseError;

export const getDeleteFileUrl = (id: string) => {
  return `/v1/files/${id}`;
};

/**
 * Marks the record "deleted" and schedules removal of the
object and any thumbnail from storage. Subsequent DELETE
calls succeed without error.

 * @summary Soft-delete a file (idempotent)
 */
export const deleteFile = async (
  id: string,
  options?: RequestInit
): Promise<deleteFileResponse> => {
  const res = await fetch(getDeleteFileUrl(id), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteFileResponse['data'] = body ? JSON.parse(body) : undefined;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteFileResponse;
};

export const getDeleteFileMutationFetcher = (
  id: string,
  options?: RequestInit
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteFile(id, options);
  };
};

export const getDeleteFileMutationKey = (id: string) =>
  [`/v1/files/${id}`] as const;
