/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */

import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

import type { Arguments, Key } from 'swr';

import type {
  BoundaryErrorResponse,
  FilesFileResponse,
  FilesGetFileResponse,
  FilesListFilesResponse,
  FilesRequestUploadBody,
  FilesRequestUploadResponse,
  GetFilesParams,
} from './types';

export type getFilesResponse200 = {
  data: FilesListFilesResponse;
  status: 200;
};

export type getFilesResponse400 = {
  data: string;
  status: 400;
};

export type getFilesResponse401 = {
  data: string;
  status: 401;
};

export type getFilesResponseSuccess = getFilesResponse200 & {
  headers: Headers;
};

export type getFilesResponseError = (
  | getFilesResponse400
  | getFilesResponse401
) & {
  headers: Headers;
};

export type getFilesResponse = getFilesResponseSuccess | getFilesResponseError;

export const getGetFilesUrl = (params?: GetFilesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/pact/gateway/v1/files/?${stringifiedParams}`
    : `/api/pact/gateway/v1/files/`;
};

/**
 * @summary List the caller's files, newest first
 */
export const getFiles = async (
  params?: GetFilesParams,
  options?: RequestInit
): Promise<getFilesResponse> => {
  const res = await fetch(getGetFilesUrl(params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getFilesResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getFilesResponse;
};

export const getGetFilesKey = (params?: GetFilesParams) =>
  [`/api/pact/gateway/v1/files/`, ...(params ? [params] : [])] as const;

export type postFilesResponse201 = {
  data: FilesRequestUploadResponse;
  status: 201;
};

export type postFilesResponse400 = {
  data: string;
  status: 400;
};

export type postFilesResponse401 = {
  data: string;
  status: 401;
};

export type postFilesResponse429 = {
  data: string;
  status: 429;
};

export type postFilesResponseSuccess = postFilesResponse201 & {
  headers: Headers;
};

export type postFilesResponseError = (
  | postFilesResponse400
  | postFilesResponse401
  | postFilesResponse429
) & {
  headers: Headers;
};

export type postFilesResponse =
  | postFilesResponseSuccess
  | postFilesResponseError;

export const getPostFilesUrl = () => {
  return `/api/pact/gateway/v1/files/`;
};

/**
 * @summary Request a presigned upload URL
 */
export const postFiles = async (
  filesRequestUploadBody: FilesRequestUploadBody,
  options?: RequestInit
): Promise<postFilesResponse> => {
  const res = await fetch(getPostFilesUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(filesRequestUploadBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postFilesResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postFilesResponse;
};

export const getPostFilesMutationFetcher = (options?: RequestInit) => {
  return (_: Key, { arg }: { arg: FilesRequestUploadBody }) => {
    return postFiles(arg, options);
  };
};

export const getPostFilesMutationKey = () =>
  [`/api/pact/gateway/v1/files/`] as const;

export type deleteFilesIdResponse204 = {
  data: void;
  status: 204;
};

export type deleteFilesIdResponse401 = {
  data: string;
  status: 401;
};

export type deleteFilesIdResponse404 = {
  data: BoundaryErrorResponse;
  status: 404;
};

export type deleteFilesIdResponseSuccess = deleteFilesIdResponse204 & {
  headers: Headers;
};

export type deleteFilesIdResponseError = (
  | deleteFilesIdResponse401
  | deleteFilesIdResponse404
) & {
  headers: Headers;
};

export type deleteFilesIdResponse =
  | deleteFilesIdResponseSuccess
  | deleteFilesIdResponseError;

export const getDeleteFilesIdUrl = (id: string) => {
  return `/api/pact/gateway/v1/files/${id}`;
};

/**
 * @summary Soft-delete a file (idempotent)
 */
export const deleteFilesId = async (
  id: string,
  options?: RequestInit
): Promise<deleteFilesIdResponse> => {
  const res = await fetch(getDeleteFilesIdUrl(id), {
    ...options,
    method: 'DELETE',
  });

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteFilesIdResponse['data'] = body
    ? contentType.includes('json')
      ? JSON.parse(body)
      : body
    : undefined;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteFilesIdResponse;
};

export const getDeleteFilesIdMutationFetcher = (
  id: string,
  options?: RequestInit
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteFilesId(id, options);
  };
};

export const getDeleteFilesIdMutationKey = (id: string) =>
  [`/api/pact/gateway/v1/files/${id}`] as const;

export type getFilesIdResponse200 = {
  data: FilesGetFileResponse;
  status: 200;
};

export type getFilesIdResponse401 = {
  data: string;
  status: 401;
};

export type getFilesIdResponse404 = {
  data: BoundaryErrorResponse;
  status: 404;
};

export type getFilesIdResponseSuccess = getFilesIdResponse200 & {
  headers: Headers;
};

export type getFilesIdResponseError = (
  | getFilesIdResponse401
  | getFilesIdResponse404
) & {
  headers: Headers;
};

export type getFilesIdResponse =
  | getFilesIdResponseSuccess
  | getFilesIdResponseError;

export const getGetFilesIdUrl = (id: string) => {
  return `/api/pact/gateway/v1/files/${id}`;
};

/**
 * @summary Get file metadata and presigned download URL when ready
 */
export const getFilesId = async (
  id: string,
  options?: RequestInit
): Promise<getFilesIdResponse> => {
  const res = await fetch(getGetFilesIdUrl(id), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getFilesIdResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getFilesIdResponse;
};

export const getGetFilesIdKey = (id: string) =>
  [`/api/pact/gateway/v1/files/${id}`] as const;

export type postFilesIdConfirmResponse200 = {
  data: FilesFileResponse;
  status: 200;
};

export type postFilesIdConfirmResponse401 = {
  data: string;
  status: 401;
};

export type postFilesIdConfirmResponse404 = {
  data: BoundaryErrorResponse;
  status: 404;
};

export type postFilesIdConfirmResponseSuccess =
  postFilesIdConfirmResponse200 & {
    headers: Headers;
  };

export type postFilesIdConfirmResponseError = (
  | postFilesIdConfirmResponse401
  | postFilesIdConfirmResponse404
) & {
  headers: Headers;
};

export type postFilesIdConfirmResponse =
  | postFilesIdConfirmResponseSuccess
  | postFilesIdConfirmResponseError;

export const getPostFilesIdConfirmUrl = (id: string) => {
  return `/api/pact/gateway/v1/files/${id}/confirm`;
};

/**
 * @summary Confirm a completed upload and start the validation pipeline
 */
export const postFilesIdConfirm = async (
  id: string,
  options?: RequestInit
): Promise<postFilesIdConfirmResponse> => {
  const res = await fetch(getPostFilesIdConfirmUrl(id), {
    ...options,
    method: 'POST',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postFilesIdConfirmResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postFilesIdConfirmResponse;
};

export const getPostFilesIdConfirmMutationFetcher = (
  id: string,
  options?: RequestInit
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return postFilesIdConfirm(id, options);
  };
};

export const getPostFilesIdConfirmMutationKey = (id: string) =>
  [`/api/pact/gateway/v1/files/${id}/confirm`] as const;
