'use client';

/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Files Service
 * Object-storage lifecycle for the signed-in user. Mounted on
pact-gateway at /v1/files/*; the gateway resolves the user_id
from the session cookie before proxying to pact-files over gRPC.
The HTTP body never carries a userId -- the gateway is the only
authority on which user is being acted on.

**File bytes never traverse the gateway.** The browser PUTs and
GETs them directly against object storage using short-lived
presigned URLs. The /v1/files/* surface carries only metadata
and the URLs themselves.

 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr';
import useSWRMutation from 'swr/mutation';
import type { Arguments, Key, SWRConfiguration } from 'swr';
import type { SWRMutationConfiguration } from 'swr/mutation';

import type { AxiosError, AxiosRequestConfig } from 'axios';

import type {
  BadRequestResponse,
  FileRecord,
  GetFileResponse,
  ListFilesParams,
  ListFilesResponse,
  NotFoundResponse,
  RequestUploadRequest,
  RequestUploadResponse,
  TooManyRequestsResponse,
  UnauthorizedResponse,
} from './types';

import {
  listFilesResponse200,
  listFilesResponse400,
  listFilesResponse401,
  listFilesResponseSuccess,
  listFilesResponseError,
  getListFilesUrl,
  listFilesResponse,
  listFiles,
  getListFilesKey,
  requestFileUploadResponse201,
  requestFileUploadResponse400,
  requestFileUploadResponse401,
  requestFileUploadResponse429,
  requestFileUploadResponseSuccess,
  requestFileUploadResponseError,
  getRequestFileUploadUrl,
  requestFileUploadResponse,
  requestFileUpload,
  getRequestFileUploadMutationFetcher,
  getRequestFileUploadMutationKey,
  confirmFileUploadResponse200,
  confirmFileUploadResponse401,
  confirmFileUploadResponse404,
  confirmFileUploadResponseSuccess,
  confirmFileUploadResponseError,
  getConfirmFileUploadUrl,
  confirmFileUploadResponse,
  confirmFileUpload,
  getConfirmFileUploadMutationFetcher,
  getConfirmFileUploadMutationKey,
  getFileResponse200,
  getFileResponse401,
  getFileResponse404,
  getFileResponseSuccess,
  getFileResponseError,
  getGetFileUrl,
  getFileResponse,
  getFile,
  getGetFileKey,
  deleteFileResponse204,
  deleteFileResponse401,
  deleteFileResponse404,
  deleteFileResponseSuccess,
  deleteFileResponseError,
  getDeleteFileUrl,
  deleteFileResponse,
  deleteFile,
  getDeleteFileMutationFetcher,
  getDeleteFileMutationKey,
} from './fetchers';

export type ListFilesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listFiles>>
>;

/**
 * @summary List the caller's files, newest first
 */
export const useListFiles = <
  TError = Promise<BadRequestResponse | UnauthorizedResponse>,
>(
  params?: ListFilesParams,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof listFiles>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
    fetch?: RequestInit;
  }
) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getListFilesKey(params) : null));
  const swrFn = () => listFiles(params, fetchOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions
  );

  return {
    swrKey,
    ...query,
  };
};

export type RequestFileUploadMutationResult = NonNullable<
  Awaited<ReturnType<typeof requestFileUpload>>
>;

/**
 * @summary Request a presigned upload URL
 */
export const useRequestFileUpload = <
  TError = Promise<
    BadRequestResponse | UnauthorizedResponse | TooManyRequestsResponse
  >,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof requestFileUpload>>,
    TError,
    Key,
    RequestUploadRequest,
    Awaited<ReturnType<typeof requestFileUpload>>
  > & { swrKey?: string };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getRequestFileUploadMutationKey();
  const swrFn = getRequestFileUploadMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type ConfirmFileUploadMutationResult = NonNullable<
  Awaited<ReturnType<typeof confirmFileUpload>>
>;

/**
 * @summary Confirm a completed upload and kick off validation
 */
export const useConfirmFileUpload = <
  TError = Promise<UnauthorizedResponse | NotFoundResponse>,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof confirmFileUpload>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof confirmFileUpload>>
    > & { swrKey?: string };
    fetch?: RequestInit;
  }
) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getConfirmFileUploadMutationKey(id);
  const swrFn = getConfirmFileUploadMutationFetcher(id, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type GetFileQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFile>>
>;

/**
 * @summary Get file metadata, plus a presigned download URL when ready
 */
export const useGetFile = <
  TError = Promise<UnauthorizedResponse | NotFoundResponse>,
>(
  id: string,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getFile>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
    fetch?: RequestInit;
  }
) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && !!id;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetFileKey(id) : null));
  const swrFn = () => getFile(id, fetchOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions
  );

  return {
    swrKey,
    ...query,
  };
};

export type DeleteFileMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteFile>>
>;

/**
 * @summary Soft-delete a file (idempotent)
 */
export const useDeleteFile = <
  TError = Promise<UnauthorizedResponse | NotFoundResponse>,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof deleteFile>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof deleteFile>>
    > & { swrKey?: string };
    fetch?: RequestInit;
  }
) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getDeleteFileMutationKey(id);
  const swrFn = getDeleteFileMutationFetcher(id, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
