'use client';

/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr';
import useSWRMutation from 'swr/mutation';
import type { Arguments, Key, SWRConfiguration } from 'swr';
import type { SWRMutationConfiguration } from 'swr/mutation';

import type { AxiosError, AxiosRequestConfig } from 'axios';

import type {
  BoundaryErrorResponse,
  FilesFileResponse,
  FilesGetFileResponse,
  FilesListFilesResponse,
  FilesRequestUploadBody,
  FilesRequestUploadResponse,
  GetFilesParams,
} from './types';

import {
  getFilesResponse200,
  getFilesResponse400,
  getFilesResponse401,
  getFilesResponseSuccess,
  getFilesResponseError,
  getGetFilesUrl,
  getFilesResponse,
  getFiles,
  getGetFilesKey,
  postFilesResponse201,
  postFilesResponse400,
  postFilesResponse401,
  postFilesResponse429,
  postFilesResponseSuccess,
  postFilesResponseError,
  getPostFilesUrl,
  postFilesResponse,
  postFiles,
  getPostFilesMutationFetcher,
  getPostFilesMutationKey,
  deleteFilesIdResponse204,
  deleteFilesIdResponse401,
  deleteFilesIdResponse404,
  deleteFilesIdResponseSuccess,
  deleteFilesIdResponseError,
  getDeleteFilesIdUrl,
  deleteFilesIdResponse,
  deleteFilesId,
  getDeleteFilesIdMutationFetcher,
  getDeleteFilesIdMutationKey,
  getFilesIdResponse200,
  getFilesIdResponse401,
  getFilesIdResponse404,
  getFilesIdResponseSuccess,
  getFilesIdResponseError,
  getGetFilesIdUrl,
  getFilesIdResponse,
  getFilesId,
  getGetFilesIdKey,
  postFilesIdConfirmResponse200,
  postFilesIdConfirmResponse401,
  postFilesIdConfirmResponse404,
  postFilesIdConfirmResponseSuccess,
  postFilesIdConfirmResponseError,
  getPostFilesIdConfirmUrl,
  postFilesIdConfirmResponse,
  postFilesIdConfirm,
  getPostFilesIdConfirmMutationFetcher,
  getPostFilesIdConfirmMutationKey,
} from './fetchers';

export type GetFilesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFiles>>
>;

/**
 * @summary List the caller's files, newest first
 */
export const useGetFiles = <TError = Promise<string>>(
  params?: GetFilesParams,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getFiles>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
    fetch?: RequestInit;
  }
) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetFilesKey(params) : null));
  const swrFn = () => getFiles(params, fetchOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions
  );

  return {
    swrKey,
    ...query,
  };
};

export type PostFilesMutationResult = NonNullable<
  Awaited<ReturnType<typeof postFiles>>
>;

/**
 * @summary Request a presigned upload URL
 */
export const usePostFiles = <TError = Promise<string>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postFiles>>,
    TError,
    Key,
    FilesRequestUploadBody,
    Awaited<ReturnType<typeof postFiles>>
  > & { swrKey?: string };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostFilesMutationKey();
  const swrFn = getPostFilesMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type DeleteFilesIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteFilesId>>
>;

/**
 * @summary Soft-delete a file (idempotent)
 */
export const useDeleteFilesId = <
  TError = Promise<string | BoundaryErrorResponse>,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof deleteFilesId>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof deleteFilesId>>
    > & { swrKey?: string };
    fetch?: RequestInit;
  }
) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getDeleteFilesIdMutationKey(id);
  const swrFn = getDeleteFilesIdMutationFetcher(id, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type GetFilesIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFilesId>>
>;

/**
 * @summary Get file metadata and presigned download URL when ready
 */
export const useGetFilesId = <TError = Promise<string | BoundaryErrorResponse>>(
  id: string,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getFilesId>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
    fetch?: RequestInit;
  }
) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const isEnabled =
    swrOptions?.enabled !== false && id !== null && id !== undefined;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetFilesIdKey(id) : null));
  const swrFn = () => getFilesId(id, fetchOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions
  );

  return {
    swrKey,
    ...query,
  };
};

export type PostFilesIdConfirmMutationResult = NonNullable<
  Awaited<ReturnType<typeof postFilesIdConfirm>>
>;

/**
 * @summary Confirm a completed upload and start the validation pipeline
 */
export const usePostFilesIdConfirm = <
  TError = Promise<string | BoundaryErrorResponse>,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof postFilesIdConfirm>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof postFilesIdConfirm>>
    > & { swrKey?: string };
    fetch?: RequestInit;
  }
) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostFilesIdConfirmMutationKey(id);
  const swrFn = getPostFilesIdConfirmMutationFetcher(id, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
