/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */
import type { FilterMatchedSpan } from './filterMatchedSpan';

export interface FilterTestRuleResponse {
  confidence?: number;
  latencyMs?: number;
  matchedSpan?: FilterMatchedSpan;
  normalizedInput?: string;
  reason?: string;
  ruleId?: string;
  sanitized?: boolean;
  sanitizedInput?: string;
  shadow?: boolean;
  verdict: string;
}
