/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */

export interface FilterLoadedPackResponse {
  /** "regex" | "vector" | "literal" | "unknown" */
  engineKind: string;
  id: string;
  loadedAt: string;
  name: string;
  ruleCount?: number;
  /** "built_in" | "policy_synced" | "unknown" */
  source: string;
  version?: string;
}
