/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */

import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

import type { Key } from 'swr';

import type {
  PolicyIssueTokenRequest,
  PolicyIssueTokenResponse,
} from './types';

export type issueTokenResponse201 = {
  data: PolicyIssueTokenResponse;
  status: 201;
};

export type issueTokenResponse400 = {
  data: string;
  status: 400;
};

export type issueTokenResponse401 = {
  data: string;
  status: 401;
};

export type issueTokenResponse429 = {
  data: string;
  status: 429;
};

export type issueTokenResponse502 = {
  data: string;
  status: 502;
};

export type issueTokenResponse503 = {
  data: string;
  status: 503;
};

export type issueTokenResponse504 = {
  data: string;
  status: 504;
};

export type issueTokenResponseSuccess = issueTokenResponse201 & {
  headers: Headers;
};

export type issueTokenResponseError = (
  | issueTokenResponse400
  | issueTokenResponse401
  | issueTokenResponse429
  | issueTokenResponse502
  | issueTokenResponse503
  | issueTokenResponse504
) & {
  headers: Headers;
};

export type issueTokenResponse =
  | issueTokenResponseSuccess
  | issueTokenResponseError;

export const getIssueTokenUrl = () => {
  return `/api/pact/gateway/v1/policy/tokens`;
};

/**
 * @summary Mint a capability token
 */
export const issueToken = async (
  policyIssueTokenRequest: PolicyIssueTokenRequest,
  options?: RequestInit
): Promise<issueTokenResponse> => {
  const res = await fetch(getIssueTokenUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(policyIssueTokenRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: issueTokenResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as issueTokenResponse;
};

export const getIssueTokenMutationFetcher = (options?: RequestInit) => {
  return (_: Key, { arg }: { arg: PolicyIssueTokenRequest }) => {
    return issueToken(arg, options);
  };
};

export const getIssueTokenMutationKey = () =>
  [`/api/pact/gateway/v1/policy/tokens`] as const;
