'use client';

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */
import useSWRMutation from 'swr/mutation';
import type { Key } from 'swr';
import type { SWRMutationConfiguration } from 'swr/mutation';

import type {
  BoundaryErrorResponse,
  PolicyIssueTokenRequest,
  PolicyIssueTokenResponse,
} from './types';

import {
  issueTokenResponse201,
  issueTokenResponse400,
  issueTokenResponse401,
  issueTokenResponse429,
  issueTokenResponse502,
  issueTokenResponse503,
  issueTokenResponse504,
  issueTokenResponseSuccess,
  issueTokenResponseError,
  getIssueTokenUrl,
  issueTokenResponse,
  issueToken,
  getIssueTokenMutationFetcher,
  getIssueTokenMutationKey,
} from './fetchers';

import { customFetch } from '../custom_fetch';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type IssueTokenMutationResult = NonNullable<
  Awaited<ReturnType<typeof issueToken>>
>;

/**
 * @summary Mint a capability token
 */
export const useIssueToken = <
  TError = BoundaryErrorResponse | string,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof issueToken>>,
    TError,
    Key,
    PolicyIssueTokenRequest,
    Awaited<ReturnType<typeof issueToken>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getIssueTokenMutationKey();
  const swrFn = getIssueTokenMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
