/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */

import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

import type { Key } from 'swr';

import type {
  FilterListPacksResponse,
  FilterTestRuleRequest,
  FilterTestRuleResponse,
} from './types';

export type listLoadedPacksResponse200 = {
  data: FilterListPacksResponse;
  status: 200;
};

export type listLoadedPacksResponse401 = {
  data: string;
  status: 401;
};

export type listLoadedPacksResponse502 = {
  data: string;
  status: 502;
};

export type listLoadedPacksResponse503 = {
  data: string;
  status: 503;
};

export type listLoadedPacksResponse504 = {
  data: string;
  status: 504;
};

export type listLoadedPacksResponseSuccess = listLoadedPacksResponse200 & {
  headers: Headers;
};

export type listLoadedPacksResponseError = (
  | listLoadedPacksResponse401
  | listLoadedPacksResponse502
  | listLoadedPacksResponse503
  | listLoadedPacksResponse504
) & {
  headers: Headers;
};

export type listLoadedPacksResponse =
  | listLoadedPacksResponseSuccess
  | listLoadedPacksResponseError;

export const getListLoadedPacksUrl = () => {
  return `/api/pact/gateway/v1/filter/packs`;
};

/**
 * @summary List loaded rule packs and engines
 */
export const listLoadedPacks = async (
  options?: RequestInit
): Promise<listLoadedPacksResponse> => {
  const res = await fetch(getListLoadedPacksUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listLoadedPacksResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listLoadedPacksResponse;
};

export const getListLoadedPacksKey = () =>
  [`/api/pact/gateway/v1/filter/packs`] as const;

export type testRuleResponse200 = {
  data: FilterTestRuleResponse;
  status: 200;
};

export type testRuleResponse400 = {
  data: string;
  status: 400;
};

export type testRuleResponse401 = {
  data: string;
  status: 401;
};

export type testRuleResponse502 = {
  data: string;
  status: 502;
};

export type testRuleResponse503 = {
  data: string;
  status: 503;
};

export type testRuleResponse504 = {
  data: string;
  status: 504;
};

export type testRuleResponseSuccess = testRuleResponse200 & {
  headers: Headers;
};

export type testRuleResponseError = (
  | testRuleResponse400
  | testRuleResponse401
  | testRuleResponse502
  | testRuleResponse503
  | testRuleResponse504
) & {
  headers: Headers;
};

export type testRuleResponse = testRuleResponseSuccess | testRuleResponseError;

export const getTestRuleUrl = () => {
  return `/api/pact/gateway/v1/filter/test-rule`;
};

/**
 * @summary Test a candidate rule against a sample
 */
export const testRule = async (
  filterTestRuleRequest: FilterTestRuleRequest,
  options?: RequestInit
): Promise<testRuleResponse> => {
  const res = await fetch(getTestRuleUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(filterTestRuleRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: testRuleResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as testRuleResponse;
};

export const getTestRuleMutationFetcher = (options?: RequestInit) => {
  return (_: Key, { arg }: { arg: FilterTestRuleRequest }) => {
    return testRule(arg, options);
  };
};

export const getTestRuleMutationKey = () =>
  [`/api/pact/gateway/v1/filter/test-rule`] as const;
