'use client';

/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr';
import useSWRMutation from 'swr/mutation';
import type { Key, SWRConfiguration } from 'swr';
import type { SWRMutationConfiguration } from 'swr/mutation';

import type {
  BoundaryErrorResponse,
  FilterListPacksResponse,
  FilterTestRuleRequest,
  FilterTestRuleResponse,
} from './types';

import {
  listLoadedPacksResponse200,
  listLoadedPacksResponse401,
  listLoadedPacksResponse502,
  listLoadedPacksResponse503,
  listLoadedPacksResponse504,
  listLoadedPacksResponseSuccess,
  listLoadedPacksResponseError,
  getListLoadedPacksUrl,
  listLoadedPacksResponse,
  listLoadedPacks,
  getListLoadedPacksKey,
  testRuleResponse200,
  testRuleResponse400,
  testRuleResponse401,
  testRuleResponse502,
  testRuleResponse503,
  testRuleResponse504,
  testRuleResponseSuccess,
  testRuleResponseError,
  getTestRuleUrl,
  testRuleResponse,
  testRule,
  getTestRuleMutationFetcher,
  getTestRuleMutationKey,
} from './fetchers';

import { customFetch } from '../custom_fetch';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type ListLoadedPacksQueryResult = NonNullable<
  Awaited<ReturnType<typeof listLoadedPacks>>
>;

/**
 * @summary List loaded rule packs and engines
 */
export const useListLoadedPacks = <
  TError = string | BoundaryErrorResponse,
>(options?: {
  swr?: SWRConfiguration<
    Awaited<ReturnType<typeof listLoadedPacks>>,
    TError
  > & { swrKey?: Key; enabled?: boolean };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getListLoadedPacksKey() : null));
  const swrFn = () => listLoadedPacks(requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions
  );

  return {
    swrKey,
    ...query,
  };
};

export type TestRuleMutationResult = NonNullable<
  Awaited<ReturnType<typeof testRule>>
>;

/**
 * @summary Test a candidate rule against a sample
 */
export const useTestRule = <TError = string | BoundaryErrorResponse>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof testRule>>,
    TError,
    Key,
    FilterTestRuleRequest,
    Awaited<ReturnType<typeof testRule>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getTestRuleMutationKey();
  const swrFn = getTestRuleMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
