#!/usr/bin/env node

/**
 * Kafka Topic Schema Codegen (json-schema-to-typescript)
 *
 * Generates TypeScript types from every vendored Kafka topic JSON Schema
 * under schema/pact-{topic} (mirrored from pact-contracts via
 * `pnpm api:update`) into src/__codegen__/schema/pact-{topic}.
 *
 * pact.decisions also vendors a non-schema benign-label vocabulary
 * (schema/pact-decisions/benign_labels.json, PACT-574) alongside its JSON
 * Schema. That file isn't a JSON Schema, so it's a straight read-and-emit
 * rather than a json-schema-to-typescript compile, and only pact.decisions
 * carries it today.
 *
 * Usage: node scripts/schema-codegen.mjs
 */

import { execSync } from 'child_process';
import { mkdir, readFile, writeFile } from 'fs/promises';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

import { compile } from 'json-schema-to-typescript';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SCHEMA_ROOT = join(ROOT, 'schema');
const OUTPUT_ROOT = join(ROOT, 'src/__codegen__/schema');

const run = (cmd) => execSync(cmd, { stdio: 'inherit', cwd: ROOT });

// Every vendored Kafka topic schema this script compiles. `topicName` feeds
// json-schema-to-typescript as a fallback root-interface name, but each
// schema's own `title` (e.g. "pact.decisions") wins whenever present -- see
// the compile() call below.
const TOPICS = [
  {
    schemaDir: 'pact-decisions',
    schemaFile: 'pact.decisions.schema.json',
    topicName: 'PactDecisions',
    outputFile: 'decisions.ts',
    benignLabels: true,
  },
  {
    schemaDir: 'pact-auth',
    schemaFile: 'pact.auth.schema.json',
    topicName: 'PactAuth',
    outputFile: 'auth.ts',
  },
  {
    schemaDir: 'pact-account',
    schemaFile: 'pact.account.schema.json',
    topicName: 'PactAccount',
    outputFile: 'account.ts',
  },
  {
    schemaDir: 'pact-files',
    schemaFile: 'pact.files.schema.json',
    topicName: 'PactFiles',
    outputFile: 'files.ts',
  },
];

const bannerFor = (file, schemaDir, schemaFile) => `/**
 * Auto-generated from pact-contracts' vendored ${schemaFile}
 * (schema/${schemaDir}/${schemaFile}).
 * Do not edit ${file} manually - run \`pnpm schema:codegen\` to regenerate.
 */
`;

const barrelBannerFor = (schemaDir, exports) => `/**
 * Auto-generated barrel for pact-contracts' vendored ${schemaDir}/ artifacts.
 * Do not edit this file manually - run \`pnpm schema:codegen\` to regenerate.
 */

${exports.map((name) => `export * from './${name}';`).join('\n')}
`;

async function compileTopic(topic) {
  const { schemaDir, schemaFile, topicName, outputFile, benignLabels } = topic;
  const schemaPath = join(SCHEMA_ROOT, schemaDir, schemaFile);
  const outputDir = join(OUTPUT_ROOT, schemaDir);

  console.log(`\n🔧 Compiling ${schemaDir} (${schemaFile})...`);
  const schema = JSON.parse(await readFile(schemaPath, 'utf-8'));
  const body = await compile(schema, topicName, {
    bannerComment: '',
    additionalProperties: false,
  });

  await mkdir(outputDir, { recursive: true });
  await writeFile(
    join(outputDir, outputFile),
    bannerFor(outputFile, schemaDir, schemaFile) + '\n' + body
  );

  const barrelExports = [outputFile.replace(/\.ts$/, '')];

  if (benignLabels) {
    console.log(`🔧 Emitting ${schemaDir} benign-label constant...`);
    const benignLabelsPath = join(SCHEMA_ROOT, schemaDir, 'benign_labels.json');
    const benignLabelsJson = JSON.parse(
      await readFile(benignLabelsPath, 'utf-8')
    );
    const benignLabelsBody = `/**
 * ${benignLabelsJson.$comment}
 */
export const BENIGN_LABELS = ${JSON.stringify(benignLabelsJson.labels)} as const;
`;

    await writeFile(
      join(outputDir, 'benign_labels.ts'),
      bannerFor('this file', schemaDir, 'benign_labels.json') +
        '\n' +
        benignLabelsBody
    );
    barrelExports.push('benign_labels');
  }

  await writeFile(
    join(outputDir, 'index.ts'),
    barrelBannerFor(schemaDir, barrelExports)
  );

  return outputDir;
}

async function main() {
  console.log('🚀 Kafka Topic Schema Codegen (json-schema-to-typescript)');

  const outputDirs = [];
  for (const topic of TOPICS) {
    outputDirs.push(await compileTopic(topic));
  }

  console.log('\n💅 Formatting...');
  run(
    `pnpm exec prettier --write ${outputDirs.map((dir) => `"${dir}/**/*.ts"`).join(' ')}`
  );

  console.log('\n✨ Complete!\n');
}

main().catch((err) => {
  console.error('❌ Failed:', err);
  process.exit(1);
});
