/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */

import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

import type { Key } from 'swr';

import type {
  RulesCreateRuleRequest,
  RulesListRulesResponse,
  RulesRuleResponse,
} from './types';

export type listRulesResponse200 = {
  data: RulesListRulesResponse;
  status: 200;
};

export type listRulesResponse401 = {
  data: string;
  status: 401;
};

export type listRulesResponseSuccess = listRulesResponse200 & {
  headers: Headers;
};

export type listRulesResponseError = listRulesResponse401 & {
  headers: Headers;
};

export type listRulesResponse =
  | listRulesResponseSuccess
  | listRulesResponseError;

export const getListRulesUrl = () => {
  return `/api/pact/gateway/v1/rules`;
};

/**
 * @summary List policy rules
 */
export const listRules = async (
  options?: RequestInit
): Promise<listRulesResponse> => {
  const res = await fetch(getListRulesUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listRulesResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listRulesResponse;
};

export const getListRulesKey = () => [`/api/pact/gateway/v1/rules`] as const;

export type createRuleResponse201 = {
  data: RulesRuleResponse;
  status: 201;
};

export type createRuleResponse400 = {
  data: string;
  status: 400;
};

export type createRuleResponse401 = {
  data: string;
  status: 401;
};

export type createRuleResponseSuccess = createRuleResponse201 & {
  headers: Headers;
};

export type createRuleResponseError = (
  | createRuleResponse400
  | createRuleResponse401
) & {
  headers: Headers;
};

export type createRuleResponse =
  | createRuleResponseSuccess
  | createRuleResponseError;

export const getCreateRuleUrl = () => {
  return `/api/pact/gateway/v1/rules`;
};

/**
 * @summary Create a policy rule (Draft)
 */
export const createRule = async (
  rulesCreateRuleRequest: RulesCreateRuleRequest,
  options?: RequestInit
): Promise<createRuleResponse> => {
  const res = await fetch(getCreateRuleUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(rulesCreateRuleRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createRuleResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createRuleResponse;
};

export const getCreateRuleMutationFetcher = (options?: RequestInit) => {
  return (_: Key, { arg }: { arg: RulesCreateRuleRequest }) => {
    return createRule(arg, options);
  };
};

export const getCreateRuleMutationKey = () =>
  [`/api/pact/gateway/v1/rules`] as const;
