'use client';

/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr';
import useSWRMutation from 'swr/mutation';
import type { Arguments, Key, SWRConfiguration } from 'swr';
import type { SWRMutationConfiguration } from 'swr/mutation';

import type { AxiosError, AxiosRequestConfig } from 'axios';

import type {
  RulesCreateRuleRequest,
  RulesListRulesResponse,
  RulesRuleResponse,
} from './types';

import {
  listRulesResponse200,
  listRulesResponse401,
  listRulesResponseSuccess,
  listRulesResponseError,
  getListRulesUrl,
  listRulesResponse,
  listRules,
  getListRulesKey,
  createRuleResponse201,
  createRuleResponse400,
  createRuleResponse401,
  createRuleResponseSuccess,
  createRuleResponseError,
  getCreateRuleUrl,
  createRuleResponse,
  createRule,
  getCreateRuleMutationFetcher,
  getCreateRuleMutationKey,
  publishRuleResponse200,
  publishRuleResponse400,
  publishRuleResponse401,
  publishRuleResponse404,
  publishRuleResponseSuccess,
  publishRuleResponseError,
  getPublishRuleUrl,
  publishRuleResponse,
  publishRule,
  getPublishRuleMutationFetcher,
  getPublishRuleMutationKey,
  revokeRuleResponse200,
  revokeRuleResponse400,
  revokeRuleResponse401,
  revokeRuleResponse404,
  revokeRuleResponseSuccess,
  revokeRuleResponseError,
  getRevokeRuleUrl,
  revokeRuleResponse,
  revokeRule,
  getRevokeRuleMutationFetcher,
  getRevokeRuleMutationKey,
} from './fetchers';

export type ListRulesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listRules>>
>;

/**
 * @summary List policy rules
 */
export const useListRules = <TError = Promise<string>>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof listRules>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getListRulesKey() : null));
  const swrFn = () => listRules(fetchOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions
  );

  return {
    swrKey,
    ...query,
  };
};

export type CreateRuleMutationResult = NonNullable<
  Awaited<ReturnType<typeof createRule>>
>;

/**
 * @summary Create a policy rule (Draft)
 */
export const useCreateRule = <TError = Promise<string>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof createRule>>,
    TError,
    Key,
    RulesCreateRuleRequest,
    Awaited<ReturnType<typeof createRule>>
  > & { swrKey?: string };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getCreateRuleMutationKey();
  const swrFn = getCreateRuleMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type PublishRuleMutationResult = NonNullable<
  Awaited<ReturnType<typeof publishRule>>
>;

/**
 * @summary Publish a draft policy rule
 */
export const usePublishRule = <TError = Promise<string>>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof publishRule>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof publishRule>>
    > & { swrKey?: string };
    fetch?: RequestInit;
  }
) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPublishRuleMutationKey(id);
  const swrFn = getPublishRuleMutationFetcher(id, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type RevokeRuleMutationResult = NonNullable<
  Awaited<ReturnType<typeof revokeRule>>
>;

/**
 * @summary Revoke a published policy rule
 */
export const useRevokeRule = <TError = Promise<string>>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof revokeRule>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof revokeRule>>
    > & { swrKey?: string };
    fetch?: RequestInit;
  }
) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getRevokeRuleMutationKey(id);
  const swrFn = getRevokeRuleMutationFetcher(id, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
