'use client';

/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr';
import useSWRMutation from 'swr/mutation';
import type { Arguments, Key, SWRConfiguration } from 'swr';
import type { SWRMutationConfiguration } from 'swr/mutation';

import type {
  BoundaryErrorResponse,
  RulesCreateRuleRequest,
  RulesListRulesResponse,
  RulesRuleResponse,
  RulesUpdateRuleRequest,
} from './types';

import {
  listRulesResponse200,
  listRulesResponse401,
  listRulesResponse403,
  listRulesResponseSuccess,
  listRulesResponseError,
  getListRulesUrl,
  listRulesResponse,
  listRules,
  getListRulesKey,
  createRuleResponse201,
  createRuleResponse400,
  createRuleResponse401,
  createRuleResponse403,
  createRuleResponseSuccess,
  createRuleResponseError,
  getCreateRuleUrl,
  createRuleResponse,
  createRule,
  getCreateRuleMutationFetcher,
  getCreateRuleMutationKey,
  updateRuleResponse200,
  updateRuleResponse400,
  updateRuleResponse401,
  updateRuleResponse403,
  updateRuleResponse404,
  updateRuleResponseSuccess,
  updateRuleResponseError,
  getUpdateRuleUrl,
  updateRuleResponse,
  updateRule,
  getUpdateRuleMutationFetcher,
  getUpdateRuleMutationKey,
  publishRuleResponse200,
  publishRuleResponse400,
  publishRuleResponse401,
  publishRuleResponse403,
  publishRuleResponse404,
  publishRuleResponseSuccess,
  publishRuleResponseError,
  getPublishRuleUrl,
  publishRuleResponse,
  publishRule,
  getPublishRuleMutationFetcher,
  getPublishRuleMutationKey,
  revokeRuleResponse200,
  revokeRuleResponse400,
  revokeRuleResponse401,
  revokeRuleResponse403,
  revokeRuleResponse404,
  revokeRuleResponseSuccess,
  revokeRuleResponseError,
  getRevokeRuleUrl,
  revokeRuleResponse,
  revokeRule,
  getRevokeRuleMutationFetcher,
  getRevokeRuleMutationKey,
} from './fetchers';

import { customFetch } from '../custom_fetch';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type ListRulesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listRules>>
>;

/**
 * @summary List policy rules
 */
export const useListRules = <TError = string>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof listRules>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getListRulesKey() : null));
  const swrFn = () => listRules(requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions
  );

  return {
    swrKey,
    ...query,
  };
};

export type CreateRuleMutationResult = NonNullable<
  Awaited<ReturnType<typeof createRule>>
>;

/**
 * @summary Create a policy rule (Draft)
 */
export const useCreateRule = <TError = string>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof createRule>>,
    TError,
    Key,
    RulesCreateRuleRequest,
    Awaited<ReturnType<typeof createRule>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getCreateRuleMutationKey();
  const swrFn = getCreateRuleMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type UpdateRuleMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateRule>>
>;

/**
 * @summary Update a draft policy rule
 */
export const useUpdateRule = <TError = string | BoundaryErrorResponse>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof updateRule>>,
      TError,
      Key,
      RulesUpdateRuleRequest,
      Awaited<ReturnType<typeof updateRule>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customFetch>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getUpdateRuleMutationKey(id);
  const swrFn = getUpdateRuleMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type PublishRuleMutationResult = NonNullable<
  Awaited<ReturnType<typeof publishRule>>
>;

/**
 * @summary Publish a policy rule
 */
export const usePublishRule = <TError = BoundaryErrorResponse | string>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof publishRule>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof publishRule>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customFetch>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPublishRuleMutationKey(id);
  const swrFn = getPublishRuleMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type RevokeRuleMutationResult = NonNullable<
  Awaited<ReturnType<typeof revokeRule>>
>;

/**
 * @summary Revoke a policy rule
 */
export const useRevokeRule = <TError = BoundaryErrorResponse | string>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof revokeRule>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof revokeRule>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customFetch>;
  }
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getRevokeRuleMutationKey(id);
  const swrFn = getRevokeRuleMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
