/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Feature Service
 * Feature flag management for PACT
 * OpenAPI spec version: 1.0.0
 */

import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

import type { Key } from 'swr';

import type { Feature, UpdateFeatureRequest } from './types';

export type getFeaturesResponse200 = {
  data: Feature[];
  status: 200;
};

export type getFeaturesResponseSuccess = getFeaturesResponse200 & {
  headers: Headers;
};

export type getFeaturesResponse = getFeaturesResponseSuccess;

export const getGetFeaturesUrl = () => {
  return `/api/pact/feature/features`;
};

/**
 * @summary List all feature flags
 */
export const getFeatures = async (
  options?: RequestInit
): Promise<getFeaturesResponse> => {
  const res = await fetch(getGetFeaturesUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getFeaturesResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getFeaturesResponse;
};

export const getGetFeaturesKey = () => [`/api/pact/feature/features`] as const;

export type updateFeatureResponse200 = {
  data: Feature;
  status: 200;
};

export type updateFeatureResponse404 = {
  data: void;
  status: 404;
};

export type updateFeatureResponseSuccess = updateFeatureResponse200 & {
  headers: Headers;
};

export type updateFeatureResponseError = updateFeatureResponse404 & {
  headers: Headers;
};

export type updateFeatureResponse =
  | updateFeatureResponseSuccess
  | updateFeatureResponseError;

export const getUpdateFeatureUrl = (id: string) => {
  return `/api/pact/feature/features/${id}`;
};

/**
 * @summary Update a feature flag's enabled state
 */
export const updateFeature = async (
  id: string,
  updateFeatureRequest: UpdateFeatureRequest,
  options?: RequestInit
): Promise<updateFeatureResponse> => {
  const res = await fetch(getUpdateFeatureUrl(id), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateFeatureRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateFeatureResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as updateFeatureResponse;
};

export const getUpdateFeatureMutationFetcher = (
  id: string,
  options?: RequestInit
) => {
  return (_: Key, { arg }: { arg: UpdateFeatureRequest }) => {
    return updateFeature(id, arg, options);
  };
};

export const getUpdateFeatureMutationKey = (id: string) =>
  [`/api/pact/feature/features/${id}`] as const;
