/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Feature Service
 * Feature flag management for PACT
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

import type { Key } from 'swr';

import type { Feature, UpdateFeatureRequest } from './types';

export const getFeatures = (
  options?: AxiosRequestConfig
): Promise<AxiosResponse<Feature[]>> => {
  return axios.get(`/api/pact/feature/features`, options);
};

export const getGetFeaturesKey = () => [`/api/pact/feature/features`] as const;

/**
 * @summary Update a feature flag's enabled state
 */
export const updateFeature = (
  id: string,
  updateFeatureRequest: UpdateFeatureRequest,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<Feature>> => {
  return axios.put(
    `/api/pact/feature/features/${id}`,
    updateFeatureRequest,
    options
  );
};

export const getUpdateFeatureMutationFetcher = (
  id: string,
  options?: AxiosRequestConfig
) => {
  return (_: Key, { arg }: { arg: UpdateFeatureRequest }) => {
    return updateFeature(id, arg, options);
  };
};

export const getUpdateFeatureMutationKey = (id: string) =>
  [`/api/pact/feature/features/${id}`] as const;
