'use client';

/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Feature Service
 * Feature flag management for PACT
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import useSWRMutation from 'swr/mutation';
import type { Key, SWRConfiguration } from 'swr';
import type { SWRMutationConfiguration } from 'swr/mutation';

import type { AxiosError, AxiosRequestConfig } from 'axios';

import type { Feature, UpdateFeatureRequest } from './types';

import {
  getFeatures,
  getGetFeaturesKey,
  updateFeature,
  getUpdateFeatureMutationFetcher,
  getUpdateFeatureMutationKey,
} from './fetchers';

export type GetFeaturesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFeatures>>
>;
export type GetFeaturesQueryError = AxiosError<unknown>;

/**
 * @summary List all feature flags
 */
export const useGetFeatures = <TError = AxiosError<unknown>>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof getFeatures>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  axios?: AxiosRequestConfig;
}) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetFeaturesKey() : null));
  const swrFn = () => getFeatures(axiosOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions
  );

  return {
    swrKey,
    ...query,
  };
};

export type UpdateFeatureMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateFeature>>
>;
export type UpdateFeatureMutationError = AxiosError<void>;

/**
 * @summary Update a feature flag's enabled state
 */
export const useUpdateFeature = <TError = AxiosError<void>>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof updateFeature>>,
      TError,
      Key,
      UpdateFeatureRequest,
      Awaited<ReturnType<typeof updateFeature>>
    > & { swrKey?: string };
    axios?: AxiosRequestConfig;
  }
) => {
  const { swr: swrOptions, axios: axiosOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getUpdateFeatureMutationKey(id);
  const swrFn = getUpdateFeatureMutationFetcher(id, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
