/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * Account Service
 * Profile, preferences, consents, and GDPR data-rights surface for the
 * signed-in user. Mounted on pact-gateway at /v1/account/*; the
 * gateway resolves the user_id from the session cookie before
 * proxying to pact-account over gRPC. The HTTP body never carries a
 * userId -- the gateway is the only authority on which user is
 * being acted on.
 *
 * OpenAPI spec version: 0.1.0
 */

import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

import type { Arguments, Key } from 'swr';

import type {
  BadRequestResponse,
  Consent,
  ConsentList,
  ErasureAcknowledgement,
  ExportAccountData200,
  Preferences,
  Profile,
  RecordConsentRequest,
  UnauthorizedResponse,
  UpdatePreferencesRequest,
  UpdateProfileRequest,
} from './types';

export type getAccountProfileResponse200 = {
  data: Profile;
  status: 200;
};

export type getAccountProfileResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type getAccountProfileResponseSuccess = getAccountProfileResponse200 & {
  headers: Headers;
};

export type getAccountProfileResponseError = getAccountProfileResponse401 & {
  headers: Headers;
};

export type getAccountProfileResponse =
  | getAccountProfileResponseSuccess
  | getAccountProfileResponseError;

export const getGetAccountProfileUrl = () => {
  return `/v1/account/profile`;
};

/**
 * @summary Get the signed-in user's profile
 */
export const getAccountProfile = async (
  options?: RequestInit
): Promise<getAccountProfileResponse> => {
  const res = await fetch(getGetAccountProfileUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getAccountProfileResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getAccountProfileResponse;
};

export const getGetAccountProfileKey = () => [`/v1/account/profile`] as const;

export type updateAccountProfileResponse200 = {
  data: Profile;
  status: 200;
};

export type updateAccountProfileResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type updateAccountProfileResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type updateAccountProfileResponseSuccess =
  updateAccountProfileResponse200 & {
    headers: Headers;
  };

export type updateAccountProfileResponseError = (
  | updateAccountProfileResponse400
  | updateAccountProfileResponse401
) & {
  headers: Headers;
};

export type updateAccountProfileResponse =
  | updateAccountProfileResponseSuccess
  | updateAccountProfileResponseError;

export const getUpdateAccountProfileUrl = () => {
  return `/v1/account/profile`;
};

/**
 * Patch semantics. updateMask lists the field names the caller
 * intends to write; unlisted fields keep their stored value.
 * Mask names are the proto field names (display_name, avatar_url,
 * locale, timezone, bio). Unknown mask entries fail with 400.
 *
 * @summary Patch the signed-in user's profile
 */
export const updateAccountProfile = async (
  updateProfileRequest: UpdateProfileRequest,
  options?: RequestInit
): Promise<updateAccountProfileResponse> => {
  const res = await fetch(getUpdateAccountProfileUrl(), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateProfileRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateAccountProfileResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as updateAccountProfileResponse;
};

export const getUpdateAccountProfileMutationFetcher = (
  options?: RequestInit
) => {
  return (_: Key, { arg }: { arg: UpdateProfileRequest }) => {
    return updateAccountProfile(arg, options);
  };
};

export const getUpdateAccountProfileMutationKey = () =>
  [`/v1/account/profile`] as const;

export type getAccountPreferencesResponse200 = {
  data: Preferences;
  status: 200;
};

export type getAccountPreferencesResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type getAccountPreferencesResponseSuccess =
  getAccountPreferencesResponse200 & {
    headers: Headers;
  };

export type getAccountPreferencesResponseError =
  getAccountPreferencesResponse401 & {
    headers: Headers;
  };

export type getAccountPreferencesResponse =
  | getAccountPreferencesResponseSuccess
  | getAccountPreferencesResponseError;

export const getGetAccountPreferencesUrl = () => {
  return `/v1/account/preferences`;
};

/**
 * @summary Get notification preferences
 */
export const getAccountPreferences = async (
  options?: RequestInit
): Promise<getAccountPreferencesResponse> => {
  const res = await fetch(getGetAccountPreferencesUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getAccountPreferencesResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getAccountPreferencesResponse;
};

export const getGetAccountPreferencesKey = () =>
  [`/v1/account/preferences`] as const;

export type updateAccountPreferencesResponse200 = {
  data: Preferences;
  status: 200;
};

export type updateAccountPreferencesResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type updateAccountPreferencesResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type updateAccountPreferencesResponseSuccess =
  updateAccountPreferencesResponse200 & {
    headers: Headers;
  };

export type updateAccountPreferencesResponseError = (
  | updateAccountPreferencesResponse400
  | updateAccountPreferencesResponse401
) & {
  headers: Headers;
};

export type updateAccountPreferencesResponse =
  | updateAccountPreferencesResponseSuccess
  | updateAccountPreferencesResponseError;

export const getUpdateAccountPreferencesUrl = () => {
  return `/v1/account/preferences`;
};

/**
 * Patch semantics, same shape as updateProfile. Mask names:
 * marketing_email, product_email.
 *
 * @summary Patch notification preferences
 */
export const updateAccountPreferences = async (
  updatePreferencesRequest: UpdatePreferencesRequest,
  options?: RequestInit
): Promise<updateAccountPreferencesResponse> => {
  const res = await fetch(getUpdateAccountPreferencesUrl(), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updatePreferencesRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateAccountPreferencesResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as updateAccountPreferencesResponse;
};

export const getUpdateAccountPreferencesMutationFetcher = (
  options?: RequestInit
) => {
  return (_: Key, { arg }: { arg: UpdatePreferencesRequest }) => {
    return updateAccountPreferences(arg, options);
  };
};

export const getUpdateAccountPreferencesMutationKey = () =>
  [`/v1/account/preferences`] as const;

export type getAccountConsentsResponse200 = {
  data: ConsentList;
  status: 200;
};

export type getAccountConsentsResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type getAccountConsentsResponseSuccess =
  getAccountConsentsResponse200 & {
    headers: Headers;
  };

export type getAccountConsentsResponseError = getAccountConsentsResponse401 & {
  headers: Headers;
};

export type getAccountConsentsResponse =
  | getAccountConsentsResponseSuccess
  | getAccountConsentsResponseError;

export const getGetAccountConsentsUrl = () => {
  return `/v1/account/consents`;
};

/**
 * Returns one entry per document (e.g. terms_of_service,
 * privacy_policy, marketing_email). Older versions remain in the
 * consents table as Art. 7 evidence but aren't surfaced here.
 *
 * @summary List the latest consent decision per document
 */
export const getAccountConsents = async (
  options?: RequestInit
): Promise<getAccountConsentsResponse> => {
  const res = await fetch(getGetAccountConsentsUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getAccountConsentsResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getAccountConsentsResponse;
};

export const getGetAccountConsentsKey = () => [`/v1/account/consents`] as const;

export type recordAccountConsentResponse201 = {
  data: Consent;
  status: 201;
};

export type recordAccountConsentResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type recordAccountConsentResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type recordAccountConsentResponseSuccess =
  recordAccountConsentResponse201 & {
    headers: Headers;
  };

export type recordAccountConsentResponseError = (
  | recordAccountConsentResponse400
  | recordAccountConsentResponse401
) & {
  headers: Headers;
};

export type recordAccountConsentResponse =
  | recordAccountConsentResponseSuccess
  | recordAccountConsentResponseError;

export const getRecordAccountConsentUrl = () => {
  return `/v1/account/consents`;
};

/**
 * The (document, version) pair is the legal claim of what the
 * user agreed to. The IP and User-Agent evidence (Art. 7(1))
 * come from the inbound HTTP request and are stored verbatim on
 * the gateway side -- the SPA must not include them in the body.
 *
 * @summary Record a consent decision
 */
export const recordAccountConsent = async (
  recordConsentRequest: RecordConsentRequest,
  options?: RequestInit
): Promise<recordAccountConsentResponse> => {
  const res = await fetch(getRecordAccountConsentUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(recordConsentRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: recordAccountConsentResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as recordAccountConsentResponse;
};

export const getRecordAccountConsentMutationFetcher = (
  options?: RequestInit
) => {
  return (_: Key, { arg }: { arg: RecordConsentRequest }) => {
    return recordAccountConsent(arg, options);
  };
};

export const getRecordAccountConsentMutationKey = () =>
  [`/v1/account/consents`] as const;

export type exportAccountDataResponse200 = {
  data: ExportAccountData200;
  status: 200;
};

export type exportAccountDataResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type exportAccountDataResponseSuccess = exportAccountDataResponse200 & {
  headers: Headers;
};

export type exportAccountDataResponseError = exportAccountDataResponse401 & {
  headers: Headers;
};

export type exportAccountDataResponse =
  | exportAccountDataResponseSuccess
  | exportAccountDataResponseError;

export const getExportAccountDataUrl = () => {
  return `/v1/account/export`;
};

/**
 * v0 returns the JSON payload inline. The roadmap calls out an
 * async "request export -> email a link" flow for v0.1; this
 * endpoint will keep working as the synchronous fallback while
 * the async path lands at a separate POST endpoint, so callers
 * don't need to be migrated.
 *
 * @summary Export pact-account-owned data for the signed-in user (GDPR Art. 15)
 */
export const exportAccountData = async (
  options?: RequestInit
): Promise<exportAccountDataResponse> => {
  const res = await fetch(getExportAccountDataUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: exportAccountDataResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as exportAccountDataResponse;
};

export const getExportAccountDataKey = () => [`/v1/account/export`] as const;

export type requestAccountErasureResponse202 = {
  data: ErasureAcknowledgement;
  status: 202;
};

export type requestAccountErasureResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type requestAccountErasureResponseSuccess =
  requestAccountErasureResponse202 & {
    headers: Headers;
  };

export type requestAccountErasureResponseError =
  requestAccountErasureResponse401 & {
    headers: Headers;
  };

export type requestAccountErasureResponse =
  | requestAccountErasureResponseSuccess
  | requestAccountErasureResponseError;

export const getRequestAccountErasureUrl = () => {
  return `/v1/account/erasure`;
};

/**
 * Records the request, deletes pact-account-owned rows, and
 * emits a pact.account.user_erasure_requested Kafka event so
 * downstream services can run their own cascade. Returns 202 --
 * cross-service completion is async and not orchestrated in v0.
 *
 * @summary Request erasure of the signed-in user's data (GDPR Art. 17)
 */
export const requestAccountErasure = async (
  options?: RequestInit
): Promise<requestAccountErasureResponse> => {
  const res = await fetch(getRequestAccountErasureUrl(), {
    ...options,
    method: 'POST',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: requestAccountErasureResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as requestAccountErasureResponse;
};

export const getRequestAccountErasureMutationFetcher = (
  options?: RequestInit
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return requestAccountErasure(options);
  };
};

export const getRequestAccountErasureMutationKey = () =>
  [`/v1/account/erasure`] as const;
