/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */

import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

import type { Arguments, Key } from 'swr';

import type {
  AccountConsentResponse,
  AccountConsentsResponse,
  AccountErasureResponse,
  AccountPreferencesResponse,
  AccountProfileResponse,
  AccountRecordConsentRequest,
  AccountUpdatePreferencesRequest,
  AccountUpdateProfileRequest,
} from './types';

export type getAccountConsentsResponse200 = {
  data: AccountConsentsResponse;
  status: 200;
};

export type getAccountConsentsResponse401 = {
  data: string;
  status: 401;
};

export type getAccountConsentsResponseSuccess =
  getAccountConsentsResponse200 & {
    headers: Headers;
  };

export type getAccountConsentsResponseError = getAccountConsentsResponse401 & {
  headers: Headers;
};

export type getAccountConsentsResponse =
  | getAccountConsentsResponseSuccess
  | getAccountConsentsResponseError;

export const getGetAccountConsentsUrl = () => {
  return `/api/pact/gateway/v1/account/consents`;
};

/**
 * @summary List the latest consent decision per document
 */
export const getAccountConsents = async (
  options?: RequestInit
): Promise<getAccountConsentsResponse> => {
  const res = await fetch(getGetAccountConsentsUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getAccountConsentsResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getAccountConsentsResponse;
};

export const getGetAccountConsentsKey = () =>
  [`/api/pact/gateway/v1/account/consents`] as const;

export type postAccountConsentsResponse201 = {
  data: AccountConsentResponse;
  status: 201;
};

export type postAccountConsentsResponse400 = {
  data: string;
  status: 400;
};

export type postAccountConsentsResponse401 = {
  data: string;
  status: 401;
};

export type postAccountConsentsResponseSuccess =
  postAccountConsentsResponse201 & {
    headers: Headers;
  };

export type postAccountConsentsResponseError = (
  | postAccountConsentsResponse400
  | postAccountConsentsResponse401
) & {
  headers: Headers;
};

export type postAccountConsentsResponse =
  | postAccountConsentsResponseSuccess
  | postAccountConsentsResponseError;

export const getPostAccountConsentsUrl = () => {
  return `/api/pact/gateway/v1/account/consents`;
};

/**
 * @summary Record a consent decision (Art. 7 evidence)
 */
export const postAccountConsents = async (
  accountRecordConsentRequest: AccountRecordConsentRequest,
  options?: RequestInit
): Promise<postAccountConsentsResponse> => {
  const res = await fetch(getPostAccountConsentsUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(accountRecordConsentRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postAccountConsentsResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postAccountConsentsResponse;
};

export const getPostAccountConsentsMutationFetcher = (
  options?: RequestInit
) => {
  return (_: Key, { arg }: { arg: AccountRecordConsentRequest }) => {
    return postAccountConsents(arg, options);
  };
};

export const getPostAccountConsentsMutationKey = () =>
  [`/api/pact/gateway/v1/account/consents`] as const;

export type postAccountErasureResponse202 = {
  data: AccountErasureResponse;
  status: 202;
};

export type postAccountErasureResponse401 = {
  data: string;
  status: 401;
};

export type postAccountErasureResponseSuccess =
  postAccountErasureResponse202 & {
    headers: Headers;
  };

export type postAccountErasureResponseError = postAccountErasureResponse401 & {
  headers: Headers;
};

export type postAccountErasureResponse =
  | postAccountErasureResponseSuccess
  | postAccountErasureResponseError;

export const getPostAccountErasureUrl = () => {
  return `/api/pact/gateway/v1/account/erasure`;
};

/**
 * @summary Request erasure of the signed-in user's data (GDPR Art. 17)
 */
export const postAccountErasure = async (
  options?: RequestInit
): Promise<postAccountErasureResponse> => {
  const res = await fetch(getPostAccountErasureUrl(), {
    ...options,
    method: 'POST',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postAccountErasureResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postAccountErasureResponse;
};

export const getPostAccountErasureMutationFetcher = (options?: RequestInit) => {
  return (_: Key, __: { arg: Arguments }) => {
    return postAccountErasure(options);
  };
};

export const getPostAccountErasureMutationKey = () =>
  [`/api/pact/gateway/v1/account/erasure`] as const;

export type getAccountExportResponse200 = {
  data: void;
  status: 200;
};

export type getAccountExportResponse401 = {
  data: string;
  status: 401;
};

export type getAccountExportResponseSuccess = getAccountExportResponse200 & {
  headers: Headers;
};

export type getAccountExportResponseError = getAccountExportResponse401 & {
  headers: Headers;
};

export type getAccountExportResponse =
  | getAccountExportResponseSuccess
  | getAccountExportResponseError;

export const getGetAccountExportUrl = () => {
  return `/api/pact/gateway/v1/account/export`;
};

/**
 * @summary Export pact-account-owned data (GDPR Art. 15)
 */
export const getAccountExport = async (
  options?: RequestInit
): Promise<getAccountExportResponse> => {
  const res = await fetch(getGetAccountExportUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getAccountExportResponse['data'] = body
    ? JSON.parse(body)
    : undefined;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getAccountExportResponse;
};

export const getGetAccountExportKey = () =>
  [`/api/pact/gateway/v1/account/export`] as const;

export type getAccountPreferencesResponse200 = {
  data: AccountPreferencesResponse;
  status: 200;
};

export type getAccountPreferencesResponse401 = {
  data: string;
  status: 401;
};

export type getAccountPreferencesResponseSuccess =
  getAccountPreferencesResponse200 & {
    headers: Headers;
  };

export type getAccountPreferencesResponseError =
  getAccountPreferencesResponse401 & {
    headers: Headers;
  };

export type getAccountPreferencesResponse =
  | getAccountPreferencesResponseSuccess
  | getAccountPreferencesResponseError;

export const getGetAccountPreferencesUrl = () => {
  return `/api/pact/gateway/v1/account/preferences`;
};

/**
 * @summary Get notification preferences
 */
export const getAccountPreferences = async (
  options?: RequestInit
): Promise<getAccountPreferencesResponse> => {
  const res = await fetch(getGetAccountPreferencesUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getAccountPreferencesResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getAccountPreferencesResponse;
};

export const getGetAccountPreferencesKey = () =>
  [`/api/pact/gateway/v1/account/preferences`] as const;

export type putAccountPreferencesResponse200 = {
  data: AccountPreferencesResponse;
  status: 200;
};

export type putAccountPreferencesResponse400 = {
  data: string;
  status: 400;
};

export type putAccountPreferencesResponse401 = {
  data: string;
  status: 401;
};

export type putAccountPreferencesResponseSuccess =
  putAccountPreferencesResponse200 & {
    headers: Headers;
  };

export type putAccountPreferencesResponseError = (
  | putAccountPreferencesResponse400
  | putAccountPreferencesResponse401
) & {
  headers: Headers;
};

export type putAccountPreferencesResponse =
  | putAccountPreferencesResponseSuccess
  | putAccountPreferencesResponseError;

export const getPutAccountPreferencesUrl = () => {
  return `/api/pact/gateway/v1/account/preferences`;
};

/**
 * @summary Patch notification preferences (mask semantics)
 */
export const putAccountPreferences = async (
  accountUpdatePreferencesRequest: AccountUpdatePreferencesRequest,
  options?: RequestInit
): Promise<putAccountPreferencesResponse> => {
  const res = await fetch(getPutAccountPreferencesUrl(), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(accountUpdatePreferencesRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: putAccountPreferencesResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as putAccountPreferencesResponse;
};

export const getPutAccountPreferencesMutationFetcher = (
  options?: RequestInit
) => {
  return (_: Key, { arg }: { arg: AccountUpdatePreferencesRequest }) => {
    return putAccountPreferences(arg, options);
  };
};

export const getPutAccountPreferencesMutationKey = () =>
  [`/api/pact/gateway/v1/account/preferences`] as const;

export type getAccountProfileResponse200 = {
  data: AccountProfileResponse;
  status: 200;
};

export type getAccountProfileResponse401 = {
  data: string;
  status: 401;
};

export type getAccountProfileResponseSuccess = getAccountProfileResponse200 & {
  headers: Headers;
};

export type getAccountProfileResponseError = getAccountProfileResponse401 & {
  headers: Headers;
};

export type getAccountProfileResponse =
  | getAccountProfileResponseSuccess
  | getAccountProfileResponseError;

export const getGetAccountProfileUrl = () => {
  return `/api/pact/gateway/v1/account/profile`;
};

/**
 * @summary Get the signed-in user's profile
 */
export const getAccountProfile = async (
  options?: RequestInit
): Promise<getAccountProfileResponse> => {
  const res = await fetch(getGetAccountProfileUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getAccountProfileResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getAccountProfileResponse;
};

export const getGetAccountProfileKey = () =>
  [`/api/pact/gateway/v1/account/profile`] as const;

export type putAccountProfileResponse200 = {
  data: AccountProfileResponse;
  status: 200;
};

export type putAccountProfileResponse400 = {
  data: string;
  status: 400;
};

export type putAccountProfileResponse401 = {
  data: string;
  status: 401;
};

export type putAccountProfileResponseSuccess = putAccountProfileResponse200 & {
  headers: Headers;
};

export type putAccountProfileResponseError = (
  | putAccountProfileResponse400
  | putAccountProfileResponse401
) & {
  headers: Headers;
};

export type putAccountProfileResponse =
  | putAccountProfileResponseSuccess
  | putAccountProfileResponseError;

export const getPutAccountProfileUrl = () => {
  return `/api/pact/gateway/v1/account/profile`;
};

/**
 * @summary Patch the signed-in user's profile (mask semantics)
 */
export const putAccountProfile = async (
  accountUpdateProfileRequest: AccountUpdateProfileRequest,
  options?: RequestInit
): Promise<putAccountProfileResponse> => {
  const res = await fetch(getPutAccountProfileUrl(), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(accountUpdateProfileRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: putAccountProfileResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as putAccountProfileResponse;
};

export const getPutAccountProfileMutationFetcher = (options?: RequestInit) => {
  return (_: Key, { arg }: { arg: AccountUpdateProfileRequest }) => {
    return putAccountProfile(arg, options);
  };
};

export const getPutAccountProfileMutationKey = () =>
  [`/api/pact/gateway/v1/account/profile`] as const;
