/**
 * Generated by orval 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */

import type { Arguments, Key } from 'swr';

import type {
  AccountConsentResponse,
  AccountConsentsResponse,
  AccountErasureResponse,
  AccountPreferencesResponse,
  AccountProfileResponse,
  AccountRecordConsentRequest,
  AccountUpdatePreferencesRequest,
  AccountUpdateProfileRequest,
  BoundaryErrorResponse,
} from './types';

import { customFetch } from '../custom_fetch';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type getAccountConsentsResponse200 = {
  data: AccountConsentsResponse;
  status: 200;
};

export type getAccountConsentsResponse401 = {
  data: string;
  status: 401;
};

export type getAccountConsentsResponseSuccess =
  getAccountConsentsResponse200 & {
    headers: Headers;
  };

export type getAccountConsentsResponseError = getAccountConsentsResponse401 & {
  headers: Headers;
};

export type getAccountConsentsResponse =
  getAccountConsentsResponseSuccess | getAccountConsentsResponseError;

export const getGetAccountConsentsUrl = () => {
  return `/api/pact/gateway/v1/account/consents`;
};

/**
 * @summary List the latest consent decision per document
 */
export const getAccountConsents = async (
  options?: Parameters<typeof customFetch>[1]
): Promise<getAccountConsentsResponse> => {
  return customFetch<getAccountConsentsResponse>(getGetAccountConsentsUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getGetAccountConsentsKey = () =>
  [`/api/pact/gateway/v1/account/consents`] as const;

export type postAccountConsentsResponse201 = {
  data: AccountConsentResponse;
  status: 201;
};

export type postAccountConsentsResponse400 = {
  data: BoundaryErrorResponse;
  status: 400;
};

export type postAccountConsentsResponse401 = {
  data: string;
  status: 401;
};

export type postAccountConsentsResponseSuccess =
  postAccountConsentsResponse201 & {
    headers: Headers;
  };

export type postAccountConsentsResponseError = (
  postAccountConsentsResponse400 | postAccountConsentsResponse401
) & {
  headers: Headers;
};

export type postAccountConsentsResponse =
  postAccountConsentsResponseSuccess | postAccountConsentsResponseError;

export const getPostAccountConsentsUrl = () => {
  return `/api/pact/gateway/v1/account/consents`;
};

/**
 * @summary Record a consent decision (Art. 7 evidence)
 */
export const postAccountConsents = async (
  accountRecordConsentRequest: AccountRecordConsentRequest,
  options?: Parameters<typeof customFetch>[1]
): Promise<postAccountConsentsResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
  return customFetch<postAccountConsentsResponse>(getPostAccountConsentsUrl(), {
    ...options,
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(accountRecordConsentRequest),
  });
};

export const getPostAccountConsentsMutationFetcher = (
  options?: SecondParameter<typeof customFetch>
) => {
  return (_: Key, { arg }: { arg: AccountRecordConsentRequest }) => {
    return postAccountConsents(arg, options);
  };
};

export const getPostAccountConsentsMutationKey = () =>
  [`/api/pact/gateway/v1/account/consents`] as const;

export type postAccountErasureResponse202 = {
  data: AccountErasureResponse;
  status: 202;
};

export type postAccountErasureResponse401 = {
  data: string;
  status: 401;
};

export type postAccountErasureResponseSuccess =
  postAccountErasureResponse202 & {
    headers: Headers;
  };

export type postAccountErasureResponseError = postAccountErasureResponse401 & {
  headers: Headers;
};

export type postAccountErasureResponse =
  postAccountErasureResponseSuccess | postAccountErasureResponseError;

export const getPostAccountErasureUrl = () => {
  return `/api/pact/gateway/v1/account/erasure`;
};

/**
 * @summary Request erasure of the signed-in user's data (GDPR Art. 17)
 */
export const postAccountErasure = async (
  options?: Parameters<typeof customFetch>[1]
): Promise<postAccountErasureResponse> => {
  return customFetch<postAccountErasureResponse>(getPostAccountErasureUrl(), {
    ...options,
    method: 'POST',
  });
};

export const getPostAccountErasureMutationFetcher = (
  options?: SecondParameter<typeof customFetch>
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return postAccountErasure(options);
  };
};

export const getPostAccountErasureMutationKey = () =>
  [`/api/pact/gateway/v1/account/erasure`] as const;

export type getAccountExportResponse200 = {
  data: void;
  status: 200;
};

export type getAccountExportResponse401 = {
  data: string;
  status: 401;
};

export type getAccountExportResponseSuccess = getAccountExportResponse200 & {
  headers: Headers;
};

export type getAccountExportResponseError = getAccountExportResponse401 & {
  headers: Headers;
};

export type getAccountExportResponse =
  getAccountExportResponseSuccess | getAccountExportResponseError;

export const getGetAccountExportUrl = () => {
  return `/api/pact/gateway/v1/account/export`;
};

/**
 * @summary Export pact-account-owned data (GDPR Art. 15)
 */
export const getAccountExport = async (
  options?: Parameters<typeof customFetch>[1]
): Promise<getAccountExportResponse> => {
  return customFetch<getAccountExportResponse>(getGetAccountExportUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getGetAccountExportKey = () =>
  [`/api/pact/gateway/v1/account/export`] as const;

export type getAccountPreferencesResponse200 = {
  data: AccountPreferencesResponse;
  status: 200;
};

export type getAccountPreferencesResponse401 = {
  data: string;
  status: 401;
};

export type getAccountPreferencesResponseSuccess =
  getAccountPreferencesResponse200 & {
    headers: Headers;
  };

export type getAccountPreferencesResponseError =
  getAccountPreferencesResponse401 & {
    headers: Headers;
  };

export type getAccountPreferencesResponse =
  getAccountPreferencesResponseSuccess | getAccountPreferencesResponseError;

export const getGetAccountPreferencesUrl = () => {
  return `/api/pact/gateway/v1/account/preferences`;
};

/**
 * @summary Get notification preferences
 */
export const getAccountPreferences = async (
  options?: Parameters<typeof customFetch>[1]
): Promise<getAccountPreferencesResponse> => {
  return customFetch<getAccountPreferencesResponse>(
    getGetAccountPreferencesUrl(),
    {
      ...options,
      method: 'GET',
    }
  );
};

export const getGetAccountPreferencesKey = () =>
  [`/api/pact/gateway/v1/account/preferences`] as const;

export type putAccountPreferencesResponse200 = {
  data: AccountPreferencesResponse;
  status: 200;
};

export type putAccountPreferencesResponse400 = {
  data: BoundaryErrorResponse;
  status: 400;
};

export type putAccountPreferencesResponse401 = {
  data: string;
  status: 401;
};

export type putAccountPreferencesResponseSuccess =
  putAccountPreferencesResponse200 & {
    headers: Headers;
  };

export type putAccountPreferencesResponseError = (
  putAccountPreferencesResponse400 | putAccountPreferencesResponse401
) & {
  headers: Headers;
};

export type putAccountPreferencesResponse =
  putAccountPreferencesResponseSuccess | putAccountPreferencesResponseError;

export const getPutAccountPreferencesUrl = () => {
  return `/api/pact/gateway/v1/account/preferences`;
};

/**
 * @summary Patch notification preferences (mask semantics)
 */
export const putAccountPreferences = async (
  accountUpdatePreferencesRequest: AccountUpdatePreferencesRequest,
  options?: Parameters<typeof customFetch>[1]
): Promise<putAccountPreferencesResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
  return customFetch<putAccountPreferencesResponse>(
    getPutAccountPreferencesUrl(),
    {
      ...options,
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
        ...getHeaders(options?.headers),
      },
      body: JSON.stringify(accountUpdatePreferencesRequest),
    }
  );
};

export const getPutAccountPreferencesMutationFetcher = (
  options?: SecondParameter<typeof customFetch>
) => {
  return (_: Key, { arg }: { arg: AccountUpdatePreferencesRequest }) => {
    return putAccountPreferences(arg, options);
  };
};

export const getPutAccountPreferencesMutationKey = () =>
  [`/api/pact/gateway/v1/account/preferences`] as const;

export type getAccountProfileResponse200 = {
  data: AccountProfileResponse;
  status: 200;
};

export type getAccountProfileResponse401 = {
  data: string;
  status: 401;
};

export type getAccountProfileResponseSuccess = getAccountProfileResponse200 & {
  headers: Headers;
};

export type getAccountProfileResponseError = getAccountProfileResponse401 & {
  headers: Headers;
};

export type getAccountProfileResponse =
  getAccountProfileResponseSuccess | getAccountProfileResponseError;

export const getGetAccountProfileUrl = () => {
  return `/api/pact/gateway/v1/account/profile`;
};

/**
 * @summary Get the signed-in user's profile
 */
export const getAccountProfile = async (
  options?: Parameters<typeof customFetch>[1]
): Promise<getAccountProfileResponse> => {
  return customFetch<getAccountProfileResponse>(getGetAccountProfileUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getGetAccountProfileKey = () =>
  [`/api/pact/gateway/v1/account/profile`] as const;

export type putAccountProfileResponse200 = {
  data: AccountProfileResponse;
  status: 200;
};

export type putAccountProfileResponse400 = {
  data: BoundaryErrorResponse;
  status: 400;
};

export type putAccountProfileResponse401 = {
  data: string;
  status: 401;
};

export type putAccountProfileResponseSuccess = putAccountProfileResponse200 & {
  headers: Headers;
};

export type putAccountProfileResponseError = (
  putAccountProfileResponse400 | putAccountProfileResponse401
) & {
  headers: Headers;
};

export type putAccountProfileResponse =
  putAccountProfileResponseSuccess | putAccountProfileResponseError;

export const getPutAccountProfileUrl = () => {
  return `/api/pact/gateway/v1/account/profile`;
};

/**
 * @summary Patch the signed-in user's profile (mask semantics)
 */
export const putAccountProfile = async (
  accountUpdateProfileRequest: AccountUpdateProfileRequest,
  options?: Parameters<typeof customFetch>[1]
): Promise<putAccountProfileResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
  return customFetch<putAccountProfileResponse>(getPutAccountProfileUrl(), {
    ...options,
    method: 'PUT',
    headers: {
      'Content-Type': 'application/json',
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(accountUpdateProfileRequest),
  });
};

export const getPutAccountProfileMutationFetcher = (
  options?: SecondParameter<typeof customFetch>
) => {
  return (_: Key, { arg }: { arg: AccountUpdateProfileRequest }) => {
    return putAccountProfile(arg, options);
  };
};

export const getPutAccountProfileMutationKey = () =>
  [`/api/pact/gateway/v1/account/profile`] as const;
