'use client';

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr';
import useSWRMutation from 'swr/mutation';
import type { Arguments, Key, SWRConfiguration } from 'swr';
import type { SWRMutationConfiguration } from 'swr/mutation';

import type {
  AccountConsentResponse,
  AccountConsentsResponse,
  AccountErasureResponse,
  AccountPreferencesResponse,
  AccountProfileResponse,
  AccountRecordConsentRequest,
  AccountUpdatePreferencesRequest,
  AccountUpdateProfileRequest,
  BoundaryErrorResponse,
} from './types';

import {
  getAccountConsentsResponse200,
  getAccountConsentsResponse401,
  getAccountConsentsResponseSuccess,
  getAccountConsentsResponseError,
  getGetAccountConsentsUrl,
  getAccountConsentsResponse,
  getAccountConsents,
  getGetAccountConsentsKey,
  postAccountConsentsResponse201,
  postAccountConsentsResponse400,
  postAccountConsentsResponse401,
  postAccountConsentsResponseSuccess,
  postAccountConsentsResponseError,
  getPostAccountConsentsUrl,
  postAccountConsentsResponse,
  postAccountConsents,
  getPostAccountConsentsMutationFetcher,
  getPostAccountConsentsMutationKey,
  postAccountErasureResponse202,
  postAccountErasureResponse401,
  postAccountErasureResponseSuccess,
  postAccountErasureResponseError,
  getPostAccountErasureUrl,
  postAccountErasureResponse,
  postAccountErasure,
  getPostAccountErasureMutationFetcher,
  getPostAccountErasureMutationKey,
  getAccountExportResponse200,
  getAccountExportResponse401,
  getAccountExportResponseSuccess,
  getAccountExportResponseError,
  getGetAccountExportUrl,
  getAccountExportResponse,
  getAccountExport,
  getGetAccountExportKey,
  getAccountPreferencesResponse200,
  getAccountPreferencesResponse401,
  getAccountPreferencesResponseSuccess,
  getAccountPreferencesResponseError,
  getGetAccountPreferencesUrl,
  getAccountPreferencesResponse,
  getAccountPreferences,
  getGetAccountPreferencesKey,
  putAccountPreferencesResponse200,
  putAccountPreferencesResponse400,
  putAccountPreferencesResponse401,
  putAccountPreferencesResponseSuccess,
  putAccountPreferencesResponseError,
  getPutAccountPreferencesUrl,
  putAccountPreferencesResponse,
  putAccountPreferences,
  getPutAccountPreferencesMutationFetcher,
  getPutAccountPreferencesMutationKey,
  getAccountProfileResponse200,
  getAccountProfileResponse401,
  getAccountProfileResponseSuccess,
  getAccountProfileResponseError,
  getGetAccountProfileUrl,
  getAccountProfileResponse,
  getAccountProfile,
  getGetAccountProfileKey,
  putAccountProfileResponse200,
  putAccountProfileResponse400,
  putAccountProfileResponse401,
  putAccountProfileResponseSuccess,
  putAccountProfileResponseError,
  getPutAccountProfileUrl,
  putAccountProfileResponse,
  putAccountProfile,
  getPutAccountProfileMutationFetcher,
  getPutAccountProfileMutationKey,
} from './fetchers';

import { customFetch } from '../custom_fetch';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type GetAccountConsentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAccountConsents>>
>;

/**
 * @summary List the latest consent decision per document
 */
export const useGetAccountConsents = <TError = string>(options?: {
  swr?: SWRConfiguration<
    Awaited<ReturnType<typeof getAccountConsents>>,
    TError
  > & { swrKey?: Key; enabled?: boolean };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getGetAccountConsentsKey() : null));
  const swrFn = () => getAccountConsents(requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions
  );

  return {
    swrKey,
    ...query,
  };
};

export type PostAccountConsentsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAccountConsents>>
>;

/**
 * @summary Record a consent decision (Art. 7 evidence)
 */
export const usePostAccountConsents = <
  TError = BoundaryErrorResponse | string,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postAccountConsents>>,
    TError,
    Key,
    AccountRecordConsentRequest,
    Awaited<ReturnType<typeof postAccountConsents>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostAccountConsentsMutationKey();
  const swrFn = getPostAccountConsentsMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type PostAccountErasureMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAccountErasure>>
>;

/**
 * @summary Request erasure of the signed-in user's data (GDPR Art. 17)
 */
export const usePostAccountErasure = <TError = string>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postAccountErasure>>,
    TError,
    Key,
    Arguments,
    Awaited<ReturnType<typeof postAccountErasure>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostAccountErasureMutationKey();
  const swrFn = getPostAccountErasureMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type GetAccountExportQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAccountExport>>
>;

/**
 * @summary Export pact-account-owned data (GDPR Art. 15)
 */
export const useGetAccountExport = <TError = string>(options?: {
  swr?: SWRConfiguration<
    Awaited<ReturnType<typeof getAccountExport>>,
    TError
  > & { swrKey?: Key; enabled?: boolean };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetAccountExportKey() : null));
  const swrFn = () => getAccountExport(requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions
  );

  return {
    swrKey,
    ...query,
  };
};

export type GetAccountPreferencesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAccountPreferences>>
>;

/**
 * @summary Get notification preferences
 */
export const useGetAccountPreferences = <TError = string>(options?: {
  swr?: SWRConfiguration<
    Awaited<ReturnType<typeof getAccountPreferences>>,
    TError
  > & { swrKey?: Key; enabled?: boolean };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getGetAccountPreferencesKey() : null));
  const swrFn = () => getAccountPreferences(requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions
  );

  return {
    swrKey,
    ...query,
  };
};

export type PutAccountPreferencesMutationResult = NonNullable<
  Awaited<ReturnType<typeof putAccountPreferences>>
>;

/**
 * @summary Patch notification preferences (mask semantics)
 */
export const usePutAccountPreferences = <
  TError = BoundaryErrorResponse | string,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof putAccountPreferences>>,
    TError,
    Key,
    AccountUpdatePreferencesRequest,
    Awaited<ReturnType<typeof putAccountPreferences>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPutAccountPreferencesMutationKey();
  const swrFn = getPutAccountPreferencesMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type GetAccountProfileQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAccountProfile>>
>;

/**
 * @summary Get the signed-in user's profile
 */
export const useGetAccountProfile = <TError = string>(options?: {
  swr?: SWRConfiguration<
    Awaited<ReturnType<typeof getAccountProfile>>,
    TError
  > & { swrKey?: Key; enabled?: boolean };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getGetAccountProfileKey() : null));
  const swrFn = () => getAccountProfile(requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions
  );

  return {
    swrKey,
    ...query,
  };
};

export type PutAccountProfileMutationResult = NonNullable<
  Awaited<ReturnType<typeof putAccountProfile>>
>;

/**
 * @summary Patch the signed-in user's profile (mask semantics)
 */
export const usePutAccountProfile = <
  TError = BoundaryErrorResponse | string,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof putAccountProfile>>,
    TError,
    Key,
    AccountUpdateProfileRequest,
    Awaited<ReturnType<typeof putAccountProfile>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPutAccountProfileMutationKey();
  const swrFn = getPutAccountProfileMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
