'use client';

/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Account Service
 * Profile, preferences, consents, and GDPR data-rights surface for the
signed-in user. Mounted on pact-gateway at /v1/account/*; the
gateway resolves the user_id from the session cookie before
proxying to pact-account over gRPC. The HTTP body never carries a
userId -- the gateway is the only authority on which user is
being acted on.

 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr';
import useSWRMutation from 'swr/mutation';
import type { Arguments, Key, SWRConfiguration } from 'swr';
import type { SWRMutationConfiguration } from 'swr/mutation';

import type { AxiosError, AxiosRequestConfig } from 'axios';

import type {
  BadRequestResponse,
  Consent,
  ConsentList,
  ErasureAcknowledgement,
  ExportAccountData200,
  Preferences,
  Profile,
  RecordConsentRequest,
  UnauthorizedResponse,
  UpdatePreferencesRequest,
  UpdateProfileRequest,
} from './types';

import {
  getAccountProfileResponse200,
  getAccountProfileResponse401,
  getAccountProfileResponseSuccess,
  getAccountProfileResponseError,
  getGetAccountProfileUrl,
  getAccountProfileResponse,
  getAccountProfile,
  getGetAccountProfileKey,
  updateAccountProfileResponse200,
  updateAccountProfileResponse400,
  updateAccountProfileResponse401,
  updateAccountProfileResponseSuccess,
  updateAccountProfileResponseError,
  getUpdateAccountProfileUrl,
  updateAccountProfileResponse,
  updateAccountProfile,
  getUpdateAccountProfileMutationFetcher,
  getUpdateAccountProfileMutationKey,
  getAccountPreferencesResponse200,
  getAccountPreferencesResponse401,
  getAccountPreferencesResponseSuccess,
  getAccountPreferencesResponseError,
  getGetAccountPreferencesUrl,
  getAccountPreferencesResponse,
  getAccountPreferences,
  getGetAccountPreferencesKey,
  updateAccountPreferencesResponse200,
  updateAccountPreferencesResponse400,
  updateAccountPreferencesResponse401,
  updateAccountPreferencesResponseSuccess,
  updateAccountPreferencesResponseError,
  getUpdateAccountPreferencesUrl,
  updateAccountPreferencesResponse,
  updateAccountPreferences,
  getUpdateAccountPreferencesMutationFetcher,
  getUpdateAccountPreferencesMutationKey,
  getAccountConsentsResponse200,
  getAccountConsentsResponse401,
  getAccountConsentsResponseSuccess,
  getAccountConsentsResponseError,
  getGetAccountConsentsUrl,
  getAccountConsentsResponse,
  getAccountConsents,
  getGetAccountConsentsKey,
  recordAccountConsentResponse201,
  recordAccountConsentResponse400,
  recordAccountConsentResponse401,
  recordAccountConsentResponseSuccess,
  recordAccountConsentResponseError,
  getRecordAccountConsentUrl,
  recordAccountConsentResponse,
  recordAccountConsent,
  getRecordAccountConsentMutationFetcher,
  getRecordAccountConsentMutationKey,
  exportAccountDataResponse200,
  exportAccountDataResponse401,
  exportAccountDataResponseSuccess,
  exportAccountDataResponseError,
  getExportAccountDataUrl,
  exportAccountDataResponse,
  exportAccountData,
  getExportAccountDataKey,
  requestAccountErasureResponse202,
  requestAccountErasureResponse401,
  requestAccountErasureResponseSuccess,
  requestAccountErasureResponseError,
  getRequestAccountErasureUrl,
  requestAccountErasureResponse,
  requestAccountErasure,
  getRequestAccountErasureMutationFetcher,
  getRequestAccountErasureMutationKey,
} from './fetchers';

export type GetAccountProfileQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAccountProfile>>
>;

/**
 * @summary Get the signed-in user's profile
 */
export const useGetAccountProfile = <
  TError = Promise<UnauthorizedResponse>,
>(options?: {
  swr?: SWRConfiguration<
    Awaited<ReturnType<typeof getAccountProfile>>,
    TError
  > & { swrKey?: Key; enabled?: boolean };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getGetAccountProfileKey() : null));
  const swrFn = () => getAccountProfile(fetchOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions
  );

  return {
    swrKey,
    ...query,
  };
};

export type UpdateAccountProfileMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateAccountProfile>>
>;

/**
 * @summary Patch the signed-in user's profile
 */
export const useUpdateAccountProfile = <
  TError = Promise<BadRequestResponse | UnauthorizedResponse>,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof updateAccountProfile>>,
    TError,
    Key,
    UpdateProfileRequest,
    Awaited<ReturnType<typeof updateAccountProfile>>
  > & { swrKey?: string };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getUpdateAccountProfileMutationKey();
  const swrFn = getUpdateAccountProfileMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type GetAccountPreferencesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAccountPreferences>>
>;

/**
 * @summary Get notification preferences
 */
export const useGetAccountPreferences = <
  TError = Promise<UnauthorizedResponse>,
>(options?: {
  swr?: SWRConfiguration<
    Awaited<ReturnType<typeof getAccountPreferences>>,
    TError
  > & { swrKey?: Key; enabled?: boolean };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getGetAccountPreferencesKey() : null));
  const swrFn = () => getAccountPreferences(fetchOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions
  );

  return {
    swrKey,
    ...query,
  };
};

export type UpdateAccountPreferencesMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateAccountPreferences>>
>;

/**
 * @summary Patch notification preferences
 */
export const useUpdateAccountPreferences = <
  TError = Promise<BadRequestResponse | UnauthorizedResponse>,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof updateAccountPreferences>>,
    TError,
    Key,
    UpdatePreferencesRequest,
    Awaited<ReturnType<typeof updateAccountPreferences>>
  > & { swrKey?: string };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getUpdateAccountPreferencesMutationKey();
  const swrFn = getUpdateAccountPreferencesMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type GetAccountConsentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAccountConsents>>
>;

/**
 * @summary List the latest consent decision per document
 */
export const useGetAccountConsents = <
  TError = Promise<UnauthorizedResponse>,
>(options?: {
  swr?: SWRConfiguration<
    Awaited<ReturnType<typeof getAccountConsents>>,
    TError
  > & { swrKey?: Key; enabled?: boolean };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getGetAccountConsentsKey() : null));
  const swrFn = () => getAccountConsents(fetchOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions
  );

  return {
    swrKey,
    ...query,
  };
};

export type RecordAccountConsentMutationResult = NonNullable<
  Awaited<ReturnType<typeof recordAccountConsent>>
>;

/**
 * @summary Record a consent decision
 */
export const useRecordAccountConsent = <
  TError = Promise<BadRequestResponse | UnauthorizedResponse>,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof recordAccountConsent>>,
    TError,
    Key,
    RecordConsentRequest,
    Awaited<ReturnType<typeof recordAccountConsent>>
  > & { swrKey?: string };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getRecordAccountConsentMutationKey();
  const swrFn = getRecordAccountConsentMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export type ExportAccountDataQueryResult = NonNullable<
  Awaited<ReturnType<typeof exportAccountData>>
>;

/**
 * @summary Export pact-account-owned data for the signed-in user (GDPR Art. 15)
 */
export const useExportAccountData = <
  TError = Promise<UnauthorizedResponse>,
>(options?: {
  swr?: SWRConfiguration<
    Awaited<ReturnType<typeof exportAccountData>>,
    TError
  > & { swrKey?: Key; enabled?: boolean };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ??
    (() => (isEnabled ? getExportAccountDataKey() : null));
  const swrFn = () => exportAccountData(fetchOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions
  );

  return {
    swrKey,
    ...query,
  };
};

export type RequestAccountErasureMutationResult = NonNullable<
  Awaited<ReturnType<typeof requestAccountErasure>>
>;

/**
 * @summary Request erasure of the signed-in user's data (GDPR Art. 17)
 */
export const useRequestAccountErasure = <
  TError = Promise<UnauthorizedResponse>,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof requestAccountErasure>>,
    TError,
    Key,
    Arguments,
    Awaited<ReturnType<typeof requestAccountErasure>>
  > & { swrKey?: string };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getRequestAccountErasureMutationKey();
  const swrFn = getRequestAccountErasureMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
