/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */

import type { Key } from 'swr';

import type {
  BoundaryErrorResponse,
  ClassifierLabelVerdictRequest,
  ClassifierLabelVerdictResponse,
} from './types';

import { customFetch } from '../custom_fetch';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type labelVerdictResponse200 = {
  data: ClassifierLabelVerdictResponse;
  status: 200;
};

export type labelVerdictResponse400 = {
  data: string;
  status: 400;
};

export type labelVerdictResponse401 = {
  data: string;
  status: 401;
};

export type labelVerdictResponse403 = {
  data: string;
  status: 403;
};

export type labelVerdictResponse429 = {
  data: string;
  status: 429;
};

export type labelVerdictResponse502 = {
  data: BoundaryErrorResponse;
  status: 502;
};

export type labelVerdictResponse503 = {
  data: BoundaryErrorResponse;
  status: 503;
};

export type labelVerdictResponse504 = {
  data: BoundaryErrorResponse;
  status: 504;
};

export type labelVerdictResponseSuccess = labelVerdictResponse200 & {
  headers: Headers;
};

export type labelVerdictResponseError = (
  | labelVerdictResponse400
  | labelVerdictResponse401
  | labelVerdictResponse403
  | labelVerdictResponse429
  | labelVerdictResponse502
  | labelVerdictResponse503
  | labelVerdictResponse504
) & {
  headers: Headers;
};

export type labelVerdictResponse =
  labelVerdictResponseSuccess | labelVerdictResponseError;

export const getLabelVerdictUrl = () => {
  return `/api/pact/gateway/v1/classifier/label`;
};

/**
 * @summary Label a classifier verdict
 */
export const labelVerdict = async (
  classifierLabelVerdictRequest: ClassifierLabelVerdictRequest,
  options?: RequestInit
): Promise<labelVerdictResponse> => {
  return customFetch<labelVerdictResponse>(getLabelVerdictUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(classifierLabelVerdictRequest),
  });
};

export const getLabelVerdictMutationFetcher = (
  options?: SecondParameter<typeof customFetch>
) => {
  return (_: Key, { arg }: { arg: ClassifierLabelVerdictRequest }) => {
    return labelVerdict(arg, options);
  };
};

export const getLabelVerdictMutationKey = () =>
  [`/api/pact/gateway/v1/classifier/label`] as const;
