'use client';

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */
import useSWRMutation from 'swr/mutation';
import type { Key } from 'swr';
import type { SWRMutationConfiguration } from 'swr/mutation';

import type {
  BoundaryErrorResponse,
  ClassifierLabelVerdictRequest,
  ClassifierLabelVerdictResponse,
} from './types';

import {
  labelVerdictResponse200,
  labelVerdictResponse400,
  labelVerdictResponse401,
  labelVerdictResponse403,
  labelVerdictResponse429,
  labelVerdictResponse502,
  labelVerdictResponse503,
  labelVerdictResponse504,
  labelVerdictResponseSuccess,
  labelVerdictResponseError,
  getLabelVerdictUrl,
  labelVerdictResponse,
  labelVerdict,
  getLabelVerdictMutationFetcher,
  getLabelVerdictMutationKey,
} from './fetchers';

import { customFetch } from '../custom_fetch';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type LabelVerdictMutationResult = NonNullable<
  Awaited<ReturnType<typeof labelVerdict>>
>;

/**
 * @summary Label a classifier verdict
 */
export const useLabelVerdict = <
  TError = BoundaryErrorResponse | string,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof labelVerdict>>,
    TError,
    Key,
    ClassifierLabelVerdictRequest,
    Awaited<ReturnType<typeof labelVerdict>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getLabelVerdictMutationKey();
  const swrFn = getLabelVerdictMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
