/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */

export type CheckRedactorInfoVerdict =
  (typeof CheckRedactorInfoVerdict)[keyof typeof CheckRedactorInfoVerdict];

export const CheckRedactorInfoVerdict = {
  pass_through: 'pass_through',
  redacted: 'redacted',
  unknown: 'unknown',
} as const;
