/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */
import type { CheckWrappedChunk } from './checkWrappedChunk';

export interface CheckSpotlightInfo {
  chunks?: CheckWrappedChunk[];
  /** "delim" | "xml" | "json" */
  format?: string;
  /** system-prompt fragment; only when SPOTLIGHT_INJECT_HEADER=true */
  header?: string;
  source_count?: number;
}
