/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */

export type CheckFilterInfoVerdict =
  (typeof CheckFilterInfoVerdict)[keyof typeof CheckFilterInfoVerdict];

export const CheckFilterInfoVerdict = {
  safe: 'safe',
  suspicious: 'suspicious',
  hostile: 'hostile',
  unknown: 'unknown',
} as const;
