/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */
import type { CheckExternalRefInfoVerdict } from './checkExternalRefInfoVerdict';

export interface CheckExternalRefInfo {
  host?: string;
  purified_content?: string;
  source?: string;
  verdict?: CheckExternalRefInfoVerdict;
}
