/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */

export interface CheckCheckRequest {
  content: string;
  /** ConversationID is an optional client-supplied chat/thread correlation id.
   * Mirrored verbatim onto the pact.decisions audit event so a decision can
   * be traced back to the chat session that produced it. May also be supplied
   * via the X-Pact-Conversation-Id header; the body value wins when both are
   * present. Opaque to the gateway — never parsed or validated. */
  conversation_id?: string;
  /** "input" | "output" */
  kind: string;
}
