/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */

export interface CheckConsensusInfo {
  /** DurationMs is the consensus stage's wall-clock RPC time in fractional
   * milliseconds (PACT-613 convention); present whenever this sub-object
   * is. nil is never emitted as 0. */
  duration_ms?: number;
}
