/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */
import type { CheckExternalRefInfo } from './checkExternalRefInfo';

export interface CheckExternalRefsInfo {
  blocked?: number;
  mitigated?: number;
  refs?: CheckExternalRefInfo[];
  scanned?: number;
}
