/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */

export type CheckSpotlightChunkTrust =
  (typeof CheckSpotlightChunkTrust)[keyof typeof CheckSpotlightChunkTrust];

export const CheckSpotlightChunkTrust = {
  trusted: 'trusted',
  user: 'user',
  untrusted: 'untrusted',
} as const;
