/**
 * Generated by orval 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */

export interface AuthSessionResponse {
  expiresAtUnix?: number;
  mfaRequired?: boolean;
  mfaToken?: string;
  refreshToken?: string;
  returnTo?: string;
  sessionToken?: string;
  userId?: string;
}
