/**
 * Generated by orval 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */

export interface AuthMfaFactorResponse {
  createdAtUnix?: number;
  factorId?: string;
  label?: string;
  type?: string;
  verified?: boolean;
}
