/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * pact-gateway
 * Public REST entrypoint for the PACT safety pipeline.
 * OpenAPI spec version: 0.1.0
 */

export type StartOAuthLoginParams = {
  /**
   * OAuth provider (e.g. google, github)
   */
  provider: string;
  /**
   * Post-login redirect target
   */
  returnTo?: string;
};
