import { type NextRequest } from 'next/server';

import { proxyToGateway } from '@/src/lib/proxy/proxy_to_gateway';

// Edge-side proxy for /v1/files/* into pact-gateway. The hooks
// generated by Orval call /v1/files/ (and friends) directly from the
// browser; this route exists so those calls never have to know the
// gateway's host -- the SPA only ever talks to its own origin, and
// we can swap PACT_GATEWAY_URL between dev/staging/prod without
// rebuilding the bundle.
//
// File bytes do NOT pass through this proxy. The /v1/files/* surface
// only carries metadata + presigned URLs; the browser PUTs and GETs
// the actual bytes against object storage directly.
//
// In mock mode (NEXT_PUBLIC_API_MOCKING=enabled) MSW intercepts the
// fetch in the browser before it reaches Next.js, so this route is a
// no-op fallback. In real mode, every /v1/files/* request lands here.
// See proxy_to_gateway.ts for the shared session-cookie -> Bearer
// translation, refresh-header forwarding, and rotated-session handling.

type RouteContext = { params: Promise<{ path: string[] }> };

async function proxy(req: NextRequest, { params }: RouteContext) {
  const { path } = await params;

  return proxyToGateway(req, {
    upstreamPath: `/v1/files/${path.join('/')}`,
    forwardRefreshHeader: true,
  });
}

export const GET = (req: NextRequest, ctx: RouteContext) => proxy(req, ctx);
export const POST = (req: NextRequest, ctx: RouteContext) => proxy(req, ctx);
export const PUT = (req: NextRequest, ctx: RouteContext) => proxy(req, ctx);
export const PATCH = (req: NextRequest, ctx: RouteContext) => proxy(req, ctx);
export const DELETE = (req: NextRequest, ctx: RouteContext) => proxy(req, ctx);
