import { type NextRequest, NextResponse } from 'next/server';

// Edge-side proxy for /v1/files/* into pact-gateway. The hooks
// generated by Orval call /v1/files/ (and friends) directly from the
// browser; this route exists so those calls never have to know the
// gateway's host -- the SPA only ever talks to its own origin, and
// we can swap PACT_GATEWAY_URL between dev/staging/prod without
// rebuilding the bundle.
//
// File bytes do NOT pass through this proxy. The /v1/files/* surface
// only carries metadata + presigned URLs; the browser PUTs and GETs
// the actual bytes against object storage directly.
//
// In mock mode (NEXT_PUBLIC_API_MOCKING=enabled) MSW intercepts the
// fetch in the browser before it reaches Next.js, so this route is a
// no-op fallback. In real mode, every /v1/files/* request lands here,
// gets the session cookie translated into the Bearer header
// pact-gateway's authMiddleware expects, and is forwarded.

const GATEWAY_URL = process.env.PACT_GATEWAY_URL ?? 'http://localhost:8080';
const SESSION_COOKIE = 'pact_session';
const REFRESH_HEADER = 'x-pact-refresh-token';
const NEW_SESSION_HEADER = 'x-pact-new-session-token';
const NEW_REFRESH_HEADER = 'x-pact-new-refresh-token';
const NEW_EXPIRES_HEADER = 'x-pact-new-expires-at-unix';

type RouteContext = { params: Promise<{ path: string[] }> };

async function proxy(req: NextRequest, { params }: RouteContext) {
  const { path } = await params;
  const target = `${GATEWAY_URL}/v1/files/${path.join('/')}${req.nextUrl.search}`;

  const session = req.cookies.get(SESSION_COOKIE)?.value;
  const headers = new Headers();
  const ct = req.headers.get('content-type');
  if (ct) headers.set('content-type', ct);
  if (session) headers.set('authorization', `Bearer ${session}`);
  const refresh = req.headers.get(REFRESH_HEADER);
  if (refresh) headers.set(REFRESH_HEADER, refresh);

  const hasBody = req.method !== 'GET' && req.method !== 'HEAD';
  const upstream = await fetch(target, {
    method: req.method,
    headers,
    ...(hasBody && { body: req.body, duplex: 'half' }),
  } as RequestInit);

  const out = new Headers();
  upstream.headers.forEach((value, key) => {
    const k = key.toLowerCase();
    if (
      k === 'content-encoding' ||
      k === 'transfer-encoding' ||
      k === 'connection'
    ) {
      return;
    }
    out.set(key, value);
  });
  const newSession = upstream.headers.get(NEW_SESSION_HEADER);
  const newExpires = upstream.headers.get(NEW_EXPIRES_HEADER);
  const res = new NextResponse(upstream.body, {
    status: upstream.status,
    headers: out,
  });
  if (newSession && newExpires) {
    res.cookies.set({
      name: SESSION_COOKIE,
      value: newSession,
      httpOnly: true,
      sameSite: 'lax',
      secure: process.env.NODE_ENV === 'production',
      path: '/',
      expires: new Date(Number(newExpires) * 1000),
    });
  }
  const newRefresh = upstream.headers.get(NEW_REFRESH_HEADER);
  if (newRefresh) {
    res.headers.set(NEW_REFRESH_HEADER, newRefresh);
  }

  return res;
}

export const GET = (req: NextRequest, ctx: RouteContext) => proxy(req, ctx);
export const POST = (req: NextRequest, ctx: RouteContext) => proxy(req, ctx);
export const PUT = (req: NextRequest, ctx: RouteContext) => proxy(req, ctx);
export const PATCH = (req: NextRequest, ctx: RouteContext) => proxy(req, ctx);
export const DELETE = (req: NextRequest, ctx: RouteContext) => proxy(req, ctx);
